### ISSUE TITLE
Error while installing sqlite3 for electron under linux 7.10

### ISSUE THREAD

**Issue by emmarvpol** [mapbox/node-sqlite3#1003]
Hello! Im trying to install sqlite3 for electron under Linux 7.10.
I search how to fix that without luck.
Thanks!

node-gyp: v3.7.0
node-pre-gyp: v0.10.0
node: v6.11.4
electron: v1.4.16

![terminal3](https://user-images.githubusercontent.com/40424838/41655532-d77dd856-7495-11e8-91fd-7ff692f82297.png)

**Comment by springmeyer** [comment]
Try node-sqlite@4.0.1 and watch #1006 if you are still having trouble.
