### ISSUE TITLE
upgrade to node-pre-gyp@0.10.0

### ISSUE THREAD

**Issue by IlanFrumer** [mapbox/node-sqlite3#1005]
https://nodesecurity.io/advisories/612

**Old Version:**
└─┬ sqlite3@4.0.0
  └─┬ node-pre-gyp@0.9.0
    └─┬ rc@1.2.6
      └── deep-extend@0.4.2 

**New Version:**
├─┬ node-pre-gyp@0.10.0
│ └─┬ rc@1.2.8
│   └── deep-extend@0.6.0

**Comment by springmeyer** [comment]
done in 2efda1d
