### ISSUE TITLE
SQLITE_ERROR: no such column with db.get()

### ISSUE THREAD

**Issue by Illuminati4Life** [mapbox/node-sqlite3#1014]
I am using Node.js 8.11.3. The issue is when I am attempting to select a row, like so:
```js
db.serialize(() => {
    db.get('SELECT * FROM example_table WHERE name = test', (err, row) => {
        if (err) console.log(err);
        console.log(row)
    });
})
```

However, when I try to execute this code, it tells me:
`{ Error: SQLITE_ERROR: no such column: test errno: 1, code: 'SQLITE_ERROR' }`

**Comment by ARitz-Cracker** [comment]
I don't know what possessed me to look through previous issues, but your query is wrong. I'm assuming you want:
`'SELECT * FROM example_table WHERE name = "test"`

**Comment by Illuminati4Life** [comment]
It's been a while since i opened this issue, and yeah, I was missing the double quotation marks.
