### ISSUE TITLE
npm install node-sqlite3 fail - node-gyp rebuild fail

### ISSUE THREAD

**Issue by tigernassau** [mapbox/node-sqlite3#1019]
On Debian testing - npm install node-sqlite3 => failing on step node-gyp rebuild script

We have tried all sorts of fixes, such as npm install node-gyp, npm install node-pre-gyp, sudo apt install node-gyp, sudo apt install node-pre-gyp, ....  still fails  yes we have build-essential and g++ installed
1) if the script is trying to recompile, does that require sudo ?  but if we run sudo npm install node-sqlite3 that is going to install somewhere else besides the node modules folder in the project folder

2) is there a work around ?  use of sqlite3 with node is dead in water for us 

3) with postgresql - loading libpq-dev solves the node-gyp issue (not sure why?) 

4) bigger question:  why is node-gyp even a dependency ?  Since it is causing a lot of trouble (based on number of questions posted) - is there another way ?  ie get rid of node-gyp dependency

**Comment by tigernassau** [comment]
yes, we do not want to use sudo to npminstall but as we said we get a permission error 
are we missing a step to load the pre-complied binary ?  
code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sqlite3@0.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sqlite3@0.0.3 install script.

**Comment by springmeyer** [comment]
Did you try `npm install --unsafe-perm`?  (https://github.com/mapbox/node-pre-gyp/wiki/Troubleshooting)

**Comment by tigernassau** [comment]
thks will try if necessary - we just did npm install sqlite3  - will see if this works for us instead - not sure what node-sqlite3 gives us instead

**Comment by zomilanovic** [comment]
@tigernassau have you already tried it? If so did it help, since we have a similar problem.
