### ISSUE TITLE
Build fails with electron and node 10

### ISSUE THREAD

**Issue by magne4000** [mapbox/node-sqlite3#1020]
- **os**: macOS 10.13.5
- **node**: 10.6.0
- **electron**: 2.x, 3.0.0-beta.1
- **electron-builder**: 20.20.4
- **sqlite3**: 3.x, 4.0.1
- **yarn**: 1.7.0 (or **npm** 6.1.0)

I have an electron project which leverages `electron-builder` and uses `sqlite3`.
I upgraded to [node 10](https://github.com/electron/electron/projects/10?card_filter_query=node+10.2.0) to test electron 3.0, and got the following error (I had no issue with node 8 and electron 2.x. Also tried with node 8 and electron 3.0, no issue either):

### Important part of the error message
```
sed: ./Release/.deps/Release/obj.target/node_sqlite3/src/database.o.d.raw: No such file or directory
rm: ./Release/.deps/Release/obj.target/node_sqlite3/src/database.o.d.raw: No such file or directory
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/magne/workspace/browserX/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/Users/magne/workspace/browserX/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/magne/workspace/browserX/node_modules/sqlite3/lib/binding/electron-v3.0-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/magne/workspace/browserX/node_modules/sqlite3/lib/binding/electron-v3.0-darwin-x64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/magne/workspace/browserX/node_modules/sqlite3
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
```

#### sqlite3 v4
https://gist.github.com/magne4000/9ecca538fe2acfac751203ad7fd41c82#file-trace-txt-L765

#### sqlite3 v3
https://gist.github.com/magne4000/2dd40526e2a70ddb3c1fa2a005a0ad36#file-trace-txt-L97

**Comment by springmeyer** [comment]
This looks very difficult to debug and not something that I am able to help with. Never seen these `sed` errors. So I suspect some kind of misconfiguration on your system, and that if you try on a fresh machine it will likely work. Also Perhaps @kewde (who recently worked on electron support) has ideas. 

What I can say is that we provide (thanks to @kewde) binaries for electron versions as seen here: https://github.com/mapbox/node-sqlite3/blob/0fdfafce601e75660fa433fbdc62ae6baeaacd59/.travis.yml#L113-L146

So if you use an older version of electron it may work.

**Comment by kewde** [comment]
CI doesn't seem to have an issue compiling #1021

**Comment by kewde** [comment]
@magne4000 can we close this?

**Comment by magne4000** [comment]
Yep
