### ISSUE TITLE
rowid question

### ISSUE THREAD

**Issue by Foggyx420** [mapbox/node-sqlite3#1024]
Could not find a forum to ask on or much of anything on google.
a table
I make tables in database:
example:
`CREATE TABLE IF NOT EXISTS 'tablename' (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL);`

it works great and i insert data into it no problems. I vacuum regularly (manually of course in code) after im done with a table completely

Now i use row count of a table to loop through pulling the key and value for certain functions however for first time I run into an issue with only one of the 24 tables created even on fresh db. row count is 1762 for the specific table however there is a missing rowids in that table. all others i can increment each one without issue.

I'll do a `SELECT key, value FROM 'tablename' WHERE ROWID = numberhere;

works on all other tables without issue except one table where it craps out partly through  the iteration as it is not able to pull by the row id to pull the key and value. 

after a few tests I noticed that the remaining three rows are after that count number. so `SELECT key, value FROM 'tablename' WHERE ROWID = 1763; up to 1766 have data despite having only 1762 rows

Any idea why making a fresh table and inserting data may skip a rowid here and there?  its only in that specific table. anytime there is a failure in my code it exits out and does not continue so that would not affect this as each time it is started a new fresh db is made. any ideas?

**Comment by kroggen** [comment]
if you wanna consistent row ids, use an explicit column for that:

`id INTEGER PRIMARY KEY`

If you will use the text as a primary key you can use a `WITHOUT ROWID` table

**Comment by Foggyx420** [comment]
ok thanks i ended up making a way to dump table instead
