### ISSUE TITLE
Access denied on AWS binaries

### ISSUE THREAD

**Issue by laurent22** [mapbox/node-sqlite3#1037]
Not sure if this is an issue on my end or a problem with the Sqlite3 package, but some users are reporting some troubles when trying to build my application. Electron-builder tries to download a pre-built binary but that results in a 403 Access Denied error. For example this one:

https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-linux-x64.tar.gz

Personally I can build it fine and Travis too, but since several users [have reported the problem](https://discourse.joplin.cozic.net/t/issues-with-running-the-electron-client/421) I thought it could be an issue with node-sqlite3 release process. Any idea what could cause this 403 error? Should this file be downloadable or is the access denied on purpose? If so is there any workaround?

This the result of `yarn dist`:

```
$ yarn dist
yarn run v1.9.4
$ node_modules/.bin/electron-builder
  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder-effective-config.yaml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=sqlite3
Error: /usr/bin/node8 exited with code 1
Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.38
node-pre-gyp info using node@8.11.4 | linux | x64
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and electron@1.8.7 (electron-v1.8 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-linux-x64.tar.gz 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ebayer/workspace/dev/repos/git/joplin/ElectronClient/app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at emitOne (events.js:116:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:211:7)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:372:16)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Linux 4.18.5-1-default
node-pre-gyp ERR! command "/usr/bin/node8" "/home/ebayer/workspace/dev/repos/git/joplin/ElectronClient/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ebayer/workspace/dev/repos/git/joplin/ElectronClient/app/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.11.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok 
error Command failed with exit code 1.
```

**Comment by kkaefer** [comment]
S3 sends 403 even when the files don't exist. We're not providing binaries for electron.

**Comment by kewde** [comment]
@laurent22 electron support has only been provided in later releases.
Please update to the latest node-sqlite3.

There is a known issue with the osx binaries, they are not published. I am resolving it #1041 .

**Comment by fmuntean** [comment]
still getting this issue accessing the follwing url:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.2/node-v64-linux-arm.tar.gz

the response is:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>1506470372ADE87D</RequestId>
<HostId>
fz8Ke0LJsdYVLh+aNjZp80CwIEq0cOd8sVR1ndYComrlLzalfw1963FLROgDatbLqRBakvyRqQc=
</HostId>
</Error>

I am trying to install the latest sqlite3@4.0.2 on a raspberry PI

**Comment by kkaefer** [comment]
We're not publishing binaries for ARM/Raspberry PI. However, you can compile node-sqlite3 yourself for Raspberry PI.

**Comment by fionaabbott** [comment]
I'm getting the access denied message using NodeJS@11.0.0 on Windows 10:

[https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-win32-x64.tar.gz](https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v67-win32-x64.tar.gz)
