### ISSUE TITLE
Enable FTS by Default

### ISSUE THREAD

**Issue by mikeptweet** [mapbox/node-sqlite3#104]
Would it be possible to enable FTS by default as part of the standard build?

Simply add the following to sqlite3.c
# define SQLITE_ENABLE_FTS4
# define SQLITE_ENABLE_FTS3

**Comment by vivekdaramwalwy** [comment]
I need SQLITE_ENABLE_FTS3_PARENTHESIS. Can you please enable it.

**Comment by springmeyer** [comment]
@vivekdaramwalwy - to get this working you can build from source. Do:

```bash
export CFLAGS="-DSQLITE_ENABLE_FTS3_PARENTHESIS"
npm install sqlite3 --build-from-source
```

If you want to see this enabled in the default pre-compiled binaries for node-sqlite we would need a PR that enables it at https://github.com/mapbox/node-sqlite3/blob/f1456b1cc96e89b82ac37b1896f23ef14aff80b6/deps/sqlite3.gyp#L81-L86 and provides a test demonstrating it is working.
