### ISSUE TITLE
Cannot install the node-sqlite3

### ISSUE THREAD

**Issue by Santhoshkumar113** [mapbox/node-sqlite3#1045]
$ npm install sqlite3@3.1.13

> sqlite3@3.1.13 install D:\SanthoshkumarV\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.9.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz

**Comment by fionaabbott** [comment]
I'm running into the same problem.

**Comment by kewde** [comment]
Node v10 support was recently added in 4.0.1
