### ISSUE TITLE
koa and sqlite3 node REST endpoint returning only Database object instead of data

### ISSUE THREAD

**Issue by harrylincoln** [mapbox/node-sqlite3#1046]
Having an issue on a koa route where the data is not being returned correctly, instead getting the instance of the Database object.

**Requesting data like so from koa route:**

`db.connection.all('SELECT * FROM meter_reads', [], (error, data) => data);`

**Unwanted result:**

`Database { open: true, filename: ':memory:', mode: 65542 }`

**More information/code here:**

https://stackoverflow.com/questions/52518527/koa-and-sql3lite-node-rest-endpoint-returning-only-database-object-instead-of-da

**Comment by gms1** [comment]
```
ctx.body = await db.connection.all('SELECT * FROM meter_reads', (err, data) => data)
```
'all' does not return any value ( it returns the result by calling the given callback) so you are actually awaiting 'db.connection' in this line of code
there are some libraries based on node-sqlite3 providing promise based API and more
e.g
https://www.npmjs.com/package/sqlite
or mine:
https://www.npmjs.com/package/sqlite3orm
