### ISSUE TITLE
Cannot run NPM | I tried to run NPM and I got the below errors, I'm new to NPM and it'll be great if someone can explain how can this be fixed.

### ISSUE THREAD

**Issue by atikullamerchant** [mapbox/node-sqlite3#1048]
[~/Desktop/awesome-node]
atikulla-> sudo npm start
Password:
npm ERR! path /Users/atikulla/Desktop/awesome-node/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/atikulla/Desktop/awesome-node/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/atikulla/.npm/_logs/2018-10-03T17_33_17_900Z-debug.log
[~/Desktop/awesome-node]
atikulla-> npm -v
6.4.1
[~/Desktop/awesome-node]

**Comment by cfanoulis** [comment]
try running `npm init`. Also this doesn't seem like an sqlite3 issue 😄

**Comment by kewde** [comment]
This is not related to node-sqlite3, closing.
