### ISSUE TITLE
Failed to build node-sqlite3 on Windows 7

### ISSUE THREAD

**Issue by anta40** [mapbox/node-sqlite3#106]
I tried these 3 ways to install node-sqlite3 on 32-bit Windows 7 (VS 2012, Python 2.7.2):
npm install sqlite3 --msvs_version=2012
npm install sqlite3 --msvs_version=v110
npm install sqlite3 --msvs_version=auto

None of them succed. Here's the build log:
http://pastebin.com/9LuPJL9f

Is there any 'easy' treatment for this problem?
I assume building this on Linux is straightforward, and I'm fine with it, but unfortunately my work PC is running Windows :|

**Comment by speedneeder** [comment]
@ErisDS  
Hi, I have the same problem like you, and I try all the way to solve it but it still exist.I try to download the folder you had upload, but the two link are both invalid.

Would you please upload it again? My system is Win7. Thank you very much!

**Comment by ErisDS** [comment]
@speedneeder this issue is well over a year old, node-sqlite3 has changed considerably in that time - you'll likely need a different solution.

**Comment by speedneeder** [comment]
@ErisDS 
I am a beginner of programming, so there are many things I dont know, thanks for your reply! :)
