### ISSUE TITLE
Precompiled binaries return 403 forbidden

### ISSUE THREAD

**Issue by kornelski** [mapbox/node-sqlite3#1081]
I'm using Node v9 on Debian 9 (stretch). Installation via npm or yarn tries to download a file that returns 403. It's reproducible even without npm:

```sh
curl -I 'https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-linux-x64.tar.gz'
HTTP/1.1 403 Forbidden
```

I've tried from a few locations, and I always get 403. Is this normal? Is this file expected to exist?

**Comment by kewde** [comment]
You're using v3.1.8 with Node v9.

https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#319
-> Node v8 support was added in v3.1.9
-> Use node-sqlite3 v4.0.4 instead
