### ISSUE TITLE
Sqlite3 Security Vulnerability 

### ISSUE THREAD

**Issue by onen5** [mapbox/node-sqlite3#1095]
Sqlite has updated to 3.26.0 which fixes the security vulnerability.   Bincrafters (conan-sqlite3) has updated to support 3.26.0 as well, if you're using them to build.

3.24 -> 3.26 seemed to be fairly safe for an upgrade.

Here is the vuln report.
https://blade.tencent.com/magellan/index_en.html?fbclid=IwAR1ly0LPd9ltmXEIW-HMxmH40E2iCybRP9YA0s1gSoakt3cSv5iG-NFDffc

**Comment by onen5** [comment]
I see there was a merge created already.

**Comment by LightZam** [comment]
refer to https://github.com/mapbox/node-sqlite3/pull/1088

**Comment by onen5** [comment]
Thanks.  I found that, which is why I closed the ticket.

Still waiting for the NPM update.  Trying to avoid a temporary hack on my end.
