### ISSUE TITLE
Is Sqlite3 compatible with Node V10.12.2 on AIX?

### ISSUE THREAD

**Issue by harshsinghania** [mapbox/node-sqlite3#1097]
I wanted to know is sqlite3 is compatible with node v10 on Aix or not?

I was trying to install sqlite3, the following error is being reproduced:

            gyp ERR! stack Error: `gmake` failed with exit code: 2

And the Binary file is also not Found in the S3 bucket:

    node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/node-v64-aix-ppc64.tar.gz

    node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and node@10.4.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

**Comment by kewde** [comment]
There is no support for AIX.
