### ISSUE TITLE
Support electron v4.0

### ISSUE THREAD

**Issue by pupupu-land** [mapbox/node-sqlite3#1099]
Hi,With new version of electron v4.0 aren't available:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/electron-v4.0-win32-x64.tar.gz

**Comment by kewde** [comment]
#1098

**Comment by jettangs** [comment]
npm install https://github.com/mapbox/node-sqlite3/tarball/kewde-4.0.5
