### ISSUE TITLE
Cannot find module sqlite3/lib/binding/node-v57-android-arm64/node_sqlite3.node

### ISSUE THREAD

**Issue by wtchaos** [mapbox/node-sqlite3#1101]
Error:Cannot find module '/storage/emulated/0/data/com.tchaos.test/nodejs/server/node_modules/sqlite3/lib/binding/node-v57-android-arm64/node_sqlite3.node'
does it mean I should execute "npm install" at android system?But it is error when i execute the command at android system(the android system not root).
Can someone help?Thanks.

**Comment by kewde** [comment]
Install the code from source, make sure it compiles on your system.

**Comment by rajagupt01** [comment]
node_modules/sqlite3/lib/binding/node-v72-android-arm64/node_sqlite3.node

**Comment by rajagupt01** [comment]
Not complied

**Comment by ahmadwaliesipick** [comment]
@rajagupt01  any solution?
