### ISSUE TITLE
AppVeyor builds fail for 4.0.5

### ISSUE THREAD

**Issue by kewde** [mapbox/node-sqlite3#1105]
The AppVeyor builds are failing, by default.
It seems like it is an authentication issue, which is out of my control.
https://help.appveyor.com/discussions/problems/11287-the-build-phase-is-set-to-msbuild-mode-default-but-no-visual-studio-project-or-solution-files-were-found

Nothing changed in the commits that should cause this failure, you can check the history here.
https://ci.appveyor.com/project/mapbox/node-sqlite3/history

This means that there are no windows builds for the 4.0.5 release.

@springmeyer @mapsam

**Comment by kewde** [comment]
I've unpublished 4.0.5 in the mean time.

**Comment by mapsam** [comment]
Hey @kewde this looks odd - and seems related to the Mapbox github org authentication. I'll ping our security team to see if they have changed anything regarding appveyor recently.

**Comment by mapsam** [comment]
@kewde we've re-authenticated appveyor for the mapbox org and builds appear to be working again! 4.0.5 binaries are published to confirm https://ci.appveyor.com/project/Mapbox/node-sqlite3/builds/21442657 - apologies for the bump, but 👍 on just incrementing to 4.0.6 to avoid any confusion.

**Comment by NilSet** [comment]
Looking forward to a 4.0.6 publish, we would like to update and get past the Magellan vulnerabilities.

**Comment by kewde** [comment]
@mapsam Thanks!

@NilSet, I've triggered the builds, awaiting the green check mark and then publishing to npm.

 #e173ebc
