### ISSUE TITLE
my windows10 have already sqlite3,exe, but node-pre-gyp still download new binary, and failed!

### ISSUE THREAD

**Issue by anlexN** [mapbox/node-sqlite3#1106]
node-sqlite3 v4.0.4
node version v10.15.0
operating system and architecture you are running, e.g. Windows 10 pro 64 bit.
![image](https://user-images.githubusercontent.com/8686739/50811267-9337ee00-1348-11e9-8e1b-fa7c888913be.png)

**Comment by kewde** [comment]
Your system is using Python3, install Python2 and force the usage.
```
npm install --build-from-source --python=C:\Python2\python.exe
```
