### ISSUE TITLE
[Missing binaries] not found node-v57-linux-arm.tar.gz v4.0.6

### ISSUE THREAD

**Issue by ptkdev** [mapbox/node-sqlite3#1110]
When trying to install it on raspbian, it outputs error message:

```
> sqlite3@4.0.6 install node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.6/node-v57-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.6 and node@8.15.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
```

**Comment by mpowell90** [comment]
On successful build of this binary within project using the following
`npm install --target-arch=arm --target_platform=linux`
Once run on device I get the following error:
`Error: /usr/server/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node: invalid ELF header`

I've really hit a wall with this, any assistance is greatly appreciated!
Happy to open another issue if not relevant to this one.

System Details:
Dev computer: Mac OSX v10.13.6
Dev computer 2: CentOS Linux release 7.5.1804 (Core)
Device: Atmel SAMA5D27-SOM1-EK Development Board
Linux Distribution: Custom with Buildroot, using glibc - Node v8.14.0, npm

**Comment by kewde** [comment]
https://github.com/mapbox/node-sqlite3/pull/1028
^a docker image and simple instructions.

ARM builds are currently not supported.

**Comment by mpowell90** [comment]
Thank You @kewde 
This works as expected - I directly replaced the binaries built on mac, on the Atmel SAMA5D27-SOM1-EK Development Board.
