### ISSUE TITLE
Issues with building on arm.

### ISSUE THREAD

**Issue by RomanBurunkov** [mapbox/node-sqlite3#1111]
Hi,

Quite often get the same issue during compiling node-sqlite3 for ARM boards(Raspberry, Orange, and other pis).

That is frustrating that there are no prebuild packages for ARM and bulding node-sqlite from source often fails.
As a result updating on new version or installing on new system becomes very inconvinient and hard process.

Currently I've got the following error during building module from sources on Orange Pi Zero:

```
Release/obj/gen/sqlite-autoconf-3240000/sqlite3.c:189875:5: note: here
     default: {
     ^~~~~~~
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
deps/sqlite3.target.mk:127: recipe for target 'Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3240000/sqlite3.o] Error 4
make: Leaving directory '/krisberg/tma/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.13-sunxi
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /krisberg/tma/node_modules/sqlite3
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/krisberg/tma/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.19.13-sunxi
node-pre-gyp ERR! command "/usr/bin/node" "/krisberg/tma/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /krisberg/tma/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=3 --node_abi_napi=napi' (1)
npm WARN tm-audio@0.0.6 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-20T07_55_26_014Z-debug.log
```

debug.log:
```
285 verbose stack Error: sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
285 verbose stack Exit status 1
285 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
285 verbose stack     at emitTwo (events.js:126:13)
285 verbose stack     at EventEmitter.emit (events.js:214:7)
285 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
285 verbose stack     at emitTwo (events.js:126:13)
285 verbose stack     at ChildProcess.emit (events.js:214:7)
285 verbose stack     at maybeClose (internal/child_process.js:915:16)
285 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
286 verbose pkgid sqlite3@4.0.4
287 verbose cwd /krisberg/tma
288 verbose Linux 4.19.13-sunxi
289 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
290 verbose node v8.15.0
291 verbose npm  v6.4.1
292 error code ELIFECYCLE
293 error errno 1
294 error sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
294 error Exit status 1
295 error Failed at the sqlite3@4.0.4 install script.
295 error This is probably not a problem with npm. There is likely additional logging output above.
296 verbose exit [ 1, true ]
```
Is there any chance having prebuilt package for ARM architecture or any way to resolve this common issue with building module from sources?

Thanks,
Roman.

**Comment by kewde** [comment]
Please use #1028 to generate builds for ARM, thanks.

**Comment by tkurki** [comment]
Prebuilt binaries would solve this problem nicely, see #418

**Comment by RomanBurunkov** [comment]
Still struggling building this module for arm.
I've checked  mentioned threads but didn't catch what to do.

**Comment by RomanBurunkov** [comment]
Getting the following:

Release/obj/gen/sqlite-autoconf-3260000/sqlite3.c:178807:5: note: here
     default: {
     ^~~~~~~
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
deps/sqlite3.target.mk:127: recipe for target 'Release/obj.target/sqlite3/gen/sqlite-autoconf-3260000/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3260000/sqlite3.o] Error 4
make: Leaving directory '/krisberg/tma/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.25-sunxi
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /krisberg/tma/node_modules/sqlite3
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/krisberg/tma/node_modules/sqlite3/lib/binding/node-v57-linux-arm --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/krisberg/tma/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.19.25-sunxi
node-pre-gyp ERR! command "/usr/bin/node" "/krisberg/tma/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /krisberg/tma/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
