### ISSUE TITLE
runtime error ng serve

### ISSUE THREAD

**Issue by sante85** [mapbox/node-sqlite3#1115]
sqlite3 v4.0.6
env Windows/linux
angular 7/ electron 4

import {Injectable} from '@angular/core';
import {Database} from 'sqlite3';
import {Observable} from 'rxjs';
@Injectable()
export class SqliteService {
  private db: Database;
  constructor() {
    this.db = new Database('dbname.db');
  }
}

if I call sqlite3, in console this is the output

WARNING in ./node_modules/sqlite3/lib/sqlite3.js 4:14-35
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js 17:20-67
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/sqlite3/node_modules/node-pre-gyp/lib/pre-binding.js 20:22-48
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/npm/lib/npm.js 124:16-56
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/npm/lib/npm.js 235:10-25
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/npm/node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/node-gyp/lib/Find-VS2017.cs 7:6
Module parse failed: Unexpected token (7:6)
You may need an appropriate loader to handle this file type.
| // Usage:
| // powershell -ExecutionPolicy Unrestricted -Version "2.0" -Command "&{Add-Type -Path Find-VS2017.cs; [VisualStudioConfiguration.Main]::Query()}"
> using System;
| using System.Text;
| using System.Runtime.InteropServices;

ERROR in ./node_modules/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in 'star-menu-app\node_modules\node-gyp\lib'
ERROR in ./node_modules/npm/bin/npm-cli.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
> #!/usr/bin/env node
| ;(function () { // wrapper in case we're in module_context mode
|   // windows: running "npm blah" in this folder will invoke WSH, not node.
i ｢wdm｣: Failed to compile.

and not run right.

Do you have any solution?

Best regards

**Comment by kewde** [comment]
Seems like a WebPack issue.
