### ISSUE TITLE
Unused buffer in issue-108.test.js

### ISSUE THREAD

**Issue by Broxzier** [mapbox/node-sqlite3#1118]
While looking through the tests, I found this oddity:

https://github.com/mapbox/node-sqlite3/blob/7eda5eee0c98d8deb2a89f3d6348f8f57ec0f9e1/test/issue-108.test.js#L20

`buff` doesn't appear to be used, a raw string `'a'` is though. Was this done intentionally?

**Comment by kewde** [comment]
Thanks!
