### ISSUE TITLE
Question about installing against an external sqlite

### ISSUE THREAD

**Issue by jflewis** [mapbox/node-sqlite3#1120]
Hi all, having a odd problem that I could use some eyes on. 
version: 4.0.0
OS: Docker (Debian) 
Node: 8.10

In order to get around the max expression depth of 1000 I needed to install sqlite manually with special compile time flag. The sqlite install and node-sqlite3 install both install correctly without any errors. I can enter the docker container, run sqlite, run the limit command and see the following...

```
sqlite> .limit
              length 1000000000
          sql_length 1000000000
              column 2000
          expr_depth 3000
     compound_select 500
             vdbe_op 250000000
        function_arg 127
            attached 10
 like_pattern_length 50000
     variable_number 999
       trigger_depth 1000
      worker_threads 0
```
You can see that the expr_depth is now set to 3000.

The issue is that when I run my code, I  get the following error...

```
{ Error: SQLITE_ERROR: Expression tree is too large (maximum depth 1000) errno: 1, code: 'SQLITE_ERROR' }
```

I'm confused as to why this module isn't respecting the new limit I'm setting.

I've attached the Dockerfile and relevant logs. If I could get some eyes on this that would be awesome. Maybe I'm missing something obvious.

```docker
FROM node:8.10
RUN apt-get update  \
    && apt-get -y install libsqlite3-dev

WORKDIR /usr/src/app

RUN wget https://www.sqlite.org/snapshot/sqlite-snapshot-201902021347.tar.gz \
    && tar xvfz sqlite-snapshot-201902021347.tar.gz


RUN cd sqlite-snapshot-201902021347 \
    && CFLAGS="-DSQLITE_THREADSAFE=1 -DHAVE_USLEEP=1 -DSQLITE_MAX_EXPR_DEPTH=3000" ./configure \
    && make \
    && make install

COPY ./rules-engine/package*.json ./

RUN npm install --build-from-source --sqlite=/usr/local  --verbose

COPY functions/models functions/models/
COPY rules-engine/ rules-engine/

CMD [ "npm", "start"]
```

Build logs: https://gist.github.com/jflewis/b71dbecaaf0b692494561ebc65c4c25c

**Comment by kewde** [comment]
Look into the node-gyp files, the additional "-DSQLITE_MAX_EXPR_DEPTH=3000" should be put there.
The docker example you provided will create a normal version of sqlite.

However, running this will do another build (the actual native .node file that will be included):
```
RUN npm install --build-from-source --sqlite=/usr/local  --verbose
```

Add the flags here (and in the other array):
https://github.com/mapbox/node-sqlite3/blob/master/deps/sqlite3.gyp#L80
