### ISSUE TITLE
Why the request dependency?

### ISSUE THREAD

**Issue by domachine** [mapbox/node-sqlite3#1132]
I noticed the `request` dependency on the npm package page. A quick search (using github) through the code didn't reveal any usage. Can this dependency be removed?

**Comment by kewde** [comment]
https://github.com/mapbox/node-sqlite3/commit/0fdfafce601e75660fa433fbdc62ae6baeaacd59

It seems to be used in node-pre-gyp. If the dependency is available, it would use the request.

**Comment by export-mike** [comment]
Seems a bit odd you have to explicitly set request in this package though even if you are using node-pre-gyp
