### ISSUE TITLE
Can't open DB with OPEN_READONLY

### ISSUE THREAD

**Issue by MChelik** [mapbox/node-sqlite3#1135]
Hello,
Thank you for the awesome library. I'm using it and everything works fine except that when I try to open database with **OPEN_READONLY**, it gives me "_SQLITE_MISUSE: bad parameter or other API misuse_" error. So I have to use **OPEN_READWRITE** to be able to use the library.
Is this a problem with library or am I doing something wrong?

```
function connectToLogDatabase() {
  db = new sqlite3.Database(global.LOG_DATABASE_PATH, sqlite3.OPEN_READONLY | sqlite3.OPEN_CREATE, (err: any) => {
    if (err) console.log(err.message);
    else connectedToDB = true;
  });
}
```

**Comment by bruce-one** [comment]
I believe `sqlite3.OPEN_READONLY` and `sqlite3.OPEN_CREATE` are mutually exclusive -> eg how can the database be created if the connection is readonly?

I can't find an exact reference to that in the Sqlite documentation, however it does have

> SQLITE_OPEN_READONLY
> The database is opened in read-only mode. If the database does not already exist, an error is returned.
> ...
> SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE
> The database is opened for reading and writing, and is created if it does not already exist. This is the behavior that is always used for sqlite3_open() and sqlite3_open16().

is the closest I can get as a it demonstrates that `SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE` is accepted/logical, but READONLY and CREATE isn't.

Hence, just use:

```
  db = new sqlite3.Database(global.LOG_DATABASE_PATH, sqlite3.OPEN_READONLY, (err: any) => {
    if (err) console.log(err.message);
    else connectedToDB = true;
  });
```

and handle the error by retrying or ignoring?

**Comment by MChelik** [comment]
Hello Bruce,
READ_ONLY alone worked! Thank you for your reply :)
