### ISSUE TITLE
Pre-build scenarios for less powerful systems

### ISSUE THREAD

**Issue by Truemedia** [mapbox/node-sqlite3#1136]
Hi,
So I am looking to use this library on an ARM6 system with very low specs.

I already have the latest version of nodeJS and npm installed, aswell as maria db.

My problem is when installing this module with no precompiled binary available on AWS, it trys to compile itself but the system has such low processing power and with it being headless over a SSH session, during the process (hour or 2 in) the SSH connection closes and the build process subsequently stops.

Just wondering if there is a way to pre-compile the binaries on a seperate more powerful system (arm7), and make the install on the ARM6 system used the pre-compiled binary from a custom location.

Would really like to use this on IOT devices.

**Comment by adipascu** [comment]
@Truemedia 
Possible solutions
 - cross-compilation from a more powerful system
 - using a tool like tmux to keep apps running over SSH in a detached mode
 - compiling in a VM from a more powerful system

ARMv6 is not a very popular platform, I do not see it getting prebuilt binaries for it soon.

**Comment by Truemedia** [comment]
Will look into those options thanks

**Comment by tkurki** [comment]
See https://github.com/mapbox/node-sqlite3/issues/418#issuecomment-484224355 for a way to cross build with Docker.
