### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by BridgeAR** [mapbox/node-sqlite3#1138]
The current sqlite3 version does not work together with Node.js v12.0.0-pre. This is already fixed on master but there's no new version released so far. I would like to point out that the official release date for Node.js v12 is very soon and it would be great to have a clean [CITGM](https://github.com/nodejs/citgm) result on Node.js side.

Is there a plan to release a new version anytime soon?

**Comment by BridgeAR** [comment]
Ping @kewde @gms1 @bruce-one @rzr

**Comment by rzr** [comment]
I can manually rebuild binaries for arm, arm64 x86 x64

**Comment by BridgeAR** [comment]
@rzr sorry, I am not sure I can follow. The sqlite3 master branch has a fix that allows it to build against Node.js master (or at least it should) but that fix is not yet in an official sqlite3 release. CITGM will always use the latest official release and the last release still fails. We skip sqlite3 on that version because of the failure and it would be great to get it working again.

**Comment by johan13** [comment]
Node.js v12 was released today. Is there any news on when a version with node 12 support will be made available on npmjs?

As far as I understand, the compatibility issues have been fixed in master and we just need a new release, right?

**Comment by ForsakenHarmony** [comment]
Reported 29 days ago and no response 🙃

**Comment by kewde** [comment]
Blocked till AppVeyor (CI) supports Node 12  (required for Windows binaries :/)

**Comment by BridgeAR** [comment]
@kewde would it not be possible to already publish 4.0.7 with the current master branch (I did not check if there are new features or breaking changes, so I guess it's a patch release)? That way most people would already be able to use sqlite3, no matter if AppVeyor supports it or not. Or am I missing something?

**Comment by kewde** [comment]
Node 12 has been merged to master, will do release very soon.

**Comment by rzr** [comment]
may this also help for ARM64:
https://github.com/mapbox/node-sqlite3/pull/1147

**Comment by kewde** [comment]
v4.0.7 has been released.
