### ISSUE TITLE
Question on module size

### ISSUE THREAD

**Issue by aabuhijleh** [mapbox/node-sqlite3#1139]
I have one doubt regarding the size of this module. I'm using it in an electron application. After rebuilding and packaging the app I see a big increase in app size. Later I found out it's because of the size of **node_modules/sqlite3** which is **~35 MB** after packaging. Is this the normal size or am I doing something wrong here?

**Comment by kewde** [comment]
It may be that you need to trim your sqlite3 folder, more importantly, only keep the `.node` files for the version that you intend to use.
