### ISSUE TITLE
Symbol files of compiled node_sqlite3.node

### ISSUE THREAD

**Issue by theDevelopper** [mapbox/node-sqlite3#1159]
Hi, 
I am using node-sqlite3 in my nwjs project and my project crashed. When looking into the minidump file and analysing the stack traces I found sqlite3 to be in the midst of the problem. 
I am sure it is my fault as in  a command I use is bad, but I cannot find it, due to the fact that I do not have the symbols file for my build node_sqlite3.node file - or at least I cannot find it - to provide it to the minidump_stackwalk command.

Can you point me to the direction where I can find these in the build folder? Or how to generate these? I am using `node-pre-gyp install --build-from-source`... to generate the sqlite3 binary.

**Comment by kewde** [comment]
Hi,

You can build this project yourself, it used the traditional make file format.
I think `make debug` should do the trick.
