### ISSUE TITLE
Unhandled null parameters

### ISSUE THREAD

**Issue by jooadam** [mapbox/node-sqlite3#116]
``` javascript
var sqlite = require('sqlite3').verbose();
var db = new sqlite.Database('test.db');

db.all('SELECT * FROM test', null, function (error, rows) {
    if (error) {
        console.log(error);
    } else {
        rows.forEach(function (row) {
            console.log(row);
        });
    }
});

db.close();
```

The previous code will produce the following output:

```
{ [Error: SQLITE_RANGE: bind or column index out of range] errno: 25, code: 'SQLITE_RANGE' }
```

Changing the second argument of `Database#all()` from `null` to `[]` produces the desired output.

This handling of null values is both counterintuitive and undocumented. Other methods may be affected too.

**Comment by hems** [comment]
lol, i can't believe adding [] was the trick. jesus!

**Comment by hems** [comment]
i did a quick note at https://github.com/mapbox/node-sqlite3/wiki/API let me know what you think @springmeyer  !

peace!

:8ball:

**Comment by kkaefer** [comment]
looks good, @hems!

**Comment by khelkun** [comment]
Just to say this could have its place in the README too.

I wanted to use a callback on my `db.run("CREATE TABLE lorem (info TEXT)")` so I did:
```
db.run("CREATE TABLE lorem (info TEXT)", null, (err) => {
  if(err) return console.error("failed to create table", err);
  console.log("succeeded to create table");
});
```
This gives the following error output and actually fails to create the table:
```
Failed to create dummy table: [Error: SQLITE_RANGE: column index out of range] {
  errno: 25,
  code: 'SQLITE_RANGE'
}
```
It took me some time to understand the root cause of this error was the `null` second parameter of my `db.run` call. Obviously this does the job:
```
db.run("CREATE TABLE lorem (info TEXT)", [], (err) => {
  if(err) return console.error("failed to create table", err);
  console.log("succeeded to create table");
});
```
