### ISSUE TITLE
4.0.7 includes vscode files

### ISSUE THREAD

**Issue by bellostom** [mapbox/node-sqlite3#1162]
The size of the latest version is very big
https://registry.npmjs.org/sqlite3/-/sqlite3-4.0.7.tgz
Previous one is much smaller
https://registry.npmjs.org/sqlite3/-/sqlite3-4.0.6.tgz

It seems unnecessary are included

**Comment by kewde** [comment]
Oh god. Thanks.

**Comment by kewde** [comment]
I've pushed a fix but I'm forced to release this as 4.0.8!
I will be removing release 4.0.7 once it's done.

**Comment by kewde** [comment]
4.0.8 has been published which does not have the excess .vscode folder.
