### ISSUE TITLE
Building sqlite3 for Electron

### ISSUE THREAD

**Issue by wuno** [mapbox/node-sqlite3#1163]
I am trying to use sqlite3 with Electron on Windows but I keep getting an issue when node-gyp appears to be trying to download the correct binding from this URL, 

It appears the binding is decalred from [here](https://github.com/mapbox/node-sqlite3/blob/ac3666ddaab74331a065aafa5095eb338ed59a78/package.json#L10-L15). When I go to this URL in the browser I get this error,

> This XML file does not appear to have any style information associated with it. The document tree is shown below.

```
<Error>
<script/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E4FE959AF0BC9163</RequestId>
<HostId>
N+nkLjthr5dgKL5ZcGFzaxIQIe7gXIHEYpJOaeV5JzjMOo1CVKXmXnMmD7fBrANdmcYZv/j9VIM=
</HostId>
</Error>

When running the script locally this is the output.

```
> Error output:
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.2-win32-x64.tar.gz

When I check the node_modules/sqlite3 path i can see the folder is there but there is nothing inside the folder. 

I am assuming all I am lacking at this point is to get this binding added to my project correctly but I have not been able to find it nor get my npm to download it correctly. 

Is the URL to the binding incorrect? If so what is the correct URL that node-gyp should be using? Can I simply download the binding and add it to my project?

**Update**

I have tested building the sqlite3 module with Electron bindings on, 

Vanilla Electron boilerplate using **electron-rebuild**
Using **electron-builder**
Using **electron-forge**

All of these fail with the same issue, the binary does not exist. For some reason it seems that when `node-pre-gyp` tries to download the electron-node binding, it fails. 

If someone can provide some insight to what the correct binding is and the path to it I would be happy to try and help fix this.

**Comment by wuno** [comment]
I got it working with exactly by down grading sqlite3 and Electron till I got a version set that downloaded a accessible binding. 

This answer lead me to this solution, 

https://github.com/electron-userland/electron-builder/issues/3643#issuecomment-473150551

"sqlite3": "4.0.6",
"electron": "3.0.16"

I am really not understanding why `node-pre-gyp` can not access the binding for the latest versions. I would think that is something that a lot of people would like to have fixed.

At the very least if we could have some documentation to show us which versions of  `Electron` support which versions of `sqlite3 `so we can use the most recent versions possible if we really want latest.

**Comment by kewde** [comment]
There does not seem to be a release for electron v4.2 but there is for v4.0 (it should work on v4.2 as well). You should be able to manually use the files of v4.0 and rename them to match v4.2
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.8/electron-v4.0-win32-x64.tar.gz

General speaking electron hardly ever makes a release like 4.1 or 4.2 hence they were missed.

**Comment by wuno** [comment]
Thanks for your response @kewde 

Are these missing cause they do not exist or cause there is something blocking access to the end point they live at?

Is there any plan to get them added correctly or to provide documentation for which versions of Electron Sqlite3 is dependent on?

**Comment by kewde** [comment]
Bindings for 5.0.0 are available in release 4.0.8

**Comment by linonetwo** [comment]
Seems prebuild for electron 5.0.0 not work for electron 5.0.1?

**Comment by wuno** [comment]
They did not work for us... We could not get 5.0.0 to work for us either. 

@linonetwo did 5.0.0 work for you?

**Comment by linonetwo** [comment]
No, I get `node-pre-gyp install --fallback-to-build   spawn ENOENT`

**Comment by wuno** [comment]
Exactly, 

The newest version we can get working is, 

"sqlite3": "^4.0.8",
"electron": "4.0.0",

Using those 2 versions will build with the bindings from node-pre-gyp. 
We have not been able to compile with Electron 5. 

The issues we are having now are getting encryption working with sqlite3 and sqlcipher.

**Comment by linonetwo** [comment]
@kewde  But you said 

> Bindings for 5.0.0 are available in release 4.0.8

Why will `node-pre-gyp install --fallback-to-build spawn ENOENT` happened?

I install package using:

```js
const npm = require('npm')
      npm.load({}, (npmErr) => {
        if (npmErr) return reject(npmErr)
        npm.commands.install(packagePath, packages, (err) => {
          if (err) return reject(err)
          installStatus.set(name, 'installed').then(resolve)
        })
      })
```

**Comment by kewde** [comment]
The automated test suite ran within electron v5 and completed fine for the builds.
We're testing electron v5 in our internal application, this should give me a second confirmation.

Please note that electron v5 comes with a lot of changes, including a change in the sandboxing mechanisms. Which means that out of the box, you won't be able to use this module in the renderer processes. You'll have to run it non-sandboxed.

**Comment by natearmagost** [comment]
Electron 5+ seems to work now.

```
"sqlite3": "^4.0.9",
"electron": "^5.0.6",
"electron-rebuild": "^1.8.5",
```

**Comment by kewde** [comment]
3b30762c022bb7a325238be537be3683a6a0f5ea
