### ISSUE TITLE
version `GLIBCXX_3.4.21' not found - sqlite3 4.0.8

### ISSUE THREAD

**Issue by sangaman** [mapbox/node-sqlite3#1164]
When building in Travis CI with Node.js 12 and sqlite3 4.0.8, tests fail with:

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/travis/build/ExchangeUnion/xud/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node)
```

This issue does not arise with the same configuration running Node.js 10.

**Comment by realies** [comment]
Similar issue because of the GLIBCXX_3.4.21 dependency. Sqlite3 segfaults on CentOS 7.

```
# ldd node_sqlite3.node 
./node_sqlite3.node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./node_sqlite3.node)
	linux-vdso.so.1 =>  (0x00007ffdcbb4d000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb10e346000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb10e044000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb10de2e000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb10dc12000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb10d845000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb10ea23000)
```

**Comment by kewde** [comment]
Thank you for reporting the issue.

Travis-CI for Node 12 has been using `xenial` which ships with a much higher version of libc++.
We could look into downgrading back to `precise` (or even lower `trusty`) instead.

**Comment by kewde** [comment]
I don't recall there being a specific reason for the upgrade to Xenial.
This additional distro upgrade got in when I splitted a pull request from another user, I had removed the upgrade from the electron builds but not for the normal builds.

**Comment by realies** [comment]
An upgraded CentOS EL7 comes with up to GLIBCXX_3.4.19

```
# strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
```

**Comment by kewde** [comment]
Building v4.0.9

**Comment by kewde** [comment]
Please test out v4.0.9 it should have resolved this issue. 
Thanks you.

**Comment by sangaman** [comment]
Confirmed that 4.0.9 works without this issue, thanks!
