### ISSUE TITLE
`serialize` method of `new sqlite3.Database()` not documented

### ISSUE THREAD

**Issue by zenflow** [mapbox/node-sqlite3#1172]
The usage example in the readme wraps all db interactions in `db.serialize(function({`, but there is no reference to this `serialize` method in [the documentation on sqllite3.Database](https://github.com/mapbox/node-sqlite3/wiki/API). 

What is it for? What does it do?

**Comment by Zenaido** [comment]
Serialize is used for control flow. Its use case is explained [here](https://github.com/mapbox/node-sqlite3/wiki/Control-Flow).
