### ISSUE TITLE
stream is undefined

### ISSUE THREAD

**Issue by cyclecycle** [mapbox/node-sqlite3#1176]
Using in a Vue app (that will run locally, so I am using sqlite for data persistence). On importing, I get a error message in the console:

TypeError: stream is undefined

With what doesn't seem like much information as to where to go next with this.

Outside of the browser environment, it works just fine. Would appreciate any thoughts.

**Comment by kewde** [comment]
It's not ment to be ran inside a browser. The electron support is only aimed at non-render processes, or render processes with nodejs integration enabled.
