### ISSUE TITLE
4.0.9 released on npm, no tag in repo

### ISSUE THREAD

**Issue by JayAndCatchFire** [mapbox/node-sqlite3#1178]
According to NPM, version 4.0.9 was published 4 days ago.  However, there is no release tag or mention of a version 4.0.9 here in this repo.  I was curious to know what changed between 4.0.8 and 4.0.9.  Also, I wanted to make sure there was nothing malicious about 4.0.9 now that I see no mention of it here.

**Comment by kewde** [comment]
No code has changed except the travis config file now using an older version of ubuntu to compile bins that require a lower version of libc.

**Comment by kewde** [comment]
Tag has been added to the corresponding commit!
