### ISSUE TITLE
How to connect sqlite with Angular 7 ionic 4

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [mapbox/node-sqlite3#1187]
I have been trying to do desktop application for windows and mac using ionic 4 Angular 7 with electron-js, Once i created .exe ionic sqlite was not working with it and i also used sqilte3 which gave error at the time of implementing itselft. "cant able to use require("sqilte3")".

As of i searched, they were no other 3rd party library for my requirement in NPM. 
Help me out with some sample app for connecting Angular 7 with sqlite3.

**Comment by kewde** [comment]
This is likely an electron issue. You can not require() sqlite3 in the renderer process.
Once you make a BrowserWindow then any code inside the "browser" can not use SQLite3.
