### ISSUE TITLE
Close open db on process exit

### ISSUE THREAD

**Issue by wmertens** [mapbox/node-sqlite3#1188]
The node `'exit'` event is called just before the application quits, and handlers can run synchronous code but anything async will never run.

Since there's no `closeSync`, would it be possible to attach to the event by default and close any open handles synchronously?

**Comment by ghaecker** [comment]
I don't know the answer to your question on attaching to node's exit event.  Perhaps, your needs could be met by closing the database earlier - for example on arrival of a termination signal on the process.  

```js
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('Closing database...');
  db.close();
  // other shutdown requirements
  // ...    
}
```

**Comment by wmertens** [comment]
@ghaecker 	the problem is that db.close is an async function, the actual work is done in the next tick, which will not run. Either `close` needs to become synchronous or `closeSync` needs to be implemented.

I already tried to implement synchronous calls but it segfaults somewhere :( https://github.com/Yaska/node-sqlite3/tree/sync

**Comment by alin1771** [comment]
do we have a resolution on this?
closeSync will be nice to have

**Comment by tkurki** [comment]
Would beforeExit work for you? Combined with a handler for uncaught Exceptions?

https://nodejs.org/api/process.html#process_event_beforeexit

**Comment by wmertens** [comment]
@tkurki well, that only fires when the event queue is empty and Node would quit, and in my case that never happens, it's always due to systemd stop or restart.

**Comment by tkurki** [comment]
@wmertens systemd stop&restart mechanism uses SIGTERM by default and is [configurable]. As already pointed out you can catch SIGTERM with `process.on('SIGTERM',....)`, run the async cleanup code there and when done issue `process.exit(0)`. 

Handling SIGTERM will keep the process running, so you can do whatever you want, sync or async.

**Comment by wmertens** [comment]
Hmm good point - I'm writing a library so I can't really usurp the handler, but OTOH I can just wrap the original handler after closing the db.

I'll close
