### ISSUE TITLE
Using sqlite3 + sequelize on electron

### ISSUE THREAD

**Issue by GoogleFeud** [mapbox/node-sqlite3#1191]
I'm trying to use sqlite3 along with sequelize with electron. This is what I do:

`
npm i sqlite3 --build-from-source --runtime=electron --target=1.7.6 --dist-url=https://atom.io/download/electron`

`.\node_modules\.bin\electron-rebuild.cmd`

But when I try to run the main script which creates an instance of BroswerWindow (`electron index.js`) I get the error "Please try to install sqlite3 manually".

**Versions:**
`
 "sequelize": "^5.10.1",    
   "sqlite3": "^4.0.9"     
  "electron": "^5.0.7",            
   "electron-rebuild": "^1.8.5"          
`

**Comment by kewde** [comment]
Why are you building for an electron version with the target of 1.7.6 while your version specifies 5.0.7 or up?
