### ISSUE TITLE
Repeatedly asking to install sqlite3@4.0.8

### ISSUE THREAD

**Issue by ed-yee** [mapbox/node-sqlite3#1193]
MacOS v10.14.6
VS Code v1.36.1
Node 10.16

VS Code asked me to install Sqlite3. So I did.

![image](https://user-images.githubusercontent.com/24571355/61844524-4d9cd600-aed2-11e9-8b71-cba9ace66ea3.png)

![image](https://user-images.githubusercontent.com/24571355/61844582-8177fb80-aed2-11e9-984b-a571beb0c7ff.png)

The "Connect to ..." button will show the first dialog box again.

I even installed sqlite3 (`npm i sqlite3 -g`) from the Terminal. Rebooted the machine. VS Code is still asking to install the module.

**Comment by leonelurra87** [comment]
Hi @ed-yee 

Node.js 6 or newer
Enable sqltools.useNodeRuntime setting, can be true or a path to the node runtime.
```
// settings.json example
{
    "sqltools.useNodeRuntime": true
}
```

https://vscode-sqltools.mteixeira.dev/connections/sqlite

**Comment by ed-yee** [comment]
That works! Thank you
