### ISSUE TITLE
'SequelizeDatabaseError'

### ISSUE THREAD

**Issue by Subodh18** [mapbox/node-sqlite3#1198]
message: 'SQLITE_READONLY: attempt to write a readonly database',
  parent: 
   { [Error: SQLITE_READONLY: attempt to write a readonly database]
     errno: 8,
     code: 'SQLITE_READONLY',
     sql: 'INSERT INTO `tbl_transaction` ' },
  original: 
   { [Error: SQLITE_READONLY: attempt to write a readonly database]

Sometimes when i am starting the application .i am facing this issue.although i check in connectionManager.js 
options.readWriteMode || (self.lib.OPEN_READWRITE | self.lib.OPEN_CREATE 
as default mode .

how can i solve this problem .any help will be appreciated.
Thanking you.

**Comment by Subodh18** [comment]
i am using  "sqlite3": "^3.1.1",

**Comment by kewde** [comment]
Seems like a problem in your application, perhaps there are two instances accessing the database and only the second instance can get write permission. SQLite only allows a single writer at a time.

**Comment by kewde** [comment]
Also update to the latest version of SQLite please. ^4.0.6
