### ISSUE TITLE
Cannot find module electron-v5.0-darwin-x64/node_sqlite3.node

### ISSUE THREAD

**Issue by elixiao** [mapbox/node-sqlite3#1203]
Cannot find sqlite after install. The errors are:

```sh
Cannot find module 'node_modules/sqlite3/lib/binding/electron-v5.0-darwin-x64/node_sqlite3.node'
Require stack:
node_modules/sqlite3/lib/sqlite3.js
node_modules/knex/lib/dialects/sqlite3/index.js
```

Actually the folder name is `node-v64-darwin-x64` so I rename folder to `electron-v5.0-darwin-x64` but get the following error:

```sh
The module 'node_modules/sqlite3/lib/binding/electron-v5.0-darwin-x64/node_sqlite3.node
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installingthe module (for instance, using `npm rebuild` or `npm install`).
```

How can I use sqlite3 with electron on my computer? (macOS Mojava 10.14.6, node version v10.16.0)

**Comment by fmacedoo** [comment]
@elixiao i bielieve you must rebuild the sqlite3 dependency before run that application.
try `npm install electron-rebuild --save && electron-rebuild -f -w sqlite3`

**Comment by fmacedoo** [comment]
Sorry, i am having the same issue but on Windows environment. I let you know if i get news.

**Comment by fmacedoo** [comment]
@elifitch seems like you must build the sqlite3 manually (few steps). And after rename the folder.

I've found [this](https://gist.github.com/craigvantonder/f59277cd788f8aa755e3bdbe5d21f08e) and tried. It definitely solved my issue on windows environment. (as on darwin i din't get it)

The solution is generic, maybe could help you.

**Comment by ridesky** [comment]
same issue

electron : 5.0.6
node: 10.15.1
macOS : 10.14.6

**Comment by zlab** [comment]
same issue

electron : 6.0.2
node: 12.8.0
macOS : 10.13.6
sqlite3: 4.1.0

**Comment by mapsam** [comment]
cc @kewde

**Comment by kewde** [comment]
Hi,

It seems like when you installed it, npm didn't realize it was an electron project?
Executing `electron-rebuild` should get the electron binaries.

https://github.com/electron/electron-rebuild

**Comment by kewde** [comment]
Unless this issue persists, I am closing it.
When you upgrade your node or electron version, then please also reinstall this module because it needs to be recompiled to match the appropriate Node ABI version.

Feel free to re-open this if you keep on having this issue.
