### ISSUE TITLE
ACID compliant in nodejs cluster

### ISSUE THREAD

**Issue by srmarjani** [mapbox/node-sqlite3#1209]
Hi
I want to use sqlite3 in a node project.
But I have a problem. In my project I use cluster module of nodejs that fork 4 worker as my PC has 4 core. In every worker I run same java-script code that need database connection and every worker can write and read to database.
In this scenario If node-sqlite3 guarantees ACID or not?
thanks

**Comment by kewde** [comment]
SQLite3 only allows a single writer, so it can not be multithreaded.
