### ISSUE TITLE
Installation failed under enterprise npm offline repository

### ISSUE THREAD

**Issue by AlexPortland** [mapbox/node-sqlite3#1212]
During the installation process (w/ npm install sqlite3 --save) an error message emerge about node-pre-gyp trying to get some binary(?) from "map-box-node-binary.s3.amazonaws.com:443" and fails because i'm not connected to the internet.

Is there any way to fix this so I can update through npm and not copy manually?
If not is it possible to make the module offline-compatible?

**Comment by kewde** [comment]
Hi @AlexPortland 

Please take a look at.
https://github.com/DenisCarriere/sqlite3-offline

If you prefer to build the native dependencies yourself then please run the following command:
```
npm install sqlite3 --save --build-from-source
```
This however will require that the build tools for the respective operating system are available.

Thanks.
