### ISSUE TITLE
Commit `b8907e79fc3fb52803b5a05c106948911dcd77ac` cannot be checked out

### ISSUE THREAD

**Issue by dorfire** [mapbox/node-sqlite3#1213]
It's available on GitHub:
https://github.com/mapbox/node-sqlite3/commit/b8907e79fc3fb52803b5a05c106948911dcd77ac

However, trying a local checkout fails:
```
$ git checkout b8907e79fc3fb52803b5a05c106948911dcd77ac
fatal: reference is not a tree: b8907e79fc3fb52803b5a05c106948911dcd77ac
```

Any ideas?

**Comment by Ranguna** [comment]
If you notice, that's a merge commit and one of the parents 200c2a62c56124c2f49959026c9945bbd36c9dda also does not exist.
I'm guessing there was a history rewrite and github is keeping a cache.

Is this necessary or do you think we can close this issue ?

**Comment by dorfire** [comment]
I guess it can be closed.
