### ISSUE TITLE
Build Error when installing with NPM

### ISSUE THREAD

**Issue by ajnauleau** [mapbox/node-sqlite3#1214]
Currently getting a build error when trying to install node-sqlite3 using `node install sqlite3 --save-dev`.

There are a bunch of errors showing build scripts failing, and then at the end:

`errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.`

Running macOS Mojave v.10.14 and Node v12.8.1

**Comment by chrissyalbert** [comment]
I got the exact same error message. Not sure what to do.

**Comment by cherylcarpenter** [comment]
same issues, on Windows - tried --build-from-source and no luck

**Comment by chrissyalbert** [comment]
I updated Node. Apparently I had an older version of it. After reinstalled Node and restarted my computer, it worked.

**Comment by kewde** [comment]
Hi,

Please upgrade your version to v4.
