### ISSUE TITLE
S3 url down - v4.0.3

### ISSUE THREAD

**Issue by ruffrey** [mapbox/node-sqlite3#1219]
While npm installing, https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.3/node-v72-linux-x64.tar.gz seems to be gone, which breaks the installation. Does anyone know if the file has been deleted? Or did the bucket permissions change?

**Comment by floriandotorg** [comment]
same problem, ideas?

**Comment by ruffrey** [comment]
I doubt they'll fix this. My colleague just updated to a newer version and it works again.
