### ISSUE TITLE
Error 403 with node-pre-gyp

### ISSUE THREAD

**Issue by Silbad** [mapbox/node-sqlite3#1234]
**electron : 6.0.8
sqlite3 : 4.1.0
node : 10.17.0
yarn : 1.19.1**

`⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.19.1
    $ node-pre-gyp install --fallback-to-build
    Failed to execute 'C:\Program Files\nodejs\node.exe E:\xxxxxmy_private_pathxxxxxx\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\xxxxxmy_private_pathxxxxxx\node_modules\sqlite3\lib\binding\electron-v6.1-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\xxxxxmy_private_pathxxxxxx\node_modules\sqlite3\lib\binding\electron-v6.1-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --msvs_version=2015' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.11.0
    node-pre-gyp info using node@10.17.0 | win32 | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/electron-v6.1-win32-x64.tar.gz
    node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/electron-v6.1-win32-x64.tar.gz
    node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/electron-v6.1-win32-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and electron@6.1.2 (electron-v6.1 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/electron-v6.1-win32-x64.tar.gz`
(I'll spare you the other error messages ^^)

Hello,
I have this recurring problem when installing sqlite3, I tried (too) many things...
I saw that I wasn't the only one with this problem.
What is the cleanest solution to solve this problem permanently?
Thanks

**Comment by kewde** [comment]
Hi,

You are not using electron 6.0.8 as you think but instead you are using 6.1!
I've added a PR #1237 which has prebuilts for that version and the new electron 7.

I will keep this issue open until it has been merged and released.

**Comment by mirismaili** [comment]
Using **sqlite v4.1.1** solved my issue!

**Comment by juniorbotelho** [comment]
Install python with ```apt install python``` and after install sqlite3 solved my issue!
