### ISSUE TITLE
Install shows a banner advertisement

### ISSUE THREAD

**Issue by CMarker** [mapbox/node-sqlite3#1235]
```
npm install sqlite3 --save
....
D:\redacted>? Want to strengthen your core JavaScript skills and master ES6?
D:\redacted>I would personally recommend this awesome ES6 course by Wes Bos.
D:\redacted>How to Install
```
Not sure where it's coming from

Edit: I have not been able to reproduce after deleting node_modules and trying to get the message to appear again. Must be an unrelated local issue.

**Comment by kewde** [comment]
Unrelated local issue it seems.
