### ISSUE TITLE
How to insert into a table with multiple values in a parametrized query

### ISSUE THREAD

**Issue by superainovacoes** [mapbox/node-sqlite3#1239]
I'd like to know how to parametrize a query of an insert into clause with multiple values, like so:

Insert into Table (columnA, columnB) values (1,2), (3,4), (5,6)

Is it possible to pass an array of array in the .all(query, params) like this [[1,2],[3,4]]?

Is there any other way of doing?
Thanks

**Comment by kewde** [comment]
Yes, take a look at the code here.
https://github.com/sqlcipher/sqlcipher/blob/master/README.md
