### ISSUE TITLE
Download(404)

### ISSUE THREAD

**Issue by Premis2** [mapbox/node-sqlite3#1241]
Using Unbuntu. Receiving this error. I'm up to date on node and sqlite3. Major error seems to be when downloading mapbox-node-binary. Anything I can run in cmd to fix??

~/gekko$ npm install --only=production

> sqlite3@4.0.4 install /home/premis/gekko/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.4/node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.0.4 and node@12.13.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.4 and node@12.13.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Connection closed while downloading tarball file

**Comment by kewde** [comment]
Hi,

Please update to v4.1.0
That will fix the issue.

**Comment by atelic** [comment]
Node v4.1.0 [was released in 2015](https://nodejs.org/dist/v4.1.0/) - it is not an upgrade. v12.13.0 is the current LTS (Erbium) with end of life being 2022-04-30, `sqlite3` should be able to support that version.
