### ISSUE TITLE
Add support for Node 13 (node-v79-linux-x64)

### ISSUE THREAD

**Issue by thierry2015** [mapbox/node-sqlite3#1246]
As a developer, I want to be able to support latest Node.js version (13.x) in order to use the latest engine features and to make sure all internal CLI users will be able to use my applications.

I work on internal business projects that are being used by developers, mostly through local CLI and distant Web interfaces. Some of them are on Node 12, some upgraded on 13 (we kept our servers on Node 12). Currently, the CI fails tests when on Node 13, not able to find the proper binding, which is supposed to be `node-v79-linux-x64`. However, the binding I get when on Bitbucket pipeline image `node:latest` is `node-v72-linux-x64`. All my CI tests are failing on the latest Node.js version because of this, but are successful on Node 12, on which binding resolves to `node-v72-linux-x64`. I use your package through `knex`.

Would it be something that you can fix in the next few weeks?

**Comment by kewde** [comment]
#1247

**Comment by kewde** [comment]
Please wait for #1248, we need to release a new version if you want to use prebuilt v13.
You will have to re-install sqlite3.

**Comment by BackPacker777** [comment]
I'd like to +1 this!

**Comment by kewde** [comment]
Please re-install sqlite3 to v4.1.1, they have been added, thanks.

**Comment by thierry2015** [comment]
Just tested it with bitbucket pipelines, it works as expected, thank you for the follow-up!

**Comment by BackPacker777** [comment]
Works for me too!
