### ISSUE TITLE
Getting issue while installing Angular

### ISSUE THREAD

**Issue by BijoyKarmakar** [mapbox/node-sqlite3#1260]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/angular/cli.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\40900326\AppData\Roaming\npm-cache\_logs\2019-12-04T10_13_20_310Z-debug.log

debug.log
=======

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular/cli'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session daa3331da496e40e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:angular/cli Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/angular/cli.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 451ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
10 verbose stack     at onErrorNT (internal/child_process.js:456:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
11 verbose cwd C:\Program Files
12 verbose Windows_NT 10.0.16299
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular/cli"
14 verbose node v12.13.1
15 verbose npm  v6.12.1
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t ssh://git@github.com/angular/cli.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]

**Comment by kewde** [comment]
This library is only for issues relating to node-sqlite3.

**Comment by adithyasbhat** [comment]
hey @BijoyKarmakar even i got the Same kind of error while Installing the node_modules.
did u find the solution?
