### ISSUE TITLE
Add support for Node 13

### ISSUE THREAD

**Issue by Pomax** [mapbox/node-sqlite3#1261]
It looks like Sqlite3 is not compatible with Node 13 yet, only Node 12. Can binaries be generated for the new (well... October, but still) major version of Node?

**Comment by Pomax** [comment]
@kewde any news on this front? Node 13's been out long enough to have had five minor version updates already, and sqlite3 is a common enough library that compatibility with new versions of Node is pretty essential. Especially since it's typically used as the "local dev" equivalent of a full blown database, with local dev generally using the most recent version of Node, rather than the LTS version.

**Comment by vanishedvan** [comment]
Yeah, @kewde any news? It has been over a month since Node 13 release.

**Comment by bedwardly-down** [comment]
What exactly is the incompatibility here? I'm on Artix Linux running nodejs 13.7.0 with no issues so far. Of course, I'm not directly messing with Sqlite3 but one of the apps I'm contributing too and using uses it pretty heavily for its backend. Thanks

**Comment by dhkatz** [comment]
The issue is, at least on Windows that node-gyp tries to request a pre-built binary for Node 13 (node-v79 ABI) but there isn't any. It then tries to fall back to building from source, but I doubt most people have a VS 2015 compiler still running.

**Comment by bedwardly-down** [comment]
Thanks for getting back to me. So it seems to be a Windows only issue that Linux bypasses for the most part, right?

**Comment by Pomax** [comment]
Any system that knows how to build C++ code using Pythong via node-gyp for node.js will compile from source, but sqlite3's power is that it _doesn't need_ a build system because all the binaries are prepackaged. It was one of the first projects to add that and it was a god send. Sure, nearly every windows user is affected, but _also_ every lean unix/linux deploy system that only installs exactly what's necessary, and not all headers and libraries necessary to compile things from source.

**Comment by kewde** [comment]
Support for Node 13 was added in 4.1.1.
I will verify that the windows prebuilt binaries are available.

**Comment by kewde** [comment]
Seems alright?

https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v79-win32-x64.tar.gz
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v79-win32-ia32.tar.gz

Make sure to be on 4.1.1 and re-install node-sqlite3 with node set to v13.
