### ISSUE TITLE
Make sqlite3 context aware for Electron 7+ compatibility

### ISSUE THREAD

**Issue by MrMitch** [mapbox/node-sqlite3#1274]
We use sqlite3 in an Electron application and Electron is soon requiring Native Modules in the Renderer Process to be NAPI or Context Aware.

Is it possible to make sqlite3 Context Aware?
See electron/electron#18397 and an example https://github.com/atom/node-keytar/pull/182/files

Thanks

**Comment by kewde** [comment]
We need to investigate #1007 again to make node-sqlite3 compatible with worker threads.
Then we can look at enabling support.

**Comment by ChrisHSandN** [comment]
There is also an open issue to add: N-API Support #830 which I guess would also solve this too - however that has been worked on for over 2 years now.

If Electron maintains their 12 week release schedule, version 11 (which will drop support for non converted modules) could be released around November 2020.

**Comment by bedwardly-down** [comment]
With the shortage of contributors here, can I safely assume that Electron 8 will not be fully supported for a good while still? Or if there's a pretty good chance it will be coming pretty soon, could I get a rough time frame for that?

**Comment by kewde** [comment]
#1304
Not yet released but will be available in 5.0.0

**Comment by MrMitch** [comment]
@kewde thank you very much for your follow-up, much appreciated !

**Comment by aabuhijleh** [comment]
Glad this change is made

@kewde,when do you think 5.0.0 will be published to npm?

**Comment by MrMitch** [comment]
@aabuhijleh v5 has been released (https://github.com/mapbox/node-sqlite3/releases/tag/v5.0.0) and is available on npm (https://www.npmjs.com/package/sqlite3)

**Comment by MrMitch** [comment]
thank you @kewde ! :tada:
