### ISSUE TITLE
Uncaught TypeError: Cannot read property '_handle' of undefined  

### ISSUE THREAD

**Issue by vahost** [mapbox/node-sqlite3#1280]
I've been trying to install your plugin in Windows 10 without success within a Quasar/Vue setup.

After playing around with it a bit, I've commented everything out except the first line:

`var sqlite3 = require('sqlite3').verbose();`

In Inspect I'm getting the following error:

Uncaught TypeError: Cannot read property '_handle' of undefined
    at eval (index.js?2f37:3)
    at Array.forEach (<anonymous>)
    at module.exports (index.js?2f37:2)
    at Object.eval (log.js?8c68:11)
    at eval (log.js:311)
    at Object../node_modules/npmlog/log.js (vendor.js:11168)
    at __webpack_require__ (app.js:791)
    at fn (app.js:151)
    at Object.eval (node-pre-gyp.js?ace6:16)
    at eval (node-pre-gyp.js:205)

Additionally, I'm getting a warning when I start up my dev server:

 warning  in ./node_modules/sqlite3/lib/sqlite3.js

Critical dependency: the request of a dependency is an expression

I'm also getting warnings about node-pre-gyp after that, but I'm pretty sure they all stem from the above warning. I do have node-pre-gyp installed with the latest version.

**Comment by kewde** [comment]
It's likely just a webpack problem, we have an issue for this.
https://github.com/mapbox/node-sqlite3/pull/1268

**Comment by doamatto** [comment]
@kewde Since #1268 was merged, this could be closed, no?

**Comment by cattox** [comment]
@doamatto or @vahost I just stepped on this same issue. Can you state exactly what I have to do to solve it? Exclude some dependency on webpack? I'm currently not using it.. do I need to?

**Comment by doamatto** [comment]
> @doamatto or @vahost I just stepped on this same issue. Can you state exactly what I have to do to solve it? Exclude some dependency on webpack? I'm currently not using it.. do I need to? 

You shoyld really make a new issue, but make sure you're using the latest version

**Comment by cattox** [comment]
Thank you for the reply. I didn't want to add noise to the project. I believe I just need some information on a already solved issue (but I can create a new issue if you prefer).  I'm using 5.0.0. This is the latest version isn't it?

**Comment by Beknazar2003** [comment]
> Thank you for the reply. I didn't want to add noise to the project. I believe I just need some information on a already solved issue (but I can create a new issue if you prefer). I'm using 5.0.0. This is the latest version isn't it?

Hello, have you solved this problem? If so, how? I read all the comments above, but I still don't understand how to solve this problem

**Comment by cattox** [comment]
> > Thank you for the reply. I didn't want to add noise to the project. I believe I just need some information on a already solved issue (but I can create a new issue if you prefer). I'm using 5.0.0. This is the latest version isn't it?
> 
> Hello @cattox, have you solved this problem? If so, how? I read all the comments above, but I still don't understand how to solve this problem

Hi Beknazar2003. I was using Node 15 which is not supported by sqlite. Moved to Node 14, and it seems that it solved the problem, but I didn't have the time to check it properly.
