### ISSUE TITLE
how to let node-sqlite3 use my os sqlite3?

### ISSUE THREAD

**Issue by anlexN** [mapbox/node-sqlite3#1284]
my os sqlite:
![image](https://user-images.githubusercontent.com/8686739/75109918-a1d38880-5662-11ea-93b9-c6a7b88d1325.png)
my os sqlite location:
![image](https://user-images.githubusercontent.com/8686739/75109932-cf203680-5662-11ea-97a1-8d6b7a91b739.png)

npm install sqlite3 --build-from-source --sqlite=/usr/local/bin

![image](https://user-images.githubusercontent.com/8686739/75110112-d0eaf980-5664-11ea-9cdd-b3ea1d8f8a84.png)

why node-sqlite3 not to use my os SQLite version 3.31.1? what's wrong?

**Comment by kewde** [comment]
Hi @anlexN 

If building against an external sqlite3 make sure to have the development headers available. Mac OS X ships with these by default. If you don't have them installed, install the -dev package with your package manager, e.g. apt-get install libsqlite3-dev for Debian/Ubuntu. Make sure that you have at least libsqlite3 >= 3.6.

What you have done is attempted linking to the sqlite3 BINARY. I think you might have to point it to the location of the headers, no? Try changing the "--sqlite=" to the directory of development headers.

Good luck!

**Comment by anlexN** [comment]
1. which should i install, libsqlite3-0 or sqlite3-devel?
2. where is my development headers location?

my system: opensuse
![image](https://user-images.githubusercontent.com/8686739/75310339-aed4bf80-588e-11ea-8260-3d35860beaa9.png)

**Comment by anlexN** [comment]
@kewde After below step, maybe i successfully install node-sqlite3
```bash
$ zypper install make gcc-c++ sqlite3 sqlite3-devel
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
$ nvm install --lts
$ npm install sqlite3 --build-from-source --sqlite=/usr/lib64
```
but theere are too many warnings!!! why??? below is some example:
![image](https://user-images.githubusercontent.com/8686739/75325443-cd00e680-58b3-11ea-80a9-edbadb637a22.png)
![image](https://user-images.githubusercontent.com/8686739/75325604-0fc2be80-58b4-11ea-82b7-e61c489d7101.png)

![image](https://user-images.githubusercontent.com/8686739/75325530-f588e080-58b3-11ea-9f37-33d8787b949c.png)

**Comment by kewde** [comment]
Warnings shouldn't affect the build, seems like it went through.
Good luck!

**Comment by anlexN** [comment]
@kewde now node-sqlite3 use sqlite3 old version: 3300100, why not use latest version:3310100?

**Comment by kewde** [comment]
@alexN SUBMIT ME THE CODE AND I WILL MERGE IT FOR YOU. THANK YOU VERY MUCH.

**Comment by alexander-nesterenko-kas** [comment]
@kewde You did use the wrong name for the message. Use @anlexN instead of @Alexn.

**Comment by anlexN** [comment]
@kewde , i have created pull request, by the way,  how to upload latest tar.gz in github.com website node-sqlite3 itself whether can invoke latest sqlite3 api? and continuous-integration use some nodejs that are less than version 8, can we give up those old nodejs version?

**Comment by SamuelBrucksch** [comment]
@kewde we are waiting for a release with 3.31.1 as 3.30.x seems to have some vulnerabilities. Can you please give an estimate, when a new release will be done?
