### ISSUE TITLE
how to build from sqlite3 official website source code?

### ISSUE THREAD

**Issue by anlexN** [mapbox/node-sqlite3#1286]
I know node-sqlite3 need sqlite3.h. i download sqlite-autoconf-3310100.tar.gz from sqlite official website.
![image](https://user-images.githubusercontent.com/8686739/75503675-4530ee80-5a11-11ea-8c13-a54c08ff5138.png)
I unpack this tar.gz, there is sqlite3.h. but build is failed. npm can not find this sqlite3.h
![image](https://user-images.githubusercontent.com/8686739/75504440-701c4200-5a13-11ea-9cdd-b6b0e16e76d5.png)

**Comment by kewde** [comment]
Look at this commit, that's how I do them:
https://github.com/mapbox/node-sqlite3/commit/b2a7d6154e3fee6db2ec2a83869c24a290911b59

**Comment by anlexN** [comment]
@kewde , now node-sqlite3 use sqlite3 version: 3300100, but sqlite3 official website latest version: 3310100. if i use this latest version, can i install node-sqlite3 to use in my project?  and node-sqlite3 itself can invoke latest version's api and function?

**Comment by anlexN** [comment]
@kewde , now node-sqlite3 use sqlite3 version: 3300100, but sqlite3 official website latest version: 3310100. if i use this latest version, can i install node-sqlite3 to use in my project?  and node-sqlite3 itself can invoke latest version's api and function?
