### ISSUE TITLE
Electron 8 prebuilt

### ISSUE THREAD

**Issue by NilSet** [mapbox/node-sqlite3#1293]
Electron 8 has been released, prebuilt binaries for it should be published.

**Comment by NilSet** [comment]
On a side note, Electron 5 and below is no longer supported by the dev team, perhaps stop publishing new builds for unsupported electron versions?

**Comment by Kupstas** [comment]
Still have a problem
`node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/electron-v8.0-darwin-x64.tar.gz
`

**Comment by JqiangLiu** [comment]
the same problem
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/electron-v8.3-win32-x64.tar.gz
