### ISSUE TITLE
Cannot compile from source for node 10

### ISSUE THREAD

**Issue by Roaders** [mapbox/node-sqlite3#1295]
Hi All

I am trying to get sqlite3 to compile and run with node 10.15.1 on linux.

I am installing as follows:
`npm install -D --build-from-source sqlite3@4.1.1`

and when I try to run I get an error message:

```
The module 'node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
was compiled against a different node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance using 'npm rebuild' or 'npm install').
```

I have tried reinstalling, recompiling and build from source but it still seems to use the incorrect node module version.

How can I get it to compile for Node 10 (as Node 8 is no longer supported at my location).

I am in a locked down environment where binary downloads are not allowed so compilation is required.

**Comment by kewde** [comment]
Here's what you should do:
* Delete the folders in `binding/`, make sure it's clean.
* Verify what version of node your npm is using to build against
* Verify the version of node that your application is using

Your builds are being created for one version of node, the application you're running is using a higher version of node.
This is an environment issue on your computer and there's nothing that we can really do here for you.
I'm tempted to close the issue, but I'll keep it open for a little while, perhaps an observant is willing to help you figure it out.

**Comment by Roaders** [comment]
Thanks. The issue was the `nodedir` being used by npm config.

I ran `npm config set nodedir /path/to/node/10` and rebuilt and the issue was resolved.
