### ISSUE TITLE
In China, the download address is blocked and the agent is not available

### ISSUE THREAD

**Issue by mapleby** [mapbox/node-sqlite3#1310]
Today, I want to give up. From yesterday to now, I have used many agents and changed many methods. I can't solve the problem that S3 is blocked by Chinese network. I'm going to crash. I recommend using a local build approach to avoid network problems, which I currently build on electron.

**Comment by kewde** [comment]
VPN?

**Comment by mapleby** [comment]
No ,I use socket5,similar to VPN.

**Comment by kewde** [comment]
SOCKS5 proxies do not provide any encryption and therefore the Great Firewall can easily intercept and block your request.

Suggestions:
* Tor (SOCKS5 proxy @ 127.0.0.1:9050 which will tunnel it into an encrypted session)
* Any VPN that you can use in China

**Comment by mapleby** [comment]
The Socks5 proxy is encrypted, and the administrators of the unencrypted proxy server have gone to the police station for vacation.
In China  dare not use VPN,  will be invited by the internet police to have tea...

I can download the build file directly from the browser through the socket5 agent, but I still need to download it when packaging.

So I would like to know if there is any way to prevent this download. Direct use download completed files from browser.

**Comment by kewde** [comment]
https://github.com/DenisCarriere/sqlite3-offline

They are not the latest versions sadly, but if you still need this, I can do a pull request updating that repository in a few day.

Then in your `package.json`
```
    "sqlite3": "https://github.com/DenisCarriere/sqlite3-offline.git",
```
