### ISSUE TITLE
Installing 4.1.1 and 4.2.0 on Node.js 14.0 generates a zillion warnings

### ISSUE THREAD

**Issue by robogeek** [mapbox/node-sqlite3#1311]
Set up a Node.js project that depends on the `sqlite3` module.  Then, when running Node.js 14.0, run `npm install`.  There are a zillion warnings printed but the module does get installed, and it works fine.  A message does get printed saying that it tried to download a prebuilt binary, and one wasn't found, so it falls back to compiling the code.

FWIW I am on macOS 10.13.x, and I've also seen this inside the `node:14` Docker container (based on Debian).

In the `package.json,` the dependency is written as:

```
"sqlite3": "https://github.com/mapbox/node-sqlite3/archive/v4.2.0.tar.gz"
```

to use the 4.2.0 release.

If I revert to Node.js 13.13.x then it finds the prebuilt binary and uses that.

It's probably not necessary to include the long list of warnings, so this is a random sample that gives a sense of what's up.  Namely that some things have been deprecated.

```
../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/statement.cc:322:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Bind);
    ^
../src/macros.h:128:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:347:13: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
            TRY_CATCH_CALL(stmt->handle(), cb, 1, argv);
            ^
../src/macros.h:112:10: note: expanded from macro 'TRY_CATCH_CALL'
    Nan::MakeCallback((context), (callback), (argc), (argv))
         ^
../../nan/nan.h:1026:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/statement.cc:370:5: warning: unused variable 'status' [-Wunused-variable]
```

**Comment by abir-taheer** [comment]
Not the exact same issue, but I'm having something very similar! My CI is now failing tests for Node 14 because sqlite3 doesn't install properly

**Comment by regevbr** [comment]
same here

**Comment by regevbr** [comment]
Using yarn2 also fails because the fallback tries to use node-gyp which is not a direct dependency.
Current fix is to add to .yarnrc.yml
```yml
packageExtensions:
  sqlite3@*:
    dependencies:
      node-gyp: "*"
```
Permanent fix is to add node-gyp as a dependency to this project.

**Comment by kewde** [comment]
Node 14 is not yet supported and v4.2.0 is not officially released to npm yet.
