### ISSUE TITLE
Support for Node.js 14.x

### ISSUE THREAD

**Issue by robogeek** [mapbox/node-sqlite3#1314]
According to the final comment in https://github.com/mapbox/node-sqlite3/issues/1311 - This package does not currently support Node.js 14.x.  Several people reported in the issue problems when trying to install it on 14.x.

This issue was created to clearly state the need for supporting SQLite3 on Node.js 14.x.

**Comment by robogeek** [comment]
In my case, I'm in the final stages of finishing the 5th edition of my book, _Node.js Web Development_, where the main focus is updating for the Node.js 14.x release.

The book features SQLite3 prominently as a way to simplify doing SQL development because you don't have to set up a database server.

It's problematic to tell the reader to use 14.x with SQLite3 if the combination does not work.

I think the book will be publishable within 2 months.  If I have to, I will be telling the reader that if 14.x with SQLite3 is still giving errors they must backtrack to Node.js 13.13 because that's the last supported release.

**Comment by analytik** [comment]
Just to share some hope here, sqlite3@4.1.1 **builds** just fine on my Windows 10 x64 with Node.js v14.0.0.

My app using it is very simple, but it does some basic CRUD with it. Hopefully this means that the changes needed in the source code will be minimal, and might just need some configuration changes to prebuild the binary for all platforms.

**Comment by kewde** [comment]
cc4b598c8cbaaa128c0528fa4a2075bfca17a5f6
Will be fixed when v5.0.0 is released.

**Comment by ujwal-setlur** [comment]
Has this been released to npmjs?

**Comment by robogeek** [comment]
@ujwal-setlur If you look up this issue, you see that @kewde added this issue to the 5.0.0 milestone.  In other words, this will be in 5.0.0.

My question is - when will that be?

I have a practical reason for asking this.  As I said at the top of this, I am working on a new edition of my book, and part of the book uses SQLite3.  I need to know whether to have the book reference 4.2.0 of this module, or 5.0.0, and what will determine that is the time frame that 5.0.0 will be released in.  The book should be finished in June, FWIW.

**Comment by panther7** [comment]
Any news? V5.0.0 still missing in npm.

**Comment by dannysofftie** [comment]
> Any news? V5.0.0 still missing in npm.

What's the status of this release?

**Comment by tabrindle** [comment]
It looks like the tag and release are missing, but the code is there and appears to be working in latest master. 

While certainly not best practice, I installed at this commit hash, and everything worked as expected:
`https://github.com/mapbox/node-sqlite3#c196b05103cc34f33e7292d0578974ccd1fe349a"`

**Comment by eiskalteschatten** [comment]
It's appalling that there is a lack of communication as to when this is coming. My company is waiting to upgrade to Node 14 exactly because this one, single package doesn't support it. Very frustrating.

**Comment by ujwal-setlur** [comment]
https://kewde.github.io/sqlite

I am waiting as well, but this is open source. Yes, this is a sponsored project...but it's still open source. Time to contribute or fork.

**Comment by kewde** [comment]
I have not yet released it because

**Comment by InclinedScorpio** [comment]
@kewde : For me it's still failing, is there any specific version I need to use along with node 14?
I am getting below error:

` ERROR [4/4] RUN npm ci --only=production                                                             3.7s
------
 > [4/4] RUN npm ci --only=production:
#8 1.986
#8 1.986 > sqlite3@4.2.0 install /usr/src/app/node_modules/sqlite3
#8 1.986 > node-pre-gyp install --fallback-to-build
#8 1.986
#8 2.057 node-pre-gyp WARN Using needle for node-pre-gyp https download
#8 3.464 node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-arm64.tar.gz
#8 3.465 node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.17.6 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
#8 3.626 gyp ERR! find Python
#8 3.626 gyp ERR! find Python Python is not set from command line or npm configuration
#8 3.626 gyp ERR! find Python Python is not set from environment variable PYTHON
#8 3.627 gyp ERR! find Python checking if "python" can be used
#8 3.627 gyp ERR! find Python - "python" is not in PATH or produced an error
#8 3.627 gyp ERR! find Python checking if "python2" can be used
#8 3.627 gyp ERR! find Python - "python2" is not in PATH or produced an error
#8 3.627 gyp ERR! find Python checking if "python3" can be used
#8 3.627 gyp ERR! find Python - "python3" is not in PATH or produced an error
#8 3.627 gyp ERR! find Python
#8 3.627 gyp ERR! find Python **********************************************************
#8 3.627 gyp ERR! find Python You need to install the latest version of Python.
#8 3.627 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#8 3.627 gyp ERR! find Python you can try one of the following options:
#8 3.627 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#8 3.627 gyp ERR! find Python   (accepted by both node-gyp and npm)
#8 3.627 gyp ERR! find Python - Set the environment variable PYTHON
#8 3.627 gyp ERR! find Python - Set the npm configuration variable python:
#8 3.627 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#8 3.627 gyp ERR! find Python For more information consult the documentation at:
#8 3.627 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#8 3.627 gyp ERR! find Python **********************************************************
#8 3.627 gyp ERR! find Python
#8 3.627 gyp ERR! configure error
#8 3.628 gyp ERR! stack Error: Could not find any Python installation to use
#8 3.628 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#8 3.628 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#8 3.628 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#8 3.628 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#8 3.628 gyp ERR! stack     at exithandler (child_process.js:397:5)
#8 3.628 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:409:5)
#8 3.628 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#8 3.628 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
#8 3.628 gyp ERR! stack     at onErrorNT (internal/child_process.js:467:16)
#8 3.628 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
#8 3.628 gyp ERR! System Linux 5.10.47-linuxkit
#8 3.628 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
#8 3.628 gyp ERR! cwd /usr/src/app/node_modules/sqlite3
#8 3.628 gyp ERR! node -v v14.17.6
#8 3.628 gyp ERR! node-gyp -v v5.1.0
#8 3.628 gyp ERR! not ok
#8 3.630 node-pre-gyp ERR! build error
#8 3.631 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
#8 3.631 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#8 3.631 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#8 3.631 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
#8 3.631 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
#8 3.631 node-pre-gyp ERR! System Linux 5.10.47-linuxkit
#8 3.631 node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#8 3.631 node-pre-gyp ERR! cwd /usr/src/app/node_modules/sqlite3
#8 3.631 node-pre-gyp ERR! node -v v14.17.6
#8 3.631 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#8 3.631 node-pre-gyp ERR! not ok
#8 3.631 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/src/app/node_modules/sqlite3/lib/binding/node-v83-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
#8 3.639 npm ERR! code ELIFECYCLE
#8 3.639 npm ERR! errno 1
#8 3.642 npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
#8 3.642 npm ERR! Exit status 1
#8 3.642 npm ERR!
#8 3.642 npm ERR! Failed at the sqlite3@4.2.0 install script.
#8 3.642 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#8 3.648
#8 3.648 npm ERR! A complete log of this run can be found in:
#8 3.648 npm ERR!     /root/.npm/_logs/2021-12-08T07_56_59_159Z-debug.log
------
executor failed running [/bin/sh -c npm ci --only=production]: exit code: 1
`
