### ISSUE TITLE
sqlite3 installation error

### ISSUE THREAD

**Issue by mucahidyazar** [mapbox/node-sqlite3#1320]
https://gist.github.com/mucahidyazar/10b072fc036437402a40f4a628682542

This is my error. I tried to clean cache
I tried this one
npm install sqlite3 --verbose --no-rollback

But everytime I got error. Whats problem on there guys.

**Comment by kewde** [comment]
```
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
```

You using Node v14 - which is not yet supported by prebuilt binaries. (#1314)
The fallback method is to build it locally, which failed because you do not have the right setup locally in order to build it.
