### ISSUE TITLE
Use 4.2.0 with electron@7.2.4: not a valid Win32 application

### ISSUE THREAD

**Issue by jackple** [mapbox/node-sqlite3#1326]
After upgrade to 4.2.0, there is no binary for download, by building on local machine, the output file is not working on win

https://github.com/mapbox/node-sqlite3/issues/910#issuecomment-510104260

![image](https://user-images.githubusercontent.com/6183232/81571144-25845200-93d4-11ea-8b31-50a0b8f416cf.png)

**Comment by kewde** [comment]
#1324 merged but not released yet.

**Comment by mapleby** [comment]
You need to build it yourself.

There are many steps, but they are not cumbersome.

If you want to know more, please send me email: 1109505386@qq.com

mapleby@outlook.com
