### ISSUE TITLE
android termux how install

### ISSUE THREAD

**Issue by neechange** [mapbox/node-sqlite3#1327]
> sqlite3@4.2.0 install /data/data/com.termux/files/home/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v72-android-arm64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@12.12.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/which/which.js:89:16

**Comment by kewde** [comment]
see #1169 for ARM builds.
