### ISSUE TITLE
Using sqlite3 with nw and angular

### ISSUE THREAD

**Issue by vatsalkgor** [mapbox/node-sqlite3#1333]
I tried to manually compile sqlite3 and add in in the project using nw-gyp as described in the README.

Many of the tutorial say that to use sqlite3, nw and angular together I have to approach like
Angular -> Express -> sqlite3
Where Angular handles the UI part, using express I create an API and the api endpoints performs 
database read write operations.

I'm using the template from [here](https://github.com/nwutils/nw-angular-cli-example) to create a minimal angular nw app and then at the root of this project I create an API folder in which my express api resides. 

However when I try to import manually built sqlite3 in to the code I get following error and my express server fails to start. 
<img width="880" alt="Screen Shot 2020-05-21 at 18 10 10" src="https://user-images.githubusercontent.com/38848916/82529882-19e11a00-9b90-11ea-834c-3c93bb7fe6ca.png">
in my node_modules/sqlite3/lib/bin I have folder named node-webkit-v0.46.0-darwin-x64 as expected from the manual build. 
<img width="418" alt="Screen Shot 2020-05-21 at 18 23 52" src="https://user-images.githubusercontent.com/38848916/82530019-6593c380-9b90-11ea-9f8e-2f5ecf45f1e6.png">

I'm starting the express server using node-main argument from nw pointing towards my startup script. 

The minimal reproducible example for the following just to import the sqlite3 in a script and then put that script in node-main to start it before the nw application loads. 

What is the cause for this error and how to fix this?

**Comment by panther7** [comment]
Same problem...

**Comment by vatsalkgor** [comment]
Have you found any alternative?@panther7

**Comment by panther7** [comment]
@vatsalkgor https://github.com/JoshuaWise/better-sqlite3 ?

**Comment by vatsalkgor** [comment]
Thanks for the suggestion. Because of JoshuaWise/better-sqlite3#65, I didn't try it till today. 
However, to my surprise, when I tried it today it worked like a charm. You can find the complete boilerplate with nwjs [here](https://github.com/vatsalkgor/nw-sqlite3-error). 

Thanks again for the suggestion though. I would not have tried it if you haven't suggested it.
