### ISSUE TITLE
Keep Node 10 prebuilt for v5 release

### ISSUE THREAD

**Issue by xPaw** [mapbox/node-sqlite3#1334]
It was removed in this commit: https://github.com/mapbox/node-sqlite3/commit/cc4b598c8cbaaa128c0528fa4a2075bfca17a5f6 but Node 10 is LTS maintaince for another year, as seen here: https://nodejs.org/en/about/releases/

As a lot of packages still provide v10 versions, it would be good to keep it around for now.

**Comment by mtgto** [comment]
There is no needs to distribute node 10 prebuild binaries, IMO.

- prebuilt of node-sqlite3 is Electron v6 or later
- Electron v6 uses Node.js v12
    - https://github.com/electron/electron/releases/tag/v6.0.0

You can use node 10 on your machine while maintenance phase, but please remember node 10 is not suitable for electron environment.

**Comment by xPaw** [comment]
I am shipping an app, so it is out of my direct control what version of node users use.

That's why we keep the minimum supported version aligned with Node's LTS releases. A lot of packages follow that too.

**Comment by mtgto** [comment]
@xPaw Sorry, I misread your description.

**Comment by kewde** [comment]
034c05fdf5bd957a914829517cfb49b473718f28

**Comment by kewde** [comment]
Binaries for 5.0.0 were prepared, releasing today.
