### ISSUE TITLE
Electron 9 support

### ISSUE THREAD

**Issue by panuhorsmalahti** [mapbox/node-sqlite3#1337]
Prebuilt binaries are currently missing for Electron 9. They should be added (probably similar to https://github.com/mapbox/node-sqlite3/pull/1294/files).

**Comment by jjhbw** [comment]
`sqlite3` 5.0 needs to be released first because of https://github.com/electron/electron/issues/18397. See also #1331 .

**Comment by tobias-klein** [comment]
What's the status of this issue? Can this be expected to be resolved any time soon? Any help needed?

**Comment by panuhorsmalahti** [comment]
electron 9 is now supported (verified to work in my application).

**Comment by panuhorsmalahti** [comment]
The main readme could be updated with this information though.
