### ISSUE TITLE
How to get the value when I do not know the column  name?

### ISSUE THREAD

**Issue by dixinke** [mapbox/node-sqlite3#1348]
Hi，I have a program like thsi

`var SqliteDB = require('./sqlite.js').SqliteDB;
var file = "modbus.db";
var sqliteDB = new SqliteDB(file);
var querySql = 'select * from student';

function seqDeal(result){
	console.log(result[0].age);     ////////// Get the value of age
}
sqliteDB.queryData(querySql, seqDeal);`

It is work well. I can get the value of 'age'.
But if i do not know the column name 'age', I only know this is the first column, how can I get the value??
I should change 'console.log(result[0].age); ' like what??????

**Comment by kewde** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames
