### ISSUE TITLE
sqlite3 doesn't install correctly?

### ISSUE THREAD

**Issue by pulli23** [mapbox/node-sqlite3#1350]
I'm trying to setup sqlite3 as a sort-of "mock" for integration testing, sqlite3 will be the driver for a knex query builder.

Now it installs happily with `npm install sqlite3 --save`. However upon running the following error occurs when loading:

```
Error: Cannot find module '<personal>/node_modules/sqlite3/lib/binding/node-v83-linux-x64/node_sqlite3.node' from 'node_modules/sqlite3/lib/sqlite3-binding.js'
    Require stack:
      node_modules/sqlite3/lib/sqlite3-binding.js
      node_modules/sqlite3/lib/sqlite3.js
      node_modules/knex/lib/dialects/sqlite3/index.js
      node_modules/knex/lib/knex.js
      node_modules/knex/lib/index.js
      node_modules/knex/knex.js
      test/controllers/sheets.test.ts
```
Looking through the actual node_modules directory I notice there exists a folder in ` node_modules/sqlite3/lib/binding/node-v72-linux-x64` with the expected file.

Is node-pre-gyp installing the wrong version? - how can I fix this?

**Comment by kewde** [comment]
Delete the sqlite3 folder and re-install. Make sure to use the same version of Node & npm.

**Comment by pulli23** [comment]
Oh I'm terribly sorry for wasting your time. I notice that webstorm's internal terminal didn't update the node version when I swapped it. And hence the terminal there had a different version than the runner.
