### ISSUE TITLE
Sorting with node-sqlite3 isn't correct

### ISSUE THREAD

**Issue by Paultje52** [mapbox/node-sqlite3#1374]
Hello. I'm programming a website to search in a sqlite database. On my backend, I have this.
```js
let query = `SELECT * FROM "main"."SPTOT" WHERE lower("Country") LIKE 'australia' ESCAPE '\\' ORDER BY Country, Operator, "Basic Type", Serial, Date`;
  db.all(query, (err, rows) => {	
    if (err) throw err;
    res.json({
      rows: rows,
      query: query
    });
  });
```
The result is sorted by date, but it should sort by Country, Operator, BasicType, Serial and then Date.

When I'm using [DB Browser for SQLite](https://sqlitebrowser.org/) with the exact same query, the results are sorted like they should be.

**From node-sqlite3**
![image](https://user-images.githubusercontent.com/31313717/91290048-6e99bf80-e793-11ea-81c6-7009fa587cd0.png)

**From DB Browser**
![image](https://user-images.githubusercontent.com/31313717/91290111-82452600-e793-11ea-89f2-517bab868c0a.png)

Am I doing something wrong or is this an issue with node-sqlite3?

**Comment by acrtz** [comment]
While SQLite has some functionality for working with date/time, it doesn't actually have a date/time type so when you make the comparison for ordering date you are just comparing two strings which explains the unexpected ordering.
It looks like the date is converted to a unix timestamp in the DB Browser example. If you were to convert to a unix time stamp for the sqlite3 example then the order should also be correct.
