### ISSUE TITLE
SQLite on Node.js with async/await - unable to run transaction

### ISSUE THREAD

**Issue by umapathyrd** [mapbox/node-sqlite3#1378]
Hi,

We are using async/await approach to connect sqlite on node.js. (approach from https://www.scriptol.com/sql/sqlite-async-await.php).
Here all is working fine except transaction (with in begin transaction and commit).

We are trying to run transaction using db.run as example below

var sql = "begin transaction; INSERT INTO users(ID) VALUES (1); INSERT INTO users(ID) VALUES (2); INSERT INTO users(ID) VALUES (3); commit;"
        r = await sqlite.run(sql)
        if(r) console.log("Inserted.")

and getting error, transaction is already opened.

How do we resolve this problem ?

**Comment by MitchellMonaghan** [comment]
I am also having this issue. Just like the example above my transaction is a single statement run by sqlite. So there is no way I left a unclosed transaction open. This is also the only place in my code where I am using transactions.

SQLITE_ERROR: cannot start a transaction within a transaction

**Comment by umapathyrd** [comment]
Hi,

We have used exec function instead of 'run' function to execute batch transaction. Thus resolved the problem.

Hope this helps.

Thank You
Umapathy
