### ISSUE TITLE
Publish 5.0.1

### ISSUE THREAD

**Issue by awjreynolds** [mapbox/node-sqlite3#1386]
It appears you've updated and finished 5.0.1 but have not published it to npm etc.

**Comment by awjreynolds** [comment]
@kewde I note you released 5.0.1 16 days ago. Can this be published to npm so that we can pick up on these changes. 

SNYK has identified an issue with 5.0.0 which is fixed by 5.0.1

**Comment by kitokip** [comment]
Any progress on this?

**Comment by alexrecuenco** [comment]
We are wondering if there is any update on this

**Comment by hverlin** [comment]
Hi, do you have an update on this? Is there anything we can do to help?

**Comment by naz** [comment]
@kewde adding to the rest of comments above :heavy_plus_sign: Would love to help 5.0.1 npm publish happen as well.

P.S. Big thanks for all the work you've put into this project :black_heart:

**Comment by Jolg42** [comment]
Same here 👍 (Posting here to be sure to get a notification)

**Comment by trevyn** [comment]
Looks like this post might add some color:

https://kewde.github.io/sqlite

Sounds like kewde wants someone trustworthy with experience being a long-term open-source maintainer and who relies on node-sqlite3 for their business to step up and make a long-term commitment to helping maintain. Any takers?

**Comment by naz** [comment]
[5.0.1](https://www.npmjs.com/package/sqlite3/v/5.0.1) has been published on npm :tada:

**Comment by naz** [comment]
@awjreynolds think this issue can be closed now?

**Comment by awjreynolds** [comment]
Fantastic!

**Comment by kitokip** [comment]
thank you!
