### ISSUE TITLE
Make better concurrency 

### ISSUE THREAD

**Issue by Leaking** [mapbox/node-sqlite3#1392]
When we use statement.all method in node-sqlite，it will query the raw data from sqlite in [Work_All](https://github.com/mapbox/node-sqlite3/blob/833f5cc1332b9213a17873f42a3d3a18dca5afc1/src/statement.cc#L541) , then make the raw data into js objects and callback for js code in [Work_AfterAll](https://github.com/mapbox/node-sqlite3/blob/833f5cc1332b9213a17873f42a3d3a18dca5afc1/src/statement.cc#L567)

the method  [Work_All](https://github.com/mapbox/node-sqlite3/blob/833f5cc1332b9213a17873f42a3d3a18dca5afc1/src/statement.cc#L541) is invoked in the libuv worker thread but the method [Work_AfterAll](https://github.com/mapbox/node-sqlite3/blob/833f5cc1332b9213a17873f42a3d3a18dca5afc1/src/statement.cc#L567) is invoked in the main thread.

when we use statement.all to query large data, the method Work_AfterAll will cost most of time. 
I think it wiil be better to move the following code  from Work_AfterAll to Work_All, which making raw data into js objects

```
Napi::Array result(Napi::Array::New(env, baton->rows.size()));
                Rows::const_iterator it = baton->rows.begin();
                Rows::const_iterator end = baton->rows.end();
                for (int i = 0; it < end; ++it, i++) {
                    std::unique_ptr<Row> row(*it);
                    (result).Set(i, RowToJS(env,row.get()));
                }

                Napi::Value argv[] = { env.Null(), result };
```

**Comment by alex3d** [comment]
Unfortunately, it is impossible. The majority of Napi/NAN functions (including JS object creation) could be called only from the main/event loop thread.

**Comment by Leaking** [comment]
> Unfortunately, it is impossible. The majority of Napi/NAN functions (including JS object creation) could be called only from the main/event loop thread.

yep, I found this limitation several days ago

**Comment by Leaking** [comment]
> Unfortunately, it is impossible. The majority of Napi/NAN functions (including JS object creation) could be called only from the main/event loop thread.
what about use arraybuffer

**Comment by Leaking** [comment]
> > Unfortunately, it is impossible. The majority of Napi/NAN functions (including JS object creation) could be called only from the main/event loop thread.
> 
> yep, I found this limitation several days ago

what about  use arraybuffer to pass query result from c++ to js, arraybuffer can speed up passing data and avoid copy of passed data
