### ISSUE TITLE
bump node-gyp dependency to from 3.x to 7.x

### ISSUE THREAD

**Issue by Pomax** [mapbox/node-sqlite3#1415]
The current version of the `node-gyp` dependency is `3.x`, released in 2018, which is so out of date that it can't run on modern setups due to the fact that Python 2.7 was finally officially discontinued in January of 2020, and so doesn't get installed on new systems anymore, while relying on code that is incompatible with Python 3 and so causes the `gyp` process to crash.

It would be great if this dependency could be bumped up to `7.x` instead.

**Comment by ed789d0** [comment]
Another issue is that versions before 7.x don't work correctly with some macOS Catalina installs, according to https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#installation-notes-for-macos-catalina-v1015

**Comment by kewde** [comment]
Merged in #1441
