### ISSUE TITLE
Dont Add "discord.js-commando" module

### ISSUE THREAD

**Issue by DigitalGamerTR** [mapbox/node-sqlite3#1416]
Please Help Me im dont add discord.js-commando
![kdksakdsakd](https://user-images.githubusercontent.com/39560877/103152810-17811700-4794-11eb-9bfa-78fe8071bc67.JPG)

**Comment by DigitalGamerTR** [comment]
![2](https://user-images.githubusercontent.com/39560877/103152819-29fb5080-4794-11eb-9957-1ffb89776fe5.JPG)

**Comment by DigitalGamerTR** [comment]
![Uploading 3.JPG…]()

**Comment by DigitalGamerTR** [comment]
![3](https://user-images.githubusercontent.com/39560877/103152829-44cdc500-4794-11eb-8f0c-b0b286ff481c.JPG)

**Comment by ed789d0** [comment]
This stems from issue #1421 and it's an issue with the servers that have the download for this module.

**Comment by michga** [comment]
From the first screenshot, it looks like you have to properly install python on your system.

> 'python' is not recognized as an internal or external command,
> operable program or batch file

**Comment by ed789d0** [comment]
You may be able to try `npm install sqlite3@5.0.0` before installing commando.

**Comment by kewde** [comment]
v4.2.0 does not support that version of node, please move to 5.0.2 or higher.
