### ISSUE TITLE
Install fails with "Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz ".

### ISSUE THREAD

**Issue by ira-gordin-sap** [mapbox/node-sqlite3#1421]
How to reproduce on Linux:

1. Create a folder with package.json with the following content:
{
"name": "project",
"version": "1.0.0",
"description": "A simple project.",
"repository": "",
"license": "UNLICENSED",
"private": true,
"dependencies": {
"sqlite3": "^5.0.1"
}
}
2. cd to the folder and run "npm install"

Environment:
$ uname -a
Linux 5.4.0-4-cloud-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
$ node -v
v10.23.0

**Comment by gpetrov** [comment]
just got the same - seems the binaries for the latest version aren't available:

```
> sqlite3@5.0.1 install /opt/node_app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.1 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
```

Are any binaries available? Or is something wrong with the amazone S3 access settings - as it gives access denied all the time.

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>26304C28165B6492</RequestId>
<HostId>SIoQ7AN40mJByPyfSNfkt+xI1+1GUvqXbUj8l102kE0uT3/bRz2tkupLU0ddlz2v0zeXG3mmds8=</HostId>
</Error>
```

**Comment by bkrrrr** [comment]
i got the same with node 12/14 on windows with SQLLite 5.0.1

**Comment by ozonep** [comment]
Yep, me too.
Maybe some issues with S3 bucket... Quota exceeded or something else.

**Comment by vegarringdal** [comment]
me too

**Comment by MarcosRuginski** [comment]
same issue

**Comment by ddhp** [comment]
occurred to me as well

**Comment by iHildy** [comment]
same issue

**Comment by murilobd** [comment]
Same issue here

**Comment by benhovinga** [comment]
#1389 already brought up this issue.

**Comment by azabroflovski** [comment]
same issue

**Comment by leohxj** [comment]
same!!!

**Comment by tkikuike** [comment]
I have same trouble, for raspberry pi(ARM)

https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-linux-x64.tar.gz ← this URL works :)
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.0/napi-v3-linux-arm.tar.gz ← this URL doesnt  :(

**Comment by zoosm3** [comment]
I got the same error with version `5.0.0`. Seems no way to fix it.
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.1/napi-v6-win32-x64.tar.gz <- this doesn't work

**Comment by gpetrov** [comment]
I wonder why this isn't fixed yet - such an urgent issue, so many production pipelines broken...

Just due to simple missing binary or wrong S3 permissions...

Who is responsible for that?

**Comment by chgeo** [comment]
Yes, this is also my concern here.
So, let's ping e.g. @kewde again who did the 5.0.1 release: can you handle this urgent issue?

**Comment by zetaraku** [comment]
@zoosm3 Manually fallback to 5.0.0 works for me:
```
npm install sqlite3@5.0.0
```
Have you tried this?

**Comment by JVMartin** [comment]
Same issue, fixed by pinning `"sqlite3": "5.0.0"`

**Comment by digaev** [comment]
Bump, but I believe it worked fine yesterday.

**Comment by r-52** [comment]
Looks like 5.0.1 and 5.0.0 are broken right now.
They return:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0DB59BC5703DC0FC</RequestId>
<HostId>
s7ost2vaTRtvAVHbyjRzHGxMN34yrI5fgqlMxf4oSCLOjw+qy5oPGJiE1urzQU3vEy7Bl5M5PXg=
</HostId>
</Error>
```

**Comment by dark-matter-matters** [comment]
Same issue here. No way to bypass it as I don't have a local copy of my node_modules folder.

**Comment by Haynesy** [comment]
5.0.2 seems to have the same problem now

**Comment by shashwatmi** [comment]
I am getting Same error for v4.2.0 and for 5.0.2 also

**Comment by Terxeno** [comment]
Same Error!

**Comment by suyeonpi** [comment]
Same issue

**Comment by JohnUSA** [comment]
Same issue

**Comment by bojanbizjak** [comment]
Same issue

**Comment by allanbarcelos** [comment]
Same issue here

**Comment by LxnChan** [comment]
Same issue.

**Comment by dev-intellisoft** [comment]
same issue

**Comment by nmccready** [comment]
What in the world is going on can we get an admin on this? mapbox bucket is toast.
