### ISSUE TITLE
Cannot find module 'E:\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node'

### ISSUE THREAD

**Issue by Thalinda** [mapbox/node-sqlite3#1427]
I am developing an electron application using the sqlite3 module and I have developed the code related to function separately now after everything is done now I am trying to import that separately developed module to my main.js file but it's throwing an error from require

> Cannot find module 'E:\CSV-CONVERTOR\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node'

now I have tried so many solutions I'm attaching the solution I have tried below

1. [This one ](https://github.com/mapbox/node-sqlite3/issues/906)
2. [This one](https://stackoverflow.com/questions/60646719/error-cannot-find-module-node-modules-sqlite3-lib-binding-electron-v8-0-win32)
3. [This one](https://discuss.atom.io/t/sqlite3-cannot-find-node-sqlite3-node-question/16530)
4. [This one](https://forum.ghost.org/t/unable-to-install-ghost-locall-on-windows-10/18768)

> Error: Cannot find module 'E:\On Going Projects\CSV-CONVERTOR\node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node'

> 
> Require stack:
> - E:\On Going Projects\CSV-CONVERTOR\node_modules\sqlite3\lib\sqlite3-binding.js
> - E:\On Going Projects\CSV-CONVERTOR\node_modules\sqlite3\lib\sqlite3.js
> - E:\On Going Projects\CSV-CONVERTOR\assets\processors\proccess.js
> - E:\On Going Projects\CSV-CONVERTOR\main.js
> - E:\On Going Projects\CSV-CONVERTOR\node_modules\electron\dist\resources\default_app.asar\main.js
> -
>     at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
>     at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
>     at Module._load (internal/modules/cjs/loader.js:848:27)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
>     at Module.require (internal/modules/cjs/loader.js:1032:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (E:\On Going Projects\CSV-CONVERTOR\node_modules\sqlite3\lib\sqlite3-binding.js:4:15)
>     at Module._compile (internal/modules/cjs/loader.js:1152:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
>     at Module.load (internal/modules/cjs/loader.js:992:32)

`var sqlite3 = require('sqlite3').verbose();`

this is the import of the sqlite package witch working perfectly when i run
`node process.js
`
![sc](https://user-images.githubusercontent.com/45384206/104821915-38093200-5865-11eb-9a8d-fb58c7b445f2.PNG)

**Comment by endlesstravel** [comment]
same question , but on nw.js v0.50.3

**Comment by Thalinda** [comment]
I was able to fix it after downgrading try downgrading.. and it's now affecting in mac os this happens only in windows

**Comment by endlesstravel** [comment]
after some work, i success build it and run `require("sqlite3")` at  nw-v0.50.3
![image](https://user-images.githubusercontent.com/10757838/105618672-04aa4280-5e25-11eb-8de0-215520cfea80.png)
here is my build version : 
[napi-v6-win32-x64.zip](https://github.com/mapbox/node-sqlite3/files/5861409/napi-v6-win32-x64.zip)


1) use python 2.7 but not  python 3.6, change path on window PATH system environment varible
2) force to install `nw-gyp` and `node-pre-gyp`
```
npm i -g nw-gyp node-pre-gyp
```
3) run
 `npm i sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.50.3`
 or
`npm i sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=nw-v0.50.3`
4) i build success in  `node_modules\sqlite3\lib\binding\napi-v6-win32-x64\node_sqlite3.node'

it need  `python 2.7` + `nw-gyp` + `node-pre-gyp` + `visual studio 2015/2017/2019` + `"visual studio c++ dev tool"`
look at here : https://github.com/nwjs/nw-gyp/issues/130#issuecomment-541327581

**Comment by Thalinda** [comment]
now the answer of the @endlesstravel did indeed help but I had to do this also so if after doing @endlesstravel  thing didn't solve do [this ](https://stackoverflow.com/questions/65754113/cannot-find-module-e-node-modules-sqlite3-lib-binding-napi-v6-win32-x64-node-s/66051487#66051487)also
