### ISSUE TITLE
 Security Issue: Request for contact

### ISSUE THREAD

**Issue by cristianstaicu** [mapbox/node-sqlite3#1440]
Hi there, 

I may have found a security issue in this project. Please create an advisory (https://github.com/mapbox/node-sqlite3/security/advisories) and invite me to further disclose and discuss the vulnerability. Alternatively, please add a security policy to the project containing a security email address to where I can send the details to. 

Best, 
Cris

**Comment by kewde** [comment]
Hi @cristianstaicu 

You can contact me at kewde@particl.io

Thank you.

**Comment by cristianstaicu** [comment]
Hey, thanks a lot for fixing this so quickly. What about letting the clients of the library know about this issue by publishing an advisory?
