### ISSUE TITLE
How to dump in memory database?

### ISSUE THREAD

**Issue by erkinsergey** [mapbox/node-sqlite3#1482]
I have an in memory database:
```
const sqlite3 = require('sqlite3');
const db = new sqlite3.Database(':memory:');
... // create structure and fill data
```
Is it possible to get a database dump (**without** getting all data from all tables manually)?

**Comment by erkinsergey** [comment]
I try call undocumented method backup
```
db.backup('mydump.sql', () => 
{
   console.log('dump ready!');
});
```
mydump.sql is created but it is always empty... The database exactly have data.

**Comment by gms1** [comment]
thanks; I didn't know this is even supported; just found the corresponding PR
https://github.com/mapbox/node-sqlite3/pull/1116
 and will test this in the next days

**Comment by gms1** [comment]
looks good; essentially it works as described in this PR

about:
```
var backup = db.backup('backup.db');
backup.step(-1);
backup.finish();
```
of course `backup.step` is asynchronous, so please provide a callback (or poll until one of `backup.complete` or `backup.failed` or `backup.idle` is true)

about https://github.com/mapbox/node-sqlite3/pull/1116#issuecomment-477330473
@paulfitz 
the mentioned commit did not find its way into the master branch. When I try to pass in a database object, I get the original error "Filename expected".

**Comment by gms1** [comment]
and the JSDoc for Database#backup seems to be partially wrong; `sourceName` and` destName` are probably swapped

https://github.com/paulfitz/node-sqlite3/blob/master/lib/sqlite3.js
```
// Database#backup(filename, destName, sourceName, filenameIsDest, [callback])
...
        backup = new Backup(this, arguments[0], arguments[1], arguments[2], arguments[3], arguments[4]);
};
```

https://github.com/mapbox/node-sqlite3/blob/master/src/backup.cc
```C++
        Napi::String filename = info[1].As<Napi::String>();
        Napi::String sourceName = info[2].As<Napi::String>();
        Napi::String destName = info[3].As<Napi::String>();
        Napi::Boolean filenameIsDest = info[4].As<Napi::Boolean>();
```

**Comment by erkinsergey** [comment]
@gms1 Thanks for the tip, it really works!
But for myself, I have already found a solution:
```
-- Get the names of all my tables
SELECT name FROM sqlite_master WHERE type ='table' AND  name NOT LIKE 'sqlite_%'
-- And after
SELECT * FROM :tableName
```
