### ISSUE TITLE
node-gyp's version is too low

### ISSUE THREAD

**Issue by 564064202** [mapbox/node-sqlite3#1500]
node-gyp's version is too low! this effects other packages,

**Comment by blubaustin** [comment]
See https://github.com/mapbox/node-sqlite3/pull/1503 for a fix

**Comment by samuelms1** [comment]
Fixed in #1441 and already merged, but the update was never published to npm

**Comment by 564064202** [comment]
> 已在[#1441 中](https://github.com/mapbox/node-sqlite3/pull/1441)修复并已合并，但更新从未发布到 npm

sir,please do a good man
