### ISSUE TITLE
install fails on macos with node 14

### ISSUE THREAD

**Issue by sirpy** [mapbox/node-sqlite3#1506]
Trying to install sqlite3 5.0.2
The long error starts with
`node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-darwin-x64.tar.gz`

This only happens on node 14.18.0 (downgrading to sqlite 5.0.0 also doesnt work)
If I switch to node 12, install works just fine

**Comment by kewde** [comment]
v4.2.0 does not support Node v14.
