### ISSUE TITLE
SQLite Engine 3.36

### ISSUE THREAD

**Issue by jeppard** [mapbox/node-sqlite3#1518]
Is there a posibility to create a Release in the near Future to get RETURNING statements working with npm?

I've come accros this Stakeoverflow Question [link](https://stackoverflow.com/questions/69813262/sqlite-syntax-error-near-returning-node/69813547?noredirect=1#comment123405811_69813547)

Or is there a way to use a package from git in a unreleased state?

**Comment by Oreilles** [comment]
While it isn't released yet, you have the option to install it from the latest commit with
```bash
npm i mapbox/node-sqlite3#918052b538b0effe6c4a44c74a16b2749c08a0d2 --build-from-source
```

**Comment by jeppard** [comment]
Thanks for the Answer expetionaly for the exact command because i tryed and failed before
