### ISSUE TITLE
Please support darwin-arm64 !!! 

### ISSUE THREAD

**Issue by chenpx976** [mapbox/node-sqlite3#1519]
```
Cannot find module 'node_modules/_sqlite3@5.0.0@sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node'

```

**Comment by StaZhu** [comment]
it actually support arm64, i think you should make some change yourself

**Comment by chgeo** [comment]
Duplicates #1513

**Comment by lmarcelocc** [comment]
@chenpx976 did you got any solution for your issue ? Have exactly the same.

**Comment by racsol** [comment]
Also having this issue with node v16.10.0. With an older node version was working fine but not with node 16.10.

**Comment by sators** [comment]
I'm getting this issue when trying to run node under x86 arch but on an M1 Apple

**Comment by marcin-zajac** [comment]
same issue on my M1 :(

**Comment by shto** [comment]
same issue

**Comment by sators** [comment]
The only solution I come up with is to manually change the folder name to be `sqlite3/lib/binding/napi-v3-darwin-arm64` ~ painful.

**Comment by iSamodurov** [comment]
same issue

**Comment by chenpx976** [comment]
colse by https://github.com/mapbox/node-sqlite3/issues/1538#issuecomment-1037839683
