### ISSUE TITLE
node 32位安装sqlite3时报错

### ISSUE THREAD

**Issue by lhc456** [mapbox/node-sqlite3#1530]
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://npm.taobao.org/mirrors/sqlite3/v5.0.2/napi-v3-win32-ia32.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@14.16.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)

 发现当前地址没有v5.0.2版本的安装包，想问一下，v5.0.2是否支持node32位， 使用的是node v 14.16.0.

**Comment by lhc456** [comment]
32位的包可以使用node的32位去下载

**Comment by pejiang** [comment]
> 32位的包可以使用node的32位去下载

node-pre-gyp ERR! node -v v9.11.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.11

node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.3/napi-v3-linux-ia32.tar.gz
gyp ERR! build error
