### ISSUE TITLE
When used with SQLite, 'order by' in prepared statement didn't work

### ISSUE THREAD

**Issue by yandongliu** [mapbox/node-sqlite3#178]
So I was using a prepared statement like

  select \* from table1 order by ?

and then ran it with parameter filled

  db.all(stmt, 'ctime desc', function(err,rows){...}

Returned results were not sorted. I can see the SQL sent to SQLite was

  select \* from table1 order by 'ctime desc'

the quotes of which is not supported by SQLite. Without the single quotes it would work.

Any way to work around this?

**Comment by jangxx** [comment]
This is still not fixed unfortunately. I just encountered this problem using node-sqlite **3.1.0** with node **4.2.1**.

**Comment by Mithgol** [comment]
Yes, I can see this problem in node-sqlite3 3.1.1 on Node v5.1.0 as well.

However, I am not convinced that this is a node-sqlite3's issue.

Perhaps, like in #330, we are facing an internal limitation of SQLite.

Is it really possible to use a parameter as a substitute for a column's name?

I know SQLite's “[Binding Values To Prepared Statements](https://www.sqlite.org/c3ref/bind_blob.html)” says “literals may be replaced by a parameter”. But columns' names are (as far as I know) identifiers, not literals.

**Comment by sky5walk** [comment]
I have the same error with v3.13.0.
