### ISSUE TITLE
Use node-sqlite3 with SQLCipher

### ISSUE THREAD

**Issue by Isolus** [mapbox/node-sqlite3#195]
It would be great to be able to encrypt a database.
SQLCipher (https://github.com/sqlcipher/sqlcipher) provides this possibility (it is only a modified version of sqlite3 and thus API compatible).

I tried to link node-sqlite3 dynamically against SQLCipher. But if I use the encryption features, it crashes with a SIGSEGV in SHA1_Final...

**Comment by aguynamedben** [comment]
@springmeyer I'm new to building native modules. I'm distributing an Electron app to user machines that don't have SQLCipher installed, and at runtime dynamic linking appears to be failing (i.e. Library not loaded: /usr/local/opt/sqlcipher/lib/libsqlcipher.0.dylib, called from dlopen).

I think I need to *statically* link SQLCipher. Do you know how I can tweak binding.gyp or pass flags to tell node-sqlite3 to statically link SQLCipher?

🙏
