### ISSUE TITLE
Dont recieve the lastId in callback when inserting a new row

### ISSUE THREAD

**Issue by szymonc** [mapbox/node-sqlite3#206]
Just like in topic, the callback always returns the null value and its the only value returned in case of the success.

**Comment by shafeequeot** [comment]
db.run(`INSERT INTO  myTable (data1, data2) VALUES (aa, bb)`, (err) => {
                console.log(this.lastID)
                if (err) {
                    console.log(err)
                } else {

                    console.log( this.lastID)
                }


Data base inserted successfully but result in callback function is undefine.
Can anyone help me what is the wrong with this code?

**Comment by ngdias** [comment]
> db.run(`INSERT INTO myTable (data1, data2) VALUES (aa, bb)`, (err) => { console.log(this.lastID) if (err) { console.log(err) } else {
> 
> ```
>                 console.log( this.lastID)
>             }
> ```
> 
> Data base inserted successfully but result in callback function is undefine. Can anyone help me what is the wrong with this code?

Apparently arrow functions don't inherit or bind the 'this' object, by design? I think these 2 links should be able to clarify you further:
https://stackoverflow.com/questions/34361379/are-arrow-functions-and-functions-equivalent-interchangeable
https://stackoverflow.com/questions/3127429/how-does-the-this-keyword-work

**Comment by szymonc** [comment]
It was almost 10 years ago, move on :)

**Comment by ngdias** [comment]
> It was almost 10 years ago, move on :)

I didn't notice! LOL

I just stumbled upon this page while researching the same problem - which came to me yesterday - so I decided to do the charitable thing and add some info that could be of use to others.

Cheers :) +1:
