### ISSUE TITLE
Unable to Obtain All Rows In A Table with database#each

### ISSUE THREAD

**Issue by BobCochran** [mapbox/node-sqlite3#242]
In this script:

<pre>
var sqlite3 = require('sqlite3').verbose()
var async = require('async')
var myList = []
var db = new sqlite3.Database('./test0.db')
async.series([
// Create a table and populate it
    function (callback) {
        db.run("CREATE TABLE lorem (listnumb bigint, info TEXT)", function (err) {
            if (err) return callback(err)
            console.log('Table created. ')
            callback()
        });

    },
    function (callback) {
        stmt = db.prepare("INSERT INTO lorem VALUES (?, ?);", function (err) {
            if (err) return callback(err)
            for (var i = 0; i < 10; i++) {
                stmt.run(i, "Ipsum " + i)
            }
            stmt.finalize();
            console.log('Table populated. ')
            callback()
        })

    },
    function (callback) {
        db.each("SELECT listnumb as numb, info FROM lorem;",
            function (err, row) {
                if (err) return callback(err)
                console.log(' numb = ' + row.numb + ' info field = ' + row.info)

            },
            function (err, cntx) {
                if (err) return callback(err)
                console.log('Number of retrieved rows is ' + cntx)
                callback()
            }

        )

    }
    ],
    // This function gets called after the tasks above have completed
    function(err) {
        if (err) return new Error(err)
        console.log("\n\nLength of array after the function go runs " + myList.length)
        db.close()
    })
</pre>

The db.each method does not obtain all the rows in the actual table. On my machine, an OS X 10.9.1 MacBook Pro, using node.js v0.10.24 and async 2.1.19, I get the following output:

<pre>
$ node pacheco3.js
Table created. 
Table populated. 
 numb = 0 info field = Ipsum 0
 numb = 1 info field = Ipsum 1
 numb = 2 info field = Ipsum 2
 numb = 3 info field = Ipsum 3
 numb = 4 info field = Ipsum 4
 numb = 5 info field = Ipsum 5
Number of retrieved rows is 6

Length of array after the function go runs 0
</pre> 

If I query the table directly using the sqlite3 shell, I get this output:

<pre>
$ sqlite3 test0.db
SQLite version 3.8.2 2013-12-06 14:53:30
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select listnumb as numb, info from lorem;
0|Ipsum 0
1|Ipsum 1
2|Ipsum 2
3|Ipsum 3
4|Ipsum 4
5|Ipsum 5
6|Ipsum 6
7|Ipsum 7
8|Ipsum 8
9|Ipsum 9
sqlite> .exit
</pre>

I am very green at coding node.js and JavaScript, so perhaps this problem is a result of my own poor coding? Or is it a bug?

Thanks,

Bob

**Comment by tarmo888** [comment]
Noticed that no solution to this, but the most probable solution to that `stmt.finalize();` needs to have calllback, otherwise it goes to next async.series before it finishes.

The example code on README.md is not the best example how to do `stmt.finalize();`
