### ISSUE TITLE
Cross compile node-sqlite3

### ISSUE THREAD

**Issue by ptitJu** [mapbox/node-sqlite3#249]
Hello,
I have a linux generated by buildroot on a raspberry pi (arm processor).

I can't install sqlite3 with npm install because it doesn't work.
So, I have tried to build from source. It requires python and g++. Unfortunately, g++ is not available for target in buildroot.

Finally, I have decided to cross-compile sqlite3 as I have done for example for node.js .

Here my script :

---
# !/bin/bash

export AR=/home/dev/Documents/rpi/buildroot-2013.05/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-ar
export CC=/home/dev/Documents/rpi/buildroot-2013.05/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc
export CXX=/home/dev/Documents/rpi/buildroot-2013.05/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-g++
export LINK=/home/dev/Documents/rpi/buildroot-2013.05/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabi-g++

npm install --sqlite=/usr/lib --build-from-source --target_arch=arm

---

The cross-compilation sucessfully finish.
In build/Release, I have:
- a directory lib
- a file "node_sqlite3.node"

Where I have to copy theses generated files ?
How do I use them ?

Thanks for your help.
Julien

**Comment by sonofwuyuan** [comment]
Hello, ptitJu
Now I have to cross-compile node-sqlite3 from source as you did.  When I excute "npm install --sqlite=/usr/lib --build-from-source --target_arch=arm", I got error "npm WARN cannot run in wd sqlite3@3.0.5 node-pre-gyp install --fallback-to-build"! 

What should i have to do to get file node_sqlite3.node generated successfully?

**Comment by ptitJu** [comment]
Look on google for "cannot run in wd".
It seems that wd means "working directory". Do you have right access to the folder ?
Are you as root ? Do you have test with sudo ?

Hope it can help you.
