### ISSUE TITLE
Tell the author that this fails on your system: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by MichaelJCole** [mapbox/node-sqlite3#256]
Hi, I'm getting this error in Linux Mint 16 (an Ubuntu 13.10 derivative).

> sqlite3@2.2.0 install /home/michael/scm/furtheryet.org/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! sqlite3@2.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! `sh "-c" "node-pre-gyp install --fallback-to-build"` failed with 127
npm ERR! 
npm ERR! Failed at the sqlite3@2.2.0 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-12-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/michael/scm/furtheryet.org/ghost
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/michael/scm/furtheryet.org/ghost/npm-debug.log
npm ERR! not ok code 0

The problem is that sqlite is looking for a binary "node".  In Ubuntu/Mint, this program is a HAM radio program.  The repo maintainers renamed node to nodejs.

This is a possible workaround for non-HAM radio people:

sudo ln -s /usr/bin/nodejs /usr/bin/node

**Comment by nomadster** [comment]
Same issue here: http://pastebin.com/shGfNBdB
I'm on
```
MacOSX 10.10.2
nodejs-v0.11.16
$ which node
/usr/local/bin/node
```

I had recently switched from `v0.11.14` to `v0.11.16` using `n`

**Comment by jw84** [comment]
Same problem as nomadster

**Comment by SlightlyCyborg** [comment]
Same problem. Not with sqlite but with opencv. node-pre-gyp is the issue

<pre><code>node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/collinbell/Programs/auto-catalog/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/collinbell/Programs/auto-catalog/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/collinbell/Programs/auto-catalog/node_modules/opencv
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok </pre></code>

**Comment by springmeyer** [comment]
@SlightlyCyborg that error contains nothing helpful. please create a new issue with a full error report otherwise I cannot help you.

**Comment by SlightlyCyborg** [comment]
I fixed it. On mac brew does not install cmake for some packages. node-pre-gyp needs cmake. All I had to do was install cmake

**Comment by Angristan** [comment]
Same probleme, nodejs 5.0.0 on Debian 8

**Comment by kapouer** [comment]
Put `build-from-source=true` in your npmrc and rebuild from source instead of using binary (typically what you want on debian).

**Comment by Angristan** [comment]
Where is npmrc ?

**Comment by kapouer** [comment]
In debian it is read-only in /usr/share/npm/npmrc, root read-write in /etc/npmrc, or user read-write in ~/.npmrc

**Comment by Angristan** [comment]
I got none of these.

**Comment by kapouer** [comment]
@Angristan create ~/.npmrc !

**Comment by Angristan** [comment]
ok, and do I have to rebuild ?

**Comment by Angristan** [comment]
> Put build-from-source=true in your npmrc and rebuild from source instead of using binary (typically what you want on debian).

What do I have to rebuild ?

**Comment by kapouer** [comment]
@Angristan aren't we talking about sqlite3 ?

**Comment by Angristan** [comment]
@kapouer Yep, but I have to rebuild it with/from what ?

**Comment by kapouer** [comment]
Let's say you're on debian and want to install node-sqlite3 npm module, but you don't want node-pre-gyp downloading binaries.
1. you put `build-from-source=true` in your ~/.npmrc
2. npm install sqlite3

Of course, you will need gcc toolchain and sqlite3 dev dependencies installed.
`apt-get install build-essential` for a start.

**Comment by Angristan** [comment]
That's what I have done before : no problem during the installation.
But I still have a problem when doing `npm install --production` for Ghost.

**Comment by marcellodesales** [comment]
Started getting this error on RHEL7 while installing node-inspector

**Comment by shemul** [comment]
same problem ..still unsolved
