### ISSUE TITLE
Is it possible to set sqlite3_busy_timeout?

### ISSUE THREAD

**Issue by jakeorr** [mapbox/node-sqlite3#273]
Hey, great module! I'm using multiple processes to write to an sqlite DB and am running into a busy error:

`{ [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }`

I would like to have the module wait more than the default 1 second before failing in this case. I see the `sqlite3_busy_timeout` variable in the src/database.cc code, but I'm unable to tell if it's exposed through the node module. Is it possible to set this busy timeout option? If so, how?

Thanks for the help!

**Comment by 1993hzw** [comment]
thanks!!

**Comment by Mithgol** [comment]
This method should probably be documented in the wiki.

**Comment by fritx** [comment]
Is it possible to set busyTimeout via new Database constructor?

**Comment by tmcw** [comment]
[Database#configure](https://github.com/mapbox/node-sqlite3/wiki/API#databaseconfigureoption-value) is now documented.

@fritx no, busyTimeout must be set on a database instance.

**Comment by kalyansagi** [comment]
I want to set this timeout in my java project. I see `db.configure("busyTimeout", 2000)` works but where exactly do we need to implement this? I am not clear on how this can be set in java programs. Any leads?

**Comment by wujichao** [comment]
> I want to set this timeout in my java project. I see `db.configure("busyTimeout", 2000)` works but where exactly do we need to implement this? I am not clear on how this can be set in java programs. Any leads? @kkaefer

in source code:
void Database::SetBusyTimeout(Baton* baton) {
    assert(baton->db->open);
    assert(baton->db->_handle);

    // Abuse the status field for passing the timeout.
    sqlite3_busy_timeout(baton->db->_handle, baton->status);

    delete baton;
}
