### ISSUE TITLE
no windows 8.1 x64 binary?

### ISSUE THREAD

**Issue by Pomax** [mapbox/node-sqlite3#345]
I usually work on win7 x64 machines, but just got a new win 8.1 x64 machine to do some dev work on as  well, and it seems that it doesn't see a valid precompiled binary available, falling back to node-gyp, which is the worst drama on windows and I'd love to avoid at any and all cost =)

**Comment by ErisDS** [comment]
Someone trying to install Ghost is having a similar issue with Windows 8.1 - I'm not sure why it's falling back to build, but here's the output from 

`npm install sqlite3 --loglevel=info` - this is sqlite@3.0.8 as we've not upgraded yet 

https://gist.github.com/lukewatts/e5c5a8adbdb06de53d5b

Any ideas why this might be happening? Thanks.

**Comment by Mithgol** [comment]
I've just experienced a similar issue, i.e. couldn't get the newest build (v3.1.1) for 64-bit Windows 7 with Node 5 (`/lib/binding/node-v47-win32-x64\node_sqlite3.node`).
