### ISSUE TITLE
Recursive requests

### ISSUE THREAD

**Issue by wizzhard** [mapbox/node-sqlite3#349]
Hello,

I am currently attempting to recursively launch parallel requests but I don't see anything to synchronize on the end of all requests. Is there any mecanism that would allow me to do that ?

may be something with this form, or another.

    var recursive = function(id, level)
    {
        db.all("SELECT * FROM table WHERE dependency_id==?", [id], function(err, rows)
        {
            for(var i = 0 ; i < rows.length ; i++)
                recursive(rows[i].id, level+1);
				
            db.run("DELETE FROM anotherTable WHERE id==?", [id], function(err)
            {
                if(level==0)
                {
                    while(!synched)
			yield;

                    res.render('ajax/action_response', {'ejsparams':ejsparams});
                }
            });
        });
    }
		
    recursive(an_id, 0);

**Comment by silkentrance** [comment]
Why don't you just use a sub select as in

```
DELETE FROM anotherTable where id IN (SELECT id FROM table WHERE dependency_id = ?)
```

That should be faster than iterating over all rows and deleting everything separately.

Another approach to this would be to iterated over all rows, collect all ids in an array and then

```
var ids = [];
for ...
   ids.push(rows[i].id);

DELETE FROM anotherTable WHERE id IN ?
```

**Comment by tmcw** [comment]
Looks like this is resolved; async queues and subqueries are both good solutions to this problem.
