### ISSUE TITLE
"dot" commands don't work

### ISSUE THREAD

**Issue by lancecarlson** [mapbox/node-sqlite3#351]
I'm not sure how you plan on supporting this but non of the "dot" commands work when I try to use .run or .exec. I'm trying to run stuff like this:

```
.mode csv
.headers on
.import MASTER.CSV master
```

When I ran anything with a dot I get this error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SQLITE_ERROR: near ".": syntax error
```

Assuming at the moment that input can only be SQL queries right now. Any ideas?

**Comment by stevage** [comment]
Chiming in here 3 years later :) 

`csv-parse` is really slow for big CSV files (eg, >1m rows). My particular use case is:

- load large table
- generate a lot of queries to write subsets of the data to individual CSV files

So these don't work:

1. csv-parse (too slow)
2. node-sqlite3 (can't use CSV mode)
3. Using command line sqlite3 (need to script commands)

I guess my workaround will to generate a bunch of commands and pipe them to the command line util.

**Comment by bobOnGitHub** [comment]
https://www.npmjs.com/package/babyparse

**Comment by mejl** [comment]
.load is not working for me.
