### ISSUE TITLE
Segmentation Fault Under Node v0.11.14

### ISSUE THREAD

**Issue by senditu** [mapbox/node-sqlite3#352]
I'm running into a segfault under ArchLinux x64 (3.16.3-1-ARCH). I downloaded a fresh copy of Node from the Node dist site (http://nodejs.org/dist/v0.11.14/) and proceeded to do an ```npm install``` for a sqlite-based website app that works fine under v0.11 on Windows x64. When running the app I get a segfault. I tracked down the seqfault to the initial load of the dbs in my app (the are no other lines invoking the sqlite3 library before these lines)... 

The following code is in LiveScript.

```LiveScript
log 'hihi'
db = new sqlite3.Database('db.sqlite')
log 'hihi2'
ip-db = new sqlite3.Database('ipdb.sqlite')
log 'byebye'
```

Here's the output:
```
$ ~/bin/lsc scrape.ls
[3:33:05 pm] hihi
[1]    3110 segmentation fault (core dumped)  ~/bin/lsc scrape.ls

Oct 10 15:33:05 m kernel: node[3116]: segfault at b6d168 ip 00007f365980c142 sp 00007f365b231e30 error 7
Oct 10 15:33:05 m kernel: node[3117]: segfault at b6d168 ip 00007f365980c142 sp 00007f365aa30e30 error 7
Oct 10 15:33:05 m kernel:  in node_sqlite3.node[7f3659718000+112000]
Oct 10 15:33:05 m kernel:  in node_sqlite3.node[7f3659718000+112000]
Oct 10 15:33:26 m systemd-coredump[3119]: Process 3110 (node) of user 1000 dumped core.
```

The application runs fine under Windows 8.1 x64 with Node v0.11.14. It also runs fine under ArchLinux x64 with Node v0.10.32. Just not Linux with v0.11.14, it seems. I also tried adding the git repository directly into package.json (```"sqlite3": "git://github.com/developmentseed/node-sqlite3.git"```) with no effect. I'd really like to use sqlite3 with Node v0.11.14, if possible. Does anyone know what could be going on here?

Thank you!

**Comment by ErisDS** [comment]
Closing as I believe this was a version incompatibility issue with unstable node, and this should no longer be a problem.
