### ISSUE TITLE
node.h: No such file or directory

### ISSUE THREAD

**Issue by brilvio** [mapbox/node-sqlite3#367]
CXX(target) Release/obj.target/node_sqlite3/src/database.o 
../src/database.cc:2:18: fatal error: node.h: No such file or directory

I have this problem trying to install sqlite3 on Debian Wheezy on a Beaglebone Black rev C.
I installed others packages without a problem.

**Comment by tmcw** [comment]
Closing; stale - reopen if you can confirm on current node-sqlite3 and Debian.
