### ISSUE TITLE
installing node-sqlite3 on a synology

### ISSUE THREAD

**Issue by Henri70** [mapbox/node-sqlite3#368]
Hi, 
I'm trying to install node-sqlite3 on my DS109 synology in order to install Ghost. When I try to build from source, it seems not to be able to find CC. But I installed gcc and make. Have someone an idea ? Here's the log : 
DiskStation> npm install sqlite3 --build-from-source=sqlite3
/
> sqlite3@3.0.4 install /node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory `/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o
make: cc: Command not found
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o] Error 127
make: Leaving directory `/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32.12
gyp ERR! command "/volume1/@appstore/node/bin/node" "/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/node_modules/sqlite3/lib/binding/node-v11-linux-arm" "--module=/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-v11-linux-arm.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz"
gyp ERR! cwd /node_modules/sqlite3
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/volume1/@appstore/node/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/node_modules/sqlite3/lib/binding/node-v11-linux-arm --module=/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:756:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
node-pre-gyp ERR! System Linux 2.6.32.12
node-pre-gyp ERR! command "node" "/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.31
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/volume1/@appstore/node/bin/node /node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/node_modules/sqlite3/lib/binding/node-v11-linux-arm --module=/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz' (1)
npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32.12
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "sqlite3" "--build-from-source=sqlite3"
npm ERR! cwd /
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

**Comment by ErisDS** [comment]
Closing this as it looks like it was solved.
