### ISSUE TITLE
Error:SQLITE_CANTOPEN:unable to open database file

### ISSUE THREAD

**Issue by shulianghe** [mapbox/node-sqlite3#371]
when i do something like clean some trash in my application,at the same time i exec :
var db = new sqlite3.Database('patch');
    var result;
    console.log('getKernalPatchLastRefreshTime');
    db.get("select date from KernalPatch order by date desc limit 0, 1", function(error,row){
        console.log('getKernalPatchLastRefreshTime'+error);
        if (error) {
            callback({error: error});
            return;
        }
        if(row&&row.date)result=row.date;
        callback(result);
    });
    db.close();

it stoped before db.get,but when i exec that codes straight forward it works well.what's the problem with me?

**Comment by tmcw** [comment]
Feel to open a report if you can specify this error in more detail and make it clear that the database isn't, for instance, absent or corrupted. Closing because this is not debuggable in its current form.
