### ISSUE TITLE
backpressure on .each

### ISSUE THREAD

**Issue by maxogden** [mapbox/node-sqlite3#375]
me and @mafintosh noticed that doing a .each around a potentially large SELECT doesn't have any read backpressure. for large datasets + queries it would be nice if .each was implemented as a stream that had a next callback for each iterable

it could probably go in here: https://github.com/mapbox/node-sqlite3/blob/master/src/statement.cc#L656

**Comment by Downchuck** [comment]
Is there any available method for scrolling through large selects? For example, calling "get" multiple times after running a query.

**Comment by tracker1** [comment]
Probably not much help, but here's the cursor implementation for the python client... 

https://github.com/ghaering/pysqlite/blob/master/src/cursor.c

**Comment by rogierschouten** [comment]
+1.   Also, an alternative to streams could be to optionally return a Promise from the callback to .each(), only giving the next callback when the previous one has its promise resolved.

**Comment by tmcw** [comment]
Moving to https://github.com/mapbox/node-sqlite3/issues/686 which proposes a next() callback, which seems like the most immediate way to get this done.
