### ISSUE TITLE
Installation Error    Seek help

### ISSUE THREAD

**Issue by bujingkua** [mapbox/node-sqlite3#384]
The problem has been solved, thank you for your attention. Thank you
Damn GFW

**Comment by BergWerkGIS** [comment]
@bujingkua how did you try to install?
Did you use `npm install sqlite3`?
If the error persists, could you share the whole log, what Windows version you are using (e.g.Windows 7 64bit) and what node architecture (32/64bit)?

I works for me without a problem: W7 64bit, node 0.10.33 32bit.

**Comment by bujingkua** [comment]
@BergWerkGIS   Sorry, back to you so late. My problem here is the network (GFW). Sorry, forgot to turn vpn, your product is very good。
