### ISSUE TITLE
node-sqlite3 failing on IOJS

### ISSUE THREAD

**Issue by c0debreaker** [mapbox/node-sqlite3#385]
Today I tried using IOJS. I spoke to few folks at #iojs today in irc. Someone told me  to inform you that NaN(https://github.com/rvagg/nan) 1.6 supports iojs now.

I got the error below after executing it:
```
module.js:324
    throw err;
          ^
Error: Cannot find module '/Users/user01/chartservice/node_modules/sqlite3/lib/binding/node-v42-darwin-x64/node_sqlite3.node'
```

**Comment by kenrick** [comment]
Got this issue as well, its downloading the wrong binding binary or looking in the wrong place for it.

**Comment by springmeyer** [comment]
We'll get this working soon. At least these things need to be done:

  - Upgrade to latest nan 1.5.x, fix any compiler errors
  - Package binaries, new tag of node-sqlite3
  - Binaries will not be installable with iojs until https://github.com/iojs/io.js/issues/402 is fixed because modules like node-sqlite3 that use node-pre-gyp to package binaries require https access to AWS S3 (refs https://github.com/iojs/io.js/issues/456 and https://github.com/mapbox/node-pre-gyp/issues/135).

**Comment by c0debreaker** [comment]
Thanks a lot @springmeyer ! :)

**Comment by Mithgol** [comment]
Node-webkit has been renamed to nw.js and its newest versions are based on io.js as well.

The more the merrier, but Windows XP is no longer supported because of iojs/io.js#374.

**Comment by springmeyer** [comment]
@Mithgol - thanks for the details. Sounds like that will need some time to resolve itself. I propose I make a new tag (v3.0.4) of node-sqlite3 today that supports node v0.10.x, v0.11.14, and iojs v1.0.2 and worry about webkit/nw.js support in the coming weeks?

**Comment by Mithgol** [comment]
Okay, though I have a couple of thoughts about it:

* Currently npm says that version 3.0.4 is already published (2 months ago), so the tag has a reason to be somewhat greater (to indicate that it contains today's changes).

* Yet another (3.0.5?…) intermediate version of the package (without today's changes) might also be somewhat helpful for people that needed just the `ForceSet()` changes from #369 (these changes might fix #382 and similar issues) but without iojs-related stuff.

**Comment by coolaj86** [comment]
What's the work around? Where's the url to the node v0.11 bins so I can just copy them into the directory myself?

**Comment by sdepold** [comment]
You will have to change the engines selector in the [package.json](https://github.com/mapbox/node-sqlite3/blob/master/package.json#L50) as well. It won't allow you to run sqlite3 on `1.0.x` otherwise.

**Comment by roblabla** [comment]
Is there a point in having this engine restriction ? Seems more trouble than it's worth, and if nodejs ever comes out of 1.0 in an incompatible way to iojs, it will not even protect anything...

After removing the engine restriction entirely, it seems the master branch of node-sqlite3 happily compiles for iojs

**Comment by KenanSulayman** [comment]
`npm i --force mapbox/node-sqlite3`

**Comment by hmalphettes** [comment]
sqlite3@3.0.5 installs and works out of the box with iojs-0.1.2
This issue can be closed.

**Comment by Mithgol** [comment]
Okay, closed.

**Comment by EgoAleSum** [comment]
not working with iojs-2.0.0

**Comment by KenanSulayman** [comment]
@EgoAleSum Please create an issue for that. This issue was about supporting io.js 1.X series; 2.X sports an updated V8 engine and breaks binary support, thus needs a new nan (1.8.4) and / or a variety of modifications throughout the codebase.
