### ISSUE TITLE
Drop support for providing node v0.11.x binaries

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-sqlite3#389]
I propose not providing binaries (via node-pre-gyp) for node v0.11.x because:

  - doing so has been a source of great pain (each v0.11.x version released has brought unpredicatable changes) - refs #352
  - due to the lack of ABI promised we've needed to build binaries for each point release, which gets out of control
  - iojs, in my mind, is the new v0.11.x release we've been hoping for and support for io.js is coming along nicely - refs #385

Node-sqlite3 would continue working against node v0.11.x (whatever the nan version we are using targets) for source compiles. But not binaries: so users would need a compiler and python around again. But anyone running the unstable node v0.11.x should unless they downloaded it without realizing it is the unstable-you-should-not-use-this-release.

/cc @jaswilli

**Comment by jaswilli** [comment]
I support this plan, and agree completely with the sentiment.

If there's ever to be a node 0.12/1.0, tracking io.js is probably a more useful predictor of what it'll be than node 0.11.x.

**Comment by springmeyer** [comment]
done here, node-sqlite3 3.0.5 will support node v0.12.x and not 0.11.x
