### ISSUE TITLE
Support building io.js binaries on appveyor and travis

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-sqlite3#390]
To fully drop support for node v0.11.x binaries (#389) we'll need to get io.js builds/binary publishing going on travis and appveyor.

- [x] nvm support for io.js - https://github.com/creationix/nvm/issues/590, or ditch nvm and use `nave` https://github.com/isaacs/nave/commit/e0b9a96ae79f64f7674a4195d8d1a89ba7df3881
- [x] Come up with a good approach on appveyor - http://help.appveyor.com/discussions/questions/882-iojs-support

/cc @FeodorFitsner

**Comment by am11** [comment]
Cross referencing: https://github.com/appveyor/ci/issues/113.

**Comment by am11** [comment]
AppVeryor support [has landed](http://www.appveyor.com/docs/lang/nodejs-iojs)! :)

**Comment by Mithgol** [comment]
We also have nvm support from creationix/nvm#590.

Some caution is necessary because the binary's name is `iojs` instead of `node`.

**Comment by springmeyer** [comment]
this is now working - no longer building for node v0.11.x and instead targeting node v0.12.x - followups at #404
