### ISSUE TITLE
Get result in array ?

### ISSUE THREAD

**Issue by guillaume23** [mapbox/node-sqlite3#391]
Hi everyone, 
I would like to get an array of result but my var is undefined
```javascript


function test(){
   var array = [];
   db.each("SELECT rowid AS id, thing FROM Stuff", function(err, row) {
      array.push(row.id + ": " + row.thing);
    }, function(err, rowCount){
      return array;
    });
}
var call = test();
console.log(call);
// undefined

```

I don't understand why ? 
I've tried with a call back but don't works.
Sorry for my bad english i'm french.
Thanks !

**Comment by kkaefer** [comment]
Node.js works with asynchronous callbacks, meaning that the call to test() doesn't return the result. Instead, you'll have to continue your code flow in the second callback of `db.each()`. Alternatively, you can also use `db.all()`, which does all of that for you in a more efficient way.
