### ISSUE TITLE
order didnot work

### ISSUE THREAD

**Issue by zscorpio** [mapbox/node-sqlite3#392]
```js
		db.all("SELECT * FROM xx WHERE a=? AND b=? ORDER BY ? LIMIT ?;",[35,2,'msgId as',10],function(err,data){
			data.forEach(function (row) {
			    console.log(row.id + ": " + row.info);
			});
			if(callback){
				callback(data);
			}
		});

when I run this ,it didnot show me  the error
and even I changed the order,the result didnot change?
Am I wrong?

**Comment by Mithgol** [comment]
As far as I recall, SQLite supports substitutions in values in `WHERE`, but neither in `ORDER BY` nor in `LIMIT` clause.

**Comment by ColonelThirtyTwo** [comment]
Query parameters aren't simple string substitutions; they are placeholder _values_. Your query's order by clause is equivalent to `ORDER BY 'msgId as'`, i.e. ordering by a constant string. Since the value is the same for all rows, no ordering takes place.
