### ISSUE TITLE
Failed to build sqlite3 in Win7

### ISSUE THREAD

**Issue by speedneeder** [mapbox/node-sqlite3#396]
I am a beginner of programming.
My nodejs version is v0.10.35,And I have visual studio 2010 on my computer.

I try to bulid sqlite3 on my computer by:
```
npm install -g sqlite3
```
But it's failed.I find some issues of this problem, just like https://github.com/mapbox/node-sqlite3/issues/106 and try the ways but failed.

this is my log file:   http://tny.cz/d7fa9de7

**Comment by speedneeder** [comment]
Perhaps I need to install python on my computer?

**Comment by silkentrance** [comment]
Do not follow the above link. After visiting it, a pop up came up and after that I was not able to revisit the github server until I restarted Safari.

However, the error is not related to sqlite3 at all:

```
error Error: shasum check failed for C:\Users\likebin\AppData\Local\Temp\npm-4676-2wTcE5Mh\registry.npmjs.org\sqlite3\-\sqlite3-3.0.4.tgz
47 error Expected: ebee3525aac5e318074647bf4e3577b33b600b73
47 error Actual:   e7be7f4ec43c890eb247b6e3f45abc59b71e079a
```

@speedneeder And please, next time use gist to prevent us from getting these unwanted popus and commercial ads

**Comment by speedneeder** [comment]
@silkentrance 
I'm sorry , I am a beginner of programming and almost know nothing about github, so I just find a website to paste my log file casually.

Next time I will try gist. :)

So the reason of this problem is I have some error of the file from npmjs.org? 

anyhow,thanks for your reply:)

**Comment by silkentrance** [comment]
Either there was an error during transmission of the file or the npm tool calculated an invalid checksum for that file upon publishing it.

**Comment by springmeyer** [comment]
The error `shasum check failed for` is usually do to a network problem and it can be fixed by waiting a few minutes, running `npm cache clean`, and then trying to install node-sqlite3 again.
