### ISSUE TITLE
Ghost installation fails at sqlite3

### ISSUE THREAD

**Issue by itxchy** [mapbox/node-sqlite3#402]
I was trying to install Ghost in Vagrant running Ubuntu 14.04  when this happened:

npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/ghost/npm-debug.log

Here's the npm debug log:

https://gist.github.com/itxchy/23ae40d7ea0255fcc4a1

I'm very new to development. If I'm missing something simple-stupid, let me know.

**Comment by itxchy** [comment]
After many hours of fruitless poking and prodding, I got everything to install just fine. In my case, it was Node v0.12.0. I used a handy npm package called n (http://davidwalsh.name/upgrade-nodejs) to downgrade Node to v0.10.35 and everything installed without a hitch. The new version of Node was just released, so that must of been culprit. Lesson learned.

Hope this helps anyone with similar issues!

**Comment by springmeyer** [comment]
Yes, node 0.12.0 was just released and was not supported when you tried. However I've just tagged a new node-sqlite3 release "3.0.5" that will work once published (in a few minutes).

**Comment by itxchy** [comment]
Great! Thanks for clearing that up.
