### ISSUE TITLE
Node 0.12.x support

### ISSUE THREAD

**Issue by gnarf** [mapbox/node-sqlite3#406]
The binary shipped doesn't work with stable node v 0.12.0 - my colleague on windows couldn't get it to install under 0.12 at all...

Here was my output from trying to install it on 0.12 on linux:

```
npm install sqlite3
-
> sqlite3@3.0.5 install /test/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: (redacted)/.nvm/versions/node/v0.12.0/bin/node --eval require('/test/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /test/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
```

This eventually works after compiling it.

**Comment by springmeyer** [comment]
> Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14'

The binaries for linux work on modern linux distros like >= Ubuntu Precise and RHEL >= 7 that have a recent libc version. So, what linux version are you using?

> my colleague on windows couldn't get it to install under 0.12 at all...

Can you have your colleague create a new ticket with detailed error message?

**Comment by gnarf** [comment]
Debian GNU/Linux 7.6 (wheezy) -- he's already reverted to 0.10.x and got it working, going to ask him to try and reproduce, but will close for now.
