### ISSUE TITLE
Got access denied accessing hosted_tarball url while building for nodewebkit!!!

### ISSUE THREAD

**Issue by blankland** [mapbox/node-sqlite3#407]
Got access denied accessing hosted_tarball url while building for nodewebkit. Doesn't work no matter opening in browser or using a proxy.
here's that url with problem: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-webkit-v0.12.0-linux-ia32.tar.gz

(every time, everty time I build this thing something goes wrong.)

**Comment by springmeyer** [comment]
@blankland node-webkit v0.11.x and greater is not currently supported. You'll need to stick to node-webkit 0.10.x for the time being.
