### ISSUE TITLE
Install fails (node-waf not found)

### ISSUE THREAD

**Issue by Yatterman** [mapbox/node-sqlite3#410]
Hi,
I don't know if this is the right place to ask for help, but this thing is driving me nuts.
OS is Linux Mint 17 x64, installed nodejs, node-legacy, node-gyp, sqlite3, libsqlite3-dev and when I do
sudo npm install sqlite -g
[sudo] password for ****: 
npm http GET https://registry.npmjs.org/sqlite
npm http 304 https://registry.npmjs.org/sqlite

> sqlite@1.0.4 preinstall /usr/local/lib/node_modules/sqlite
> node-waf configure build

sh: 1: node-waf: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0

The same happens if I try to install locally
sudo npm install sqlite
npm WARN package.json nw-demo@0.1.0 No repository field.
npm WARN package.json nw-demo@0.1.0 No README data
npm http GET https://registry.npmjs.org/sqlite
npm http 304 https://registry.npmjs.org/sqlite

> sqlite@1.0.4 preinstall /home/ikki/Code/CTA/phaser_extend/nw/node_modules/sqlite
> node-waf configure build

sh: 1: node-waf: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0

I'm pretty new to node, this is my first attempt at installing a module (which I'm going to use with nwjs, BTW) so I might be missing something.
I also tried to install node-sqlite3 from Linux MInt repository (which I guess stands for a global installation), but even after this, the local installation still fails.
Every search for this kind of error lead to suggestion about the Debian/Ubuntu problem about node being named nodejs, but I installed node-legacy as suggested to no avail.
I even tried to create a ln -s from node-gyp to node-waf and the install still fails.
I tried looking at the suggested README.Debian file, but the content is either cryptic to me or not useful to find a solution on my own.
Some of the answers I found on the net suggested it might be a bug in the package I'm trying to install, so, here I am.
Could you please help?
Thank you.

**Comment by Yatterman** [comment]
Forgot to mention
node -v
v0.10.25
node-gyp -v
v1.0.2

**Comment by Mithgol** [comment]
You seem to be installing some other npm package.

Please try `npm install sqlite3` instead of `npm install sqlite`.

**Comment by Yatterman** [comment]
Now I feel stupid T__T
Thank you, that solved it (apparently my copy/paste left out a single character and I didn't notice it... lesson for the future)

**Comment by Mithgol** [comment]
Good.
