### ISSUE TITLE
Failed to build manually - can't find sqlite3.h (even with --sqlite=/usr/local)

### ISSUE THREAD

**Issue by coolaj86** [mapbox/node-sqlite3#413]
**Update**: Workaround available at https://github.com/mapbox/node-sqlite3/issues/414

Here's what I've done:

```bash
npm install node-gyp -g
npm install -g nan

git clone git@github.com:mapbox/node-sqlite3.git
pushd node-sqlite3

npm install nan

node-gyp clean
node-gyp configure --sqlite=/usr/local --sqlite_libname=sqlcipher --module_name=node_sqlite3 --module_path=$(pwd)/lib/binding/node-v10-linux-arm
rsync -av /usr/local/include/sqlcipher/sqlite3* src/

node-gyp build
```

Not sure what I'm doing wrong here, but I just can't get it to find sqlite3.h

**Comment by springmeyer** [comment]
calling node-gyp directly is not supported as mentioned at https://github.com/mapbox/node-sqlite3/issues/416#issuecomment-75415682
