### ISSUE TITLE
module_name and module_path won't accept defaults AND ignore specific values

### ISSUE THREAD

**Issue by coolaj86** [mapbox/node-sqlite3#415]
**Update**: Workaround available at https://github.com/mapbox/node-sqlite3/issues/414

As mentioned in #412, I built with the option `--module_path=$(pwd)/lib/binding/node-v10-linux-arm` because if I left out `module_path` I got an error message.

Even though the file built to `lib/binding/node-v10-linux-arm/node_sqlite3.node`, when I required the module it still complained that it was looking for it in `lib/binding/node-v11-linux-arm/` (and I know I'm running v0.10.36).

Side Note: I did have iojs 1.2 installed, but I installed v0.10.36 over it (because I'm stuck between buggy versions of this and that - some things needing v0.11 / v0.12 / v1.2 while others need v0.10 - and v0.10.36 requires the fewest workarounds).

**Comment by springmeyer** [comment]
calling node-gyp directly is not supported as mentioned at https://github.com/mapbox/node-sqlite3/issues/416#issuecomment-75415682
