### ISSUE TITLE
Documentation for manual build incorrect

### ISSUE THREAD

**Issue by coolaj86** [mapbox/node-sqlite3#416]
In addition to the issues linked at **Update**: Workaround available at https://github.com/mapbox/node-sqlite3/issues/414

The documentation in the readme is also incorrect. I don't know how incorrect, but I at least know that it would be `node-gyp configure --some-option`, not `node-gyp --some-option` (throws error).

Once I understand what's going on with the options being ignored I'll be happy to update the README.

**Comment by springmeyer** [comment]
Calling 'node-gyp' directly is not supported. This module uses node-pre-gyp instead.

**Comment by coolaj86** [comment]
I'm not educated enough on the matter. Tell me more. Or link me to a good resource.

**Comment by Mithgol** [comment]
@coolaj86 Link: https://github.com/mapbox/node-pre-gyp/
