### ISSUE TITLE
Compile error on Debian stable

### ISSUE THREAD

**Issue by JoKeyser** [mapbox/node-sqlite3#420]
(I'd like to install `sharelatex`, however that fails at compilation of the `clsi` module.)
I'm using a self-compiled version of `node v0.12.0`,  `node-gyp v1.0.2` and `npm 2.6.0`.
Is it my fault, or can I help with more tests and logs?

`npm install sqlite3`
<pre>
npm WARN package.json js@0.1.0 No repository field.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecation Per-package engineStrict will no longer be used
npm WARN deprecation in upcoming versions of npm. Use the config
npm WARN deprecation setting `engine-strict` instead.
npm WARN deprecated set-immediate@0.1.1: Use `setimmediate` instead

> sqlite3@2.2.7 install /usr/local/src/sharelatex/clsi/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/bin/node --eval require('/usr/local/src/sharelatex/clsi/node_modules/sqlite3/lib/binding/node-v14-linux-ia32/node_sqlite3.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /usr/local/src/sharelatex/clsi/node_modules/sqlite3/lib/binding/node-v14-linux-ia32/node_sqlite3.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)

node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile 
child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp"
^[[Achild_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/usr/local/src/sharelatex/clsi/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080500/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080500/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc: In static member function ‘static void node_sqlite3::Database::New(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/database.cc:134:71: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::String>, v8::PropertyAttribute)’
../src/database.cc:134:71: note: candidates are:
In file included from /usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/database.cc:2:
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
../src/database.cc:135:69: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Integer>, v8::PropertyAttribute)’
../src/database.cc:135:69: note: candidates are:
In file included from /usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/src/node.h:61:0,
                 from ../src/database.cc:2:
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: bool v8::Object::Set(v8::Handle<v8::Value>, v8::Handle<v8::Value>)
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note:   candidate expects 2 arguments, 3 provided
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: bool v8::Object::Set(uint32_t, v8::Handle<v8::Value>)
/usr/local/src/sharelatex/clsi/node_modules/sqlite3/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note:   candidate expects 2 arguments, 3 provided
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
make: Leaving directory `/usr/local/src/sharelatex/clsi/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=2.2.7" "--major=2" "--minor=2" "--patch=7" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=ia32" "--target_arch=ia32" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/local/src/sharelatex/clsi/node_modules/sqlite3/lib/binding/node-v14-linux-ia32" "--remote_path=./sqlite3/v2.2.7/" "--package_name=node-v14-linux-ia32.tar.gz" "--staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz"
gyp ERR! cwd /usr/local/src/sharelatex/clsi/node_modules/sqlite3
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/src/sharelatex/clsi/node_modules/sqlite3/lib/binding/node-v14-linux-ia32 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-ia32.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/src/sharelatex/clsi/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Linux 3.2.0-4-686-pae
node-pre-gyp ERR! command "node" "/usr/local/src/sharelatex/clsi/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/src/sharelatex/clsi/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=2.2.7 --major=2 --minor=2 --patch=7 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/local/src/sharelatex/clsi/node_modules/sqlite3/lib/binding/node-v14-linux-ia32 --remote_path=./sqlite3/v2.2.7/ --package_name=node-v14-linux-ia32.tar.gz --staged_tarball=build/stage/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v2.2.7/node-v14-linux-ia32.tar.gz' (1)
npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE
</pre>

**Comment by springmeyer** [comment]
You are installing `sqlite3@2.2.7`. You need at least `sqlite3@3.0.5` for node v0.12.x support.

**Comment by JoKeyser** [comment]
That fixed it, thanks! (And sorry for not looking that up.)
