### ISSUE TITLE
[object Object] when using toString() on SlowBuffer

### ISSUE THREAD

**Issue by ThucHoang** [mapbox/node-sqlite3#421]
Hi.

I'm trying to get out the data from my blob, but all I get is a [object Object] when doing it.

```
db.serialize(function() {
			db.get("SELECT data FROM FTP", function(err, row) {
				console.log(row.toString()); // => [object Object]
				var json = JSON.stringify(row); // => string with a lot of numbers (24000 in array)
});
```

How can I get the data from it? Apparently toString('utf-8') should have worked, but it doesn't for me. Anyone have the same experienced this?

**Comment by springmeyer** [comment]
To see how to work with buffers see https://nodejs.org/api/buffer.html
