### ISSUE TITLE
Failed to Install 

### ISSUE THREAD

**Issue by sgiovanni** [mapbox/node-sqlite3#425]
After updating Node and Ghost Blog to the latest versions on my mac, I received errors that stated sqlite3 dependency was missing when I tried to start Ghost. I attempted to add it using <pre>npm install sqlite3 --build-from-source</pre>
That failed as well. Here are the <a href="http://pastebin.com/JBQdFbZu" target="_blank">logs</a>.
<br>
OS: OSX Yosemite 10.10.2 
Node: v0.12.0

Thanks in advance for the help!

**Comment by springmeyer** [comment]
You need to use `node-sqlite3@3.0.5` not `3.0.4`. Also when you fix the version you will not need `--build-from-source`

**Comment by sgiovanni** [comment]
@springmeyer thanks! Unfortunately Ghost Blog is not compatible with Node v0.12.0 so that helps explain my other issues.

**Comment by springmeyer** [comment]
yes, anyone hitting this should see https://github.com/TryGhost/Ghost/issues/4240
