### ISSUE TITLE
Support Promise to replace callback

### ISSUE THREAD

**Issue by wyefei** [mapbox/node-sqlite3#427]
Promises has tons of advantages than callback. Do you guys think it's worth to put this on the road map?

**Comment by wyefei** [comment]
Bluebird is really power promise library, in case you guys decide to support Promises
https://github.com/petkaantonov/bluebird

**Comment by springmeyer** [comment]
promises are not on the roadmap. node-sqlite is mostly in maintenance mode.

**Comment by EgoAleSum** [comment]
:+1: for promises

**Comment by koistya** [comment]
Here is a Promise-based wrapper for `node-sqlite3`: https://github.com/kriasoft/sqlite

**Comment by vieks** [comment]
@koistya Nice ! Thanks.

**Comment by fritx** [comment]
Is any API difference between node-sqlite and node-sqlite3?
Is it safe to migrate?? If so, that would be great.

**Comment by koistya** [comment]
@fritx `sqlite` npm module (node-sqlite) is just a tiny wrapper (see the source code) over the `sqlite3` (node-sqlite3) library. It's intended to make it easier to write async code in a modern ES2015+ style.

**Comment by fritx** [comment]
@koistya awesome. But seems there is no API like `new Database()`?
Do I have to replace all of them to `db.open()`?

**Comment by koistya** [comment]
Yep, instead of `new Database()`, you would just do `db.open(..)`, the rest of the API is very similar to `node-sqlite3`.
