### ISSUE TITLE
Cannot install sqlite3 module.

### ISSUE THREAD

**Issue by Konstantinos76** [mapbox/node-sqlite3#428]
Hello.
I am trying to install sqlite3 module on windows.
I am receiving this at the end of the installation process:
![capture1](https://cloud.githubusercontent.com/assets/11249775/6542313/97b62cc2-c4a9-11e4-8cf8-58cc47202180.PNG)

When I am running a script containing the code below:
var sqlite3 = require('sqlite3'); to test that the module has been installed, I am receiving this error:
![capture2](https://cloud.githubusercontent.com/assets/11249775/6542327/151dffaa-c4aa-11e4-8cc0-1a4a07d9a9ff.PNG)

There is not any folder in \lib, just three files, index.js-sqlite3.js-trace.js
Working with node v.0.11.14

Also, I couldn't find an answer in this issue->https://github.com/mapbox/node-sqlite3/issues/364
which is similar to mine. Just to mension that tested npm install sqlite3 --verbose --no-rollback
but with no luck.

Would appreciate any help.

**Comment by springmeyer** [comment]
I'm not sure what is wrong however using node v0.11.14 is not recommended: I would recommend using either 0.10.x or 0.12.x (the stable series releases).

**Comment by Konstantinos76** [comment]
v.0.10.9 doesn't help. Just tested.

**Comment by Konstantinos76** [comment]
@springmeyer executing node-pre-gyp install --fallback-to-build-

I am taking these errors:
![capture](https://cloud.githubusercontent.com/assets/11249775/6547461/16bdf620-c596-11e4-8146-7109573ec8cb.PNG)
 Do I need a binary? Need to fix my package.json file?

Thank you.

**Comment by tbranyen** [comment]
It doesn't work because Node 0.12 binaries haven't been published to S3 from what I can tell.

**Comment by springmeyer** [comment]
please do not use node v0.11.14. Instead use node v0.12.x or v0.10.x which will not have this problem.
