### ISSUE TITLE
Error: SQLITE_CANTOPEN with forever executed from shell script

### ISSUE THREAD

**Issue by jessekinsman** [mapbox/node-sqlite3#430]
Ok I know I have several things going on here so this may not be a bug. 

I am trying to get my server (Ubuntu 14.04) to start my nodejs app using crontab. However, if I use forever in crontab or any shell script, I get this error.

However, I can run this just fine from the command line. No Error. I realize this may be an Ubuntu issue or a Forever issue, but I just thought I would add it here in the case someone might recognize it.

I have set permissions to 777 on directory and database to ensure it is not a permissions issue

Here is the shell I am running
```
#!/bin/sh
export HOME=/home/myHome
export NODE_BIN_DIR=/usr/bin
export NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export APP_PATH=/home/myHome/nodeServ/lServer/

PATH=$NODE_BIN_DIR:$NODE_PATH:$APP_PATH:$PATH
echo $PATH
cd $HOME/nodeServ/lServer/
/usr/bin/forever start -c /usr/bin/nodejs /home/myHome/nodeServ/lServer/server.js 1337
```

I get this error
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SQLITE_CANTOPEN: unable to open database file
```

However, if I run this from the command line
```
/usr/bin/forever start -c /usr/bin/nodejs /home/myHome/nodeServ/lServer/server.js 1337
```
No errors

**Comment by springmeyer** [comment]
It might also be an issue with the currently working directory when run from a cron. Are you using an absolute path to the sqlite.db you are trying to open?

But yeah, overall this is not a node-sqlite issue, so I'll close. Hope you can resolve this!
