### ISSUE TITLE
Is this.lastID on db.run atomic?

### ISSUE THREAD

**Issue by hahamed** [mapbox/node-sqlite3#431]
Hello, on a single database connection for concurrent inserts, is db.run stable?
Does this.lastID return right value?
thanks.

**Comment by kkaefer** [comment]
The [SQLite reference](https://www.sqlite.org/c3ref/last_insert_rowid.html) explains this:

> If a separate thread performs a new INSERT on the same database connection while the sqlite3_last_insert_rowid() function is running and thus changes the last insert rowid, then the value returned by sqlite3_last_insert_rowid() is unpredictable and might not equal either the old or the new last insert rowid.

**Comment by hahamed** [comment]
Thank you @kkaefer.
I use node.js framework for serve clients. i did not understand: does concurrent inserts on my single node.js server (one http request) mean threads?
