### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by rrs120486** [mapbox/node-sqlite3#433]
I added dependency sqlite3 3.0.5 to my node app but it fails with below error.

 Possibly unhandled Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by cronus/software/service_nodes/installed-packages/cronus/scripts/node_modules/sqlite3/lib/node_sqlite3.node)

I am using RedHatEnterpriseServer Release: 5.4. Is there any older version of sqlite3 which can run without this error?

Also by any chance is pure js version will be available for this?

**Comment by bnoordhuis** [comment]
I'm seeing the same issue.  It looks like it's just the memcpy symbol:
 
```
$ nm lib/binding/node-v43-linux-x64/node_sqlite3.node | grep GLIBC_2.14
                 U memcpy@@GLIBC_2.14
```

Perhaps a strategically placed .symver directive can help work around that?

```c
#ifdef __GLIBC__
__asm__ (".symver memcpy, memcpy@GLIBC_2.2.5");
#endif
```

**Comment by springmeyer** [comment]
@bnoordhuis - thanks for helping with this! And I see you found my failed previous effort at this (the https://github.com/mapbox/node-sqlite3/blob/master/src/gcc-preinclude.h). I was not able to get it working and that is the background for giving up over at https://github.com/mapbox/node-sqlite3/issues/244#issuecomment-76689979. Its been too long now to recall what did not work previously, but I presume you've confirmed that this fixes things on your system? Out of curiosity what operating system did you hit this on?

**Comment by bnoordhuis** [comment]
> Its been too long now to recall what did not work previously, but I presume you've confirmed that this fixes things on your system? Out of curiosity what operating system did you hit this on?

It works on my x86_64 centos 6 (glibc 2.12) system.  I got a bug report from a customer; they haven't verified it yet but I have no reason to believe it won't work, they run pretty much the exact same configuration.
