### ISSUE TITLE
Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fallback-to-build'

### ISSUE THREAD

**Issue by patrioticcow** [mapbox/node-sqlite3#434]
hello,

i try to run `npm install -g strongloop`

and i get

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"     "--build-from-source" "--runtime=node-webkit" "--
    target_arch=ia32" "--target=$(NODE_WEBKIT_VERSION)"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the sqlite3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sqlite3
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\Work\thrdPlaceDev\npm-debug.log

any ideas?

i have Python27, Visual Studio 2013, node-gyp and more, installed

same error if i run: `npm install sqlite3 --build-from-source=sqlite3`

**Comment by mrminecart** [comment]
I am getting the same issue.

Ubuntu 14.10
Node  v0.12.2  (I have tried v0.10.20)
NPM  1.4.21
Python 2.7.8

**Comment by mrminecart** [comment]
```
$ sudo npm install -g db-migrate
npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4
 
> kerberos@0.0.9 install /usr/local/lib/node_modules/db-migrate/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

 
> bson@0.2.21 install /usr/local/lib/node_modules/db-migrate/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> sqlite3@3.0.5 install /usr/local/lib/node_modules/db-migrate/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.5 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "db-migrate"
npm ERR! cwd /home/william
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/william/npm-debug.log
npm ERR! not ok code 0
```

**Comment by darkoverlordofdata** [comment]
I started getting this same error when I upgraded my node version 0.10.25 to 0.10.38. When I
saw this npm ERR! node -v v0.10.25 in the log, I rolled back to 0.10.25, the error goes away.

**Comment by ilife5** [comment]
I got the same issue

```
sudo npm install -g sqlite3
\
> sqlite3@3.0.5 install /usr/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: Permission denied
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "sqlite3"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

**Comment by springmeyer** [comment]
do not use sudo when installing. if you need to then the problem is permissions and has nothing to do with this module specifically.

**Comment by ilife5** [comment]
I use <code>npm install -g sqlite3</code>, then I got

```
npm install -g sqlite3
\
> sqlite3@3.0.5 install /usr/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /home/jifeng.yao/download/node-v0.12.2-linux-x64/bin/node --eval require('/usr/lib/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node')
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib/node_modules/sqlite3/lib/binding/node-v14-linux-x64/node_sqlite3.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
```

**Comment by ilife5** [comment]
I passed with

```
--build-from-source
```

**Comment by darkoverlordofdata** [comment]
It appears to have been a network issue; once the prebuilts were back online, my install issue went away:

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-v11-linux-x64.tar.gz
[sqlite3] Success: "/home/bruce/Git/games.darkoverlordofdata.com/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" is installed via remote

**Comment by jfaquinojr** [comment]
`npm install --global windows-build-tools`

fixed it for me
