### ISSUE TITLE
Not able to build for node-webkit 0.12.0

### ISSUE THREAD

**Issue by shahrukhmlk** [mapbox/node-sqlite3#436]
Getting this error when building using the instructions given in the docs. please. help

F:\Projects\Library\nw\iarl>npm install sqlite3 --build-from-source --runtime=no
de-webkit --target_arch=ia32 --target=$("0.12.0")
npm WARN package.json iarl@ No description
npm WARN package.json iarl@ No repository field.
npm WARN package.json iarl@ No README data
|
> sqlite3@3.0.5 install F:\Projects\Library\nw\iarl\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\ShahRukh\AppData\Roaming\npm\node_m
odules\nw-gyp\lib\configure.js:101:14)
gyp ERR! stack     at C:\Users\ShahRukh\AppData\Roaming\npm\node_modules\nw-gyp\
lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\ShahRukh\\AppData\\Roaming\\npm\\node_module
s\\nw-gyp\\bin\\nw-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release"
"--module_name=node_sqlite3" "--version=3.0.5" "--major=3" "--patch=5" "--runtim
e=node-webkit" "--node_abi=node-webkit-v$(0.12.0" "--target=$(0.12.0" "--platfor
m=win32" "--target_platform=win32" "--arch=ia32" "--target_arch=ia32" "--module_
main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--mod
ule_path=F:\\Projects\\Library\\nw\\iarl\\node_modules\\sqlite3\\lib\\binding\\n
ode-webkit-v$(0.12.0-win32-ia32" "--module=F:\\Projects\\Library\\nw\\iarl\\node
_modules\\sqlite3\\lib\\binding\\node-webkit-v$(0.12.0-win32-ia32\\node_sqlite3.
node" "--remote_path=./sqlite3/v3.0.5/" "--package_name=node-webkit-v$(0.12.0-wi
n32-ia32.tar.gz" "--staged_tarball=build\\stage\\sqlite3\\v3.0.5\\node-webkit-v$
(0.12.0-win32-ia32.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaw
s.com/sqlite3/v3.0.5/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws
.com/sqlite3/v3.0.5/node-webkit-v$(0.12.0-win32-ia32.tar.gz"
gyp ERR! cwd F:\Projects\Library\nw\iarl\node_modules\sqlite3
gyp ERR! node -v v0.12.2
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd rebuild --name=sqli
te3 --configuration=Release --module_name=node_sqlite3 --version=3.0.5 --major=3
 --patch=5 --runtime=node-webkit --node_abi=node-webkit-v$(0.12.0 --target=$(0.1
2.0 --platform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32 --mo
dule_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --mo
dule_path=F:\Projects\Library\nw\iarl\node_modules\sqlite3\lib\binding\node-webk
it-v$(0.12.0-win32-ia32 --module=F:\Projects\Library\nw\iarl\node_modules\sqlite
3\lib\binding\node-webkit-v$(0.12.0-win32-ia32\node_sqlite3.node --remote_path=.
/sqlite3/v3.0.5/ --package_name=node-webkit-v$(0.12.0-win32-ia32.tar.gz --staged
_tarball=build\stage\sqlite3\v3.0.5\node-webkit-v$(0.12.0-win32-ia32.tar.gz --ho
sted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_t
arball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-webkit-v$
(0.12.0-win32-ia32.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Projects\Library\nw\
iarl\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:71:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "F:\\Projects\\Library\\nw\\iarl\\node_modules\
\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-t
o-build"
node-pre-gyp ERR! cwd F:\Projects\Library\nw\iarl\node_modules\sqlite3
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=Release --m
odule_name=node_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node-webki
t --node_abi=node-webkit-v$(0.12.0 --target=$(0.12.0 --platform=win32 --target_p
latform=win32 --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=
https://mapbox-node-binary.s3.amazonaws.com/ --module_path=F:\Projects\Library\n
w\iarl\node_modules\sqlite3\lib\binding\node-webkit-v$(0.12.0-win32-ia32 --modul
e=F:\Projects\Library\nw\iarl\node_modules\sqlite3\lib\binding\node-webkit-v$(0.
12.0-win32-ia32\node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_name
=node-webkit-v$(0.12.0-win32-ia32.tar.gz --staged_tarball=build\stage\sqlite3\v3
.0.5\node-webkit-v$(0.12.0-win32-ia32.tar.gz --hosted_path=https://mapbox-node-b
inary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-node-bina
ry.s3.amazonaws.com/sqlite3/v3.0.5/node-webkit-v$(0.12.0-win32-ia32.tar.gz' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\\node.js\\\\node.exe" "F:\\node.js\\node_modules\\npm\\bin\\np
m-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--t
arget_arch=ia32" "--target=$(0.12.0"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Projects\Library\nw\iarl\npm-debug.log

F:\Projects\Library\nw\iarl>node "F:\node.js\\.\node_modules\npm\bin\npm-cli.js"
 install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --
target=$("0.12.0")
npm WARN package.json iarl@ No description
npm WARN package.json iarl@ No repository field.
npm WARN package.json iarl@ No README data
\
> sqlite3@3.0.5 install F:\Projects\Library\nw\iarl\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

--target was unexpected at this time.

F:\Projects\Library\nw\iarl\node_modules\sqlite3>  "C:\Users\ShahRukh\AppData\Ro
aming\npm\\node.exe"  "C:\Users\ShahRukh\AppData\Roaming\npm\\node_modules\nw-gy
p\bin\nw-gyp.js" rebuild --name=sqlite3 --configuration=Release --module_name=no
de_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node-webkit --node_abi=
node-webkit-v$(0.12.0) --target=$(0.12.0) --platform=win32 --target_platform=win
32 --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --host=https://map
box-node-binary.s3.amazonaws.com/ --module_path=F:\Projects\Library\nw\iarl\node
_modules\sqlite3\lib\binding\node-webkit-v$(0.12.0)-win32-ia32 --module=F:\Proje
cts\Library\nw\iarl\node_modules\sqlite3\lib\binding\node-webkit-v$(0.12.0)-win3
2-ia32\node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_name=node-web
kit-v$(0.12.0)-win32-ia32.tar.gz --staged_tarball=build\stage\sqlite3\v3.0.5\nod
e-webkit-v$(0.12.0)-win32-ia32.tar.gz --hosted_path=https://mapbox-node-binary.s
3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-node-binary.s3.a
mazonaws.com/sqlite3/v3.0.5/node-webkit-v$(0.12.0)-win32-ia32.tar.gz
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd rebuild --name=sqli
te3 --configuration=Release --module_name=node_sqlite3 --version=3.0.5 --major=3
 --patch=5 --runtime=node-webkit --node_abi=node-webkit-v$(0.12.0) --target=$(0.
12.0) --platform=win32 --target_platform=win32 --arch=ia32 --target_arch=ia32 --
module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --
module_path=F:\Projects\Library\nw\iarl\node_modules\sqlite3\lib\binding\node-we
bkit-v$(0.12.0)-win32-ia32 --module=F:\Projects\Library\nw\iarl\node_modules\sql
ite3\lib\binding\node-webkit-v$(0.12.0)-win32-ia32\node_sqlite3.node --remote_pa
th=./sqlite3/v3.0.5/ --package_name=node-webkit-v$(0.12.0)-win32-ia32.tar.gz --s
taged_tarball=build\stage\sqlite3\v3.0.5\node-webkit-v$(0.12.0)-win32-ia32.tar.g
z --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --ho
sted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-web
kit-v$(0.12.0)-win32-ia32.tar.gz' (255)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Projects\Library\nw\
iarl\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:71:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "F:\\Projects\\Library\\nw\\iarl\\node_modules\
\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-t
o-build"
node-pre-gyp ERR! cwd F:\Projects\Library\nw\iarl\node_modules\sqlite3
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok
Failed to execute 'nw-gyp.cmd rebuild --name=sqlite3 --configuration=Release --m
odule_name=node_sqlite3 --version=3.0.5 --major=3 --patch=5 --runtime=node-webki
t --node_abi=node-webkit-v$(0.12.0) --target=$(0.12.0) --platform=win32 --target
_platform=win32 --arch=ia32 --target_arch=ia32 --module_main=./lib/sqlite3 --hos
t=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=F:\Projects\Library
\nw\iarl\node_modules\sqlite3\lib\binding\node-webkit-v$(0.12.0)-win32-ia32 --mo
dule=F:\Projects\Library\nw\iarl\node_modules\sqlite3\lib\binding\node-webkit-v$
(0.12.0)-win32-ia32\node_sqlite3.node --remote_path=./sqlite3/v3.0.5/ --package_
name=node-webkit-v$(0.12.0)-win32-ia32.tar.gz --staged_tarball=build\stage\sqlit
e3\v3.0.5\node-webkit-v$(0.12.0)-win32-ia32.tar.gz --hosted_path=https://mapbox-
node-binary.s3.amazonaws.com/sqlite3/v3.0.5/ --hosted_tarball=https://mapbox-nod
e-binary.s3.amazonaws.com/sqlite3/v3.0.5/node-webkit-v$(0.12.0)-win32-ia32.tar.g
z' (255)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "F:\\node.js\\node_modules\\npm\\bin\\npm-cli.js" "install"
 "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=ia32" "-
-target=$(0.12.0)"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.5 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Projects\Library\nw\iarl\npm-debug.log

**Comment by raulmatei** [comment]
You don't have Python installed:
`gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`,
Or if you have it, make sure it's added to Windows path more details in nw-gyp installation guide: https://github.com/nwjs/nw-gyp#installation

**Comment by shahrukhmlk** [comment]
Do I need to install only python or all the other items ( listed on
the installation page for windows ) as well ( like visual c++)

**Comment by raulmatei** [comment]
Hi,

You need to have them installed, so if you don't have them just go ahead and install everything. It depends on your environment, but I was able to build SQLite3 for node-webkit 0.12.0 without any issue.

**Comment by shahrukhmlk** [comment]
okay, thanx
i will try to build after installing all of them

**Comment by springmeyer** [comment]
we don't support node-webkit 0.12.0 currently. Bug @Mithgol who might be interested in adding support.

**Comment by Mithgol** [comment]
There was [a message](https://groups.google.com/d/msg/nwjs-general/A7VpwOztU_s/_hsN14m-AT4J) from @rogerwang that said the following:

* they're working on a repository of prebuilt native modules, which are automatically built in their buildbot for each of the nw.js releases,

* SQLite will be in it.

I am going to wait for about a week and see if they release anything.

And if they don't, I'll reopen this issue and try something by myself.

(Meanwhile I am assigning this issue to myself in a slight fear that it might be forgotten by me in a week.)

**Comment by shahrukhmlk** [comment]
thank you.

**Comment by Mithgol** [comment]
Some useful information for future references:

https://github.com/voodootikigod/node-serialport/issues/374#issuecomment-99389279

**Comment by rogerwang** [comment]
@Mithgol , regarding the native module repository @xueeinstein has been working on this. But unfortunately he will leave Intel soon. I'll looking into it after that or find someone else to continue the work but the time would be longer than expected. Thanks.

**Comment by Mithgol** [comment]
@rogerwang Thanks for sharing these details.

**Comment by josephlimb** [comment]
@Mithgol Any update on getting newer versions of NW.js to work?

**Comment by Mithgol** [comment]
I am removing the previous self-assignment of this issue from myself because I am no longer interested in experimenting with node-sqlite3 on NW.js.

This loss of interest is temporal and I may again be interested in the future when NW.js starts supporting Node v4 API (especially all of its new shiny ECMAScript 6 features). Such support is [expected](https://groups.google.com/d/msg/nwjs-general/tvJaLZ3dqvQ/-4DvH1G6BQAJ) to happen eventually.
