### ISSUE TITLE
Repetitive inserts terribly, terribly slow

### ISSUE THREAD

**Issue by lafar6502** [mapbox/node-sqlite3#437]
Code snippet below is only able to do about 100 inserts per second - doing just inserts in a loop. This is nowhere near usual sqlite performance (30K rows per second or so). And I thought prepared statement is for fast execution of repetitive queries.

Unfortunately, this is the fastest way of doing these inserts I found. Just using db.run without a prepared sql stmt (second code snippet) is handling 1-2 inserts per second. 

Can you suggest any acceptably fast way of performing multiple inserts?

    var num = events.length;
        var ts = new Date().getTime();
        var stmt = db.prepare("INSERT INTO logentry(ts, level, correlation, source, logname, message) values($ts, $level, $correlation, $source, $logname, $message)");
        try {
            _.forEach(events, function(evt) {
                stmt.run({
                    $ts: evt.ts,
                    $level: getLogLevelId(evt.level),
                    $correlation: evt.correlation,
                    $source: evt.source,
                    $logname: evt.logname,
                    $message: evt.message
                }, function(err) {
                    num--;
                    if (err != null) console.log('run cbk', err);
                    if (num % 100 == 0) console.log('rem',num);
                    if (num == 0) {
                        console.log('all events saved', events.length, new Date().getTime() - ts);
                    }
                });
            });
        }
        finally {
            stmt.finalize();
        }

=======================================

    //snippet 2 - only 1-2 inserts per second!
        _.forEach(events, function(evt) {
            if (!_.has(evt, 'ts') || !_.has(evt, 'message')) throw new Error('message missing');
            
            db.exec("INSERT INTO logentry(ts, level, correlation, source, logname, message) values($ts, $level, $correlation, $source, $logname, $message)", {
                $ts: evt.ts,
                $level: getLogLevelId(evt.level),
                $correlation: evt.correlation,
                $source: evt.source,
                $logname: evt.logname,
                $message: evt.message
            });
        });

**Comment by Alendri** [comment]
I believe there is currently no built in support for the transaction command, however it is not blocked.
You can run the following SQL code before running your prepared statements.
```javascript
db.run("BEGIN TRANSACTION");
```
Once all prepared statements are done (your loop is finished) you use the following.
```javascript
db.run("COMMIT");
```
The database will process all the statements at the same time at the call of the COMMIT sql command. The resulting performance is what you would normally expect.

WORD OF WARNING: Unexpected stuff may happen since node-sqlite3 will allow any SQL commands to be issued to the server between your BEGIN and COMMIT calls. For expected results ensure only your loop is inserting SQL commands between BEGIN and COMMIT.

Read more at https://www.sqlite.org/lang_transaction.html

**Comment by kkaefer** [comment]
You should certainly get better performance than that; Like @Alendri said, use transactions. We're doing this in [node-mbtiles](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L404) as well and get insert rates that were into the 10s of thousands per second.

**Comment by kkaefer** [comment]
A few more tips for improving performance: http://www.sqlite.org/pragma.html#pragma_synchronous, and using a [WAL](http://www.sqlite.org/wal.html). Lastly, the IO performance of your system is probably the most important factor.

**Comment by lafar6502** [comment]
Thanks everyone for your tips. It appears there's no I/O perf problem on my side, I found a way to do inserts faster - instead of executing 'insert into' query 500 times for each row separately, I glue the SQL together and insert 500 rows in a single query. Only then the code is able to approach 20K-30K inserts per second, which is more or less what 'raw' sqlite would be able to handle. So the naive/default way of doing this in nodejs is not very optimal - I wonder how the asynchronous implementation for nodejs deals with the fact that sqlite doesnt allow concurrent write operations.

**Comment by springmeyer** [comment]
great, thanks for the followup @lafar6502

**Comment by Mithgol** [comment]
See also http://sqlite.org/faq.html#q19

Might be the same problem that was already experienced at #270.
