### ISSUE TITLE
SQLITE_ERROR: no such table

### ISSUE THREAD

**Issue by devanp92** [mapbox/node-sqlite3#441]
I'm getting the following error:

	in serialize
	err:  { [Error: SQLITE_ERROR: no such table: temp] errno: 1, code: 'SQLITE_ERROR' }
	/home/project/node_modules/sqlite3/lib/trace.js:28
	                    throw err;
	                          ^
	Error: SQLITE_ERROR: no such table: temp
	    at Error (native)
	--> in Database#each('select * from temp', [Function])

temp.db is in the same folder, so there shouldn't be any pathing issue.

Setup:    

* node v0.12.2
* npm v2.7.5
* node-sqlite3 v.3.0.5
* OSX Yosemite

I am writing the querying logic in my Sails controller. Just testing it out with a simple "SELECT * FROM TEMP" statement. Here is my source code:

	var sqlite = require('sqlite3').verbose()
	var db = new sqlite.Database('temp.db')

	module.exports = {
	  search: function(next) {
	    db.serialize(function(){
				db.all('SELECT * FROM TEMP', function(err, rows) {
					if(err) {
						console.log("err: ", err)
						throw err
					}
					rows.forEach(function (row) {
						console.log(row)
					})
					closeDb()
					next(err, rows)
				})
			})
		}
	}

	function closeDb(rows) {
		console.log("closeDb")
		db.close()
	}

I feel like the reason is due to asynchro call to DB, however, I am using serializable to thwart that.

**Comment by talkingtab** [comment]
Opening a table in node-sqlite3 is such a fundamental thing that the 
first thought would be the database is not what you expect, for example 
that the database temp.db does not contain a table "temp" or a similar 
error.

You can use sqlite3 from the command line to  open the database and then 
to check the table.

 >sqlite3 temp.db
 >.tables
 >.schema

If the db has the table "temp" then you would need to provide more 
information (like the result of the .tables command), a full code 
listing perhaps one that shows the creation of the table as well 
insertion of data and then a select.

**Comment by devanp92** [comment]
Hi, sorry for the lack of information. Here is what I have:

        $ sqlite3 temp.db

	sqlite> .tables
	temp

	sqlite> .schema temp;
	CREATE TABLE temp (a TEXT, b REAL, c TEXT, d TEXT, e REAL, PRIMARY KEY(a, b, c));

	sqlite> select count(*) from temp;
	563

My insert statements imitate:
     	insert or ignore into temp values ('string',0,'another string','another string',-1.0);

**Comment by springmeyer** [comment]
the behavior of sqlite3 core is to create a db if it does not already exist. So what is likely happening is that the path to the `temp.db` is wrong and a new one is being created.

**Comment by bridiver** [comment]
I am seeing this same issue. The path is correct (absolute path verified in output), the db exists and I can connect to it with the sqlite3 cmd

**Comment by Letladi** [comment]
I was having a similar problem and ended up here, the following seems to solve the problem for me (assuming you want to create a table called 'boards');
```js
db.get("SELECT name FROM sqlite_master WHERE type='table' AND name='boards'", (err, boardTable)=> {
  if (boardTable === undefined) {
    db.run(`CREATE TABLE boards (
      id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
      name TEXT NOT NULL,
      starred INTEGER NOT NULL DEFAULT 0
    );`);
  }
});
```

**Comment by christophemarois** [comment]
In my case too, I was referring to the location using a relative path `../dev.sqlite3`. Changing it for `path.resolve(__dirname, '../dev.sqlite3')` fixed it

**Comment by stevematdavies** [comment]
Ive not managed to get sqlite working in High SIerra at all, always no table found, and no solutions offered.

**Comment by shsma** [comment]
@springmeyer did you try to either await the sync or trigger the function chaining once the sync promise is resolved?
       await Address.sync({ force : true }); // drops addresses table and re-creates it

       Address.sync({ force : true }).then(async () => {
         // your logic here
        });

**Comment by LeonardoGentile** [comment]
Experiencing a similar problem and the above solution didn't work for me.

**Comment by tksilicon** [comment]
> path.resolve(__dirname, '../dev.sqlite3'

Solves the problem

**Comment by shakhawatfci** [comment]
> 
> 
> In my case too, I was referring to the location using a relative path `../dev.sqlite3`. Changing it for `path.resolve(__dirname, '../dev.sqlite3')` fixed it

thanks man this save my day

**Comment by stock-dd** [comment]
> the behavior of sqlite3 core is to create a db if it does not already exist. So what is likely happening is that the path to the `temp.db` is wrong and a new one is being created.

Strange behaviour. More logical would be to throw an error with the erroneous path.

**Comment by Saddam-tech** [comment]
> In my case too, I was referring to the location using a relative path `../dev.sqlite3`. Changing it for `path.resolve(__dirname, '../dev.sqlite3')` fixed it

Thanks bro was having the same issue, resolving the path helped me too

**Comment by MehmetFaahem** [comment]
> the behavior of sqlite3 core is to create a db if it does not already exist. So what is likely happening is that the path to the `temp.db` is wrong and a new one is being created.

So many thanks, It is working now....
