### ISSUE TITLE
installing sqlite3 module on mac

### ISSUE THREAD

**Issue by anantasur** [mapbox/node-sqlite3#442]
npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

**Comment by springmeyer** [comment]
That error message is not enough - I would need all the errors that happened above it to know exactly the cause. However my guess is that you need to upgrade to node-sqlite3 `v3.0.5` because you are running node v0.12.x.
