### ISSUE TITLE
Joins of tables with duplicate column names returning only last table's columns

### ISSUE THREAD

**Issue by beakybal4** [mapbox/node-sqlite3#443]
Node version: v0.10.28
node-sqlite3 version: 3.0.5

If you have two tables which have, say, ID and name fields:

```
thing: ID, name
```

```
user: ID, name, thingID
```

then join them
```
select thing.id, thing.name, user.id, user.name 
from thing
inner join user on thing.id = user.thingID
```

The returned rowset contains only one pair of ID and name properties which will be the ID and name of the last table, which in this case is user:

```
[
{ id: 1,
  name: "foo" }
]
```

This would be to be expected if the fields in the query were not prefixed with the table name. 
When running the same query in a SQLite DB Browser it returns 
```
id, name, id, name 
```
So it's understandable that if you try to make a JS Object out of that then the later id property would overwrite the first one.

Are we using SQLite wrong? Is it expected for it to strip out table names in returned column names?

We have a workaround, which is to alias each column as tablename_columnname, but this is a performance hit as the result then needs to be processed to remove the tablename_.

**Comment by kkaefer** [comment]
The recommended way of circumventing this issue is to use aliases.

**Comment by beakybal4** [comment]
This is what we're doing, it doesn't fix the issue though.

**Comment by kkaefer** [comment]
There is no issue to fix. The SQLite API is index based, and you can use [`sqlite3_column_name`](https://www.sqlite.org/c3ref/column_name.html) to query the name. This is what the node module does, but we can't magically create distinct names.

**Comment by cztomsik** [comment]
If anyone else is fighting this, it seems [dblite](https://github.com/WebReflection/dblite) fetch array of arrays (and so you can reference columns one by one) - there might be others but this one seems to be working.

`sqlite3` currently does not support this but it could certainly be patched somehow in `src/statement.cc`

**Comment by kkaefer** [comment]
I'm not convinced that this change is necessary to node-sqlite3, especially when it's so easy to define unique aliases.

**Comment by cztomsik** [comment]
What do you mean by "so easy"? Is this general purpose sqlite driver or rather an opiniated data access layer for obtaining an array of hashes?

Let's say I'd like to implement sqlite shell using this library - so if I type `SELECT 1, 1` I would really expect to see two columns filled with ones. MySQL does this, MSSQL does it too. You can't implement SQL shell without being able to get an array of arrays (and it's useful for other low-level stuff too)

BTW: even ActiveRecord.Result allows getting array of arrays - and that's much higher abstraction.
http://api.rubyonrails.org/classes/ActiveRecord/Result.html

**Comment by dotnil** [comment]
A pr is proposed :-)

**Comment by dotnil** [comment]
Sorry about the repeated reference. I was struggling with travis.

**Comment by rathboma** [comment]
Hey everyone,

I run [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio) and I'm struggling with this issue.

If a user runs `select 1 as total, 2 as total`, the result is a single column with `2` as the result. Obviously users expect their sql client to return both values `1, 2`.

Is there a suggested way do this now?

**Comment by ianharrigan** [comment]
Is still a "wont fix"?

I have a similar sort of use case where I have an ORM type library that creates multiple joins, some of these, of course, end up with the same column names in the record set and they, essentially, disappear - its also not so easy for the library to add a bunch of "as Foo" since they library doesnt have a deep understanding of all the fields of each table (just the relationship between specific ones) 

Is there _anything_ that can be done with this lib? Or am i better off looking for an alternative?

Thanks in advance!
Ian
