### ISSUE TITLE
Error: Cannot find module 'sqlite3' with mozilla/popcorn.webmaker.org

### ISSUE THREAD

**Issue by ashikcse20** [mapbox/node-sqlite3#455]
I need to launch mozilla/popcorn.webmaker.org in nodejs for my project. For that I have read from here https://github.com/mozilla/popcorn.webmaker.org. I have downloaded the zip file named it to popcorn then did this:  cmd> cd .... popcorn>> npm npm install -g bower >>  npm install --save >> node server.js and there is  he belowed error : I did not do any type of settings like make-valet. I don't know how and where make-valet need to be installed. I did not also setup these :
Microsoft Visual C++ 2010 (Express edition is fine)
Microsoft Visual Studio 2010 SP1. Please help me. 

C:\Users\Ashik\Desktop\popcorn>node server.js
HTTP Server started on http://localhost:8888
Press Ctrl+C to stop
module.js:338
    throw err;
    ^
Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at new module.exports.ConnectorManager (C:\Users\Ashik\Desktop\popcorn\node_
modules\sequelize\lib\dialects\sqlite\connector-manager.js:13:17)
    at TransactionManager.getConnectorManager (C:\Users\Ashik\Desktop\popcorn\no
de_modules\sequelize\lib\transaction-manager.js:33:36)
    at TransactionManager.query (C:\Users\Ashik\Desktop\popcorn\node_modules\seq
uelize\lib\transaction-manager.js:52:15)
    at module.exports.Sequelize.query (C:\Users\Ashik\Desktop\popcorn\node_modul
es\sequelize\lib\sequelize.js:330:36)
    at null.<anonymous> (C:\Users\Ashik\Desktop\popcorn\node_modules\sequelize\l
ib\query-interface.js:971:40)
    at null.<anonymous> (C:\Users\Ashik\Desktop\popcorn\node_modules\sequelize\l
ib\emitters\custom-event-emitter.js:24:18)

C:\Users\Ashik\Desktop\popcorn>

**Comment by ashikcse20** [comment]
@springmeyer

**Comment by springmeyer** [comment]
the problem is that the `node-sqlite3` version popcorn pulls in is ancient: https://github.com/mozilla/popcorn.webmaker.org/blob/master/package.json#L119. That is over 2 years old.

The logs you shared do not provide enough to know the exact error but I presume it will go away if you upgrade popcorn's sqlite3 version to the latest.

**Comment by ashikcse20** [comment]
Thanks. @springmeyer . may allah bless you. Also in this project i want to change the port from 8888 to 3000. But I am not finding that code of port. Can you tell where I can find the port location?

**Comment by ashikcse20** [comment]
Got it in lib/default-config.js from README.md.
