### ISSUE TITLE
Is there a way to get the contents of an in-memory db?

### ISSUE THREAD

**Issue by juanpaco** [mapbox/node-sqlite3#458]
Use case:

I need to render an sqlite db for clients of a service.  I don't have a filesystem on which I can build a .db file.  I would like to use the in-memory db, pipe its contents through zip, and then hand that off as a response.

Is this possible?  I didn't see a way to retrieve the raw bytes that make up the db, but I might have missed it.

If it's not currently a feature, is this something that would be interesting?  I'm happy to put in the work to add this functionality if it isn't there and desired.

**Comment by soaxelbrooke** [comment]
@juanpaco Well... is it?
