### ISSUE TITLE
Node-Webkit Packaged app wont work

### ISSUE THREAD

**Issue by serpent666** [mapbox/node-sqlite3#464]
I have successfully compiled sqlite3 for Node Webkit V0.12.2 (ia32) in windows 7, but as soon as i turn it into a nw package and embed it into the nw.exe it stops working

**Uncaught Error: The specified module could not be found.
C:\Users\yan\AppData\Local\Temp\nw5596_22206\node_modules\sqlite3\lib\binding\node-webkit-v0.12.2-win32-ia32\node_sqlite3.node**

And yet, visiting that directory in explorer shows the .node file existing.

Has anyone successfully created a windows application with the .db file accessible

**Comment by serpent666** [comment]
After posting on the official google group for nwjs.io it turns out its an issue with renaming nw.exe to anything else, this will be fixed in 0.13.0 but the sqlite3 module will probably need to be updated to support that version of IO.js (v1.5.#)

**Comment by springmeyer** [comment]
> sqlite3 module will probably need to be updated to support that version of IO.js (v1.5.#)

Already supported in the latest versions: node-sqlite3@3.0.8 supports up to ios.js 2.x for example.
