### ISSUE TITLE
Unable to bind parameters for ORDER BY

### ISSUE THREAD

**Issue by jexmex** [mapbox/node-sqlite3#466]
When using the following code

```
db.each('SELECT * FROM articles ORDER BY ? ? LIMIT ?, ?', [column, direction, offset, limit]);
```

I get an invalid syntax error near ?. As far as I can tell it will bind to the order by column placeholder, but not the order by direction. If I hard code the column direction in, it works without a hitch. I tried the parameters as just function arguments, an array, and also named arguments.

**Comment by glenn9** [comment]
I think it was never the idea to use sqlite binding for things like that.

Old but relevant: http://sqlite.1065341.n5.nabble.com/Can-I-use-sqlite3-bind-for-colmun-name-or-ASC-DESC-selector-td43732.html

**Comment by jexmex** [comment]
OK, I guess that makes sense. Since the order direction comes from a request, I wanted to make sure it was properly escaped, but I can use other methods of handling that. Thanks.

**Comment by tmcw** [comment]
Closing - like @glenn9 notes, sqlite bindings are not intended for general-purpose token replacement.
