### ISSUE TITLE
Travis iojs ia32 binary builds fail.

### ISSUE THREAD

**Issue by cscott** [mapbox/node-sqlite3#468]
https://github.com/mapbox/node-sqlite3/blob/master/scripts/build_against_node.sh#L73 says:
```
# broken for some unknown reason against io.js
```
I think the reason is that iojs builds have have started using `ia32` in the pathname, instead of `x86`.

I suggest changing:
```
export PATH=$(pwd)/iojs-${NVER}-${platform}-x86/bin:$PATH
```
to:
```
export PATH=$(pwd)/iojs-${NVER}-${platform}-x86/bin:$(pwd)/iojs-${NVER}-${platform}-ia32/bin:$PATH
```
That might fix the build issue.  (Sorry, no pull request.)

**Comment by cscott** [comment]
See: https://github.com/cscott/node-icu-bidi/commit/04b2aaa0a590a486a5d371ecc55b7ccb645978b3

**Comment by springmeyer** [comment]
Thats a good fix, thanks. See also https://github.com/nodejs/build/issues/45. Applied in 1127c27
