### ISSUE TITLE
could not install in Mac , sqlite3/v3.0.8/node-v0.11.14-pre-darwin-x64.tar.gz not found 

### ISSUE THREAD

**Issue by wahaha2099** [mapbox/node-sqlite3#470]
hi , I use npm install sqlite3 , bad request with this url:
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.14-pre-darwin-x64.tar.gz

**Comment by wahaha2099** [comment]
npm install sqlite3
npm http GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.8.tgz
npm http 200 https://registry.npmjs.org/sqlite3/-/sqlite3-3.0.8.tgz
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> sqlite3@3.0.8 install /Users/apple/Documents/ios/Ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.14-pre-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.14-pre-darwin-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.8/node-v0.11.14-pre-darwin-x64.tar.gz (falling back to source compile with node-gyp)

**Comment by coolaj86** [comment]
What version of node are you on? I don't think 0.11 is supported any longer.

Try with io.js v2.3.1 or node v0.12.x.

Keep in mind that node is out of date, so you'll probably have best success with io.js. I'll find out in a few minutes.

**Comment by springmeyer** [comment]
> I don't think 0.11 is supported any longer.

Correct and @wahaha2099 is clearly running node v0.11.x. Closing: the fix is to run v0.10.x or v0.12.x.
