### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by glenn9** [mapbox/node-sqlite3#471]
What would be a safe way to implement read/write rights from 2 different connections? I'm hitting an occasional SQLITE_BUSY and need to eliminate it. Currently the database is accessed from 2 completely different projects, and both of them have several different modules with each their own sqlite3.Database object, all pointing to the same file.

I assume using only one connection per project would eliminate some of them, but I still need 2 connections to the database at the same time, with read/write access. According to the sqlite3 docs this will always be a risk. Any advice, or are there built-in options to use that I'm missing?

**Comment by springmeyer** [comment]
Good questions. I don't know the answer, but there is some discussion that might help at https://github.com/mapbox/node-sqlite3/issues/9 /cc @kkaefer

**Comment by kkaefer** [comment]
This isn't possible with SQLite.

**Comment by glenn9** [comment]
Yeah I figured that much. Solved it with a wrapper module that maintains a single read/write connection and exposed an API to localhost only to allow the other project access. Not ideal but it gets the job done without failures.

**Comment by michael-ts** [comment]
Wait, what? What do you mean "isn't possible"?    I've use the SQLite [Busy Handler](https://www.sqlite.org/c3ref/busy_handler.html) for years and set the handler to do a linearly increasing usleep.

**Comment by kkaefer** [comment]
@michael-ts you might be able to do that, but there's not guarantee that you're not running into a starvation issue. SQLite isn't built for concurrency (it is not one of the design goals), so when you try to use it concurrently anyway, you sort of just hope for the best.
