### ISSUE TITLE
Do you support AIX platforms?

### ISSUE THREAD

**Issue by smartmouse** [mapbox/node-sqlite3#477]
npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.8 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System AIX 1
npm ERR! command "/svt/shared/SVT32_10/bin/node" "/svt/shared/SVT32_10/bin/npm" "install" "sqlite3" "--build-from-source"
npm ERR! cwd /home/strongLoop
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
-bash-4.2$

**Comment by springmeyer** [comment]
Try `npm install --build-from-source`
