### ISSUE TITLE
 node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by albertohenche** [mapbox/node-sqlite3#478]
Hello!
I am a windows vista user and i am having problems with the instalation of sqlite3.

> sqlite3@3.0.8 install C:\mis_proyectos\quiz\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: quiz package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack main
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (C:\mis_proyectos\quiz\node_modul
es\sqlite3\node_modules\node-pre-gyp\lib\util\versioning.js:187:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (C:\mis_proyectos\
quiz\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\versioning.js:233:5
)
node-pre-gyp ERR! stack     at install (C:\mis_proyectos\quiz\node_modules\sqlit
e3\node_modules\node-pre-gyp\lib\install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as ins
tall] (C:\mis_proyectos\quiz\node_modules\sqlite3\node_modules\node-pre-gyp\lib\
node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (C:\mis_proyectos\quiz\node_modules\sqlite3\n
ode_modules\node-pre-gyp\bin\node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\mis_proyectos\quiz\node_mo
dules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Windows_NT 6.0.6002
node-pre-gyp ERR! command "node" "C:\\mis_proyectos\\quiz\\node_modules\\sqlite3
\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd C:\mis_proyectos\quiz
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
quiz package.json is not node-pre-gyp ready:
package.json must declare these properties:
main
binary.module_name
binary.module_path
binary.host
npm ERR! Windows_NT 6.0.6002
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "sqlite3"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mis_proyectos\quiz\npm-debug.log

Please, can anyone help me with this issue?

Thanks in advance.

**Comment by ulknight** [comment]
+1 The same issue
Ubuntu 14.04 64-bit

**Comment by springmeyer** [comment]
Try upgrading to from `0.12.4` to node `0.12.7` and see if that fixes the problem.

**Comment by ulknight** [comment]
installed node 0.12.7. It helps me.

**Comment by springmeyer** [comment]
Thanks for confirming the fix.

**Comment by albertohenche** [comment]
Sorry but it doesn´t work for me.
I still getting those errors.
