### ISSUE TITLE
npm" "install" "sqlite3" fails

### ISSUE THREAD

**Issue by varada66** [mapbox/node-sqlite3#490]
npm" "install" "sqlite3"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

**Comment by springmeyer** [comment]
Thanks for the report, however we will need more of the terminal output to know the problem. Can you run `npm install sqlite3 --loglevel=verbose`, capture the entire terminal output, paste to https://gist.github.com/, and share the link here?

**Comment by layane** [comment]
With iojs 3.0 (Win32 version) on Win7 64bits with Visual Studio Express and Visual Studio 2010 installed.

https://gist.github.com/layane/064f0446211874bdc435

**Comment by dedelp** [comment]
I ran into this issue on windows 7. You should check your installed python version. I had 3.4.3 installed and according to https://github.com/TooTallNate/node-gyp 2.7.3 is the latest version that is supported by node-gyp. Npm worked fine for me after moving to 2.7.3.

**Comment by rmg** [comment]
@layane your issue is that iojs-v3.0.0 isn't supported, which was reported in #487.

**Comment by Mklueh** [comment]
Any news about this issue?

**Comment by mramakrushna** [comment]
Initially it failed, however, when I ran the below command it succeded

npm install sqlite3 --loglevel=verbose

within the verbose log I could see this; # "--fallback-to-build"


npm info lifecycle sqlite3@3.1.8~install: sqlite3@3.1.8

> sqlite3@3.1.8 install C:\NodeJS\expr\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok

**Comment by springmeyer** [comment]
Besides deleting package-lock.json the other workaround here is to upgrade to node-sqlite3@4.0.2, which should avoid this problem since it no longer uses `bundledDependencies` which trigger problems in recent npm versions > npm@5.6.x. refs https://github.com/mapbox/node-pre-gyp/pull/403
