### ISSUE TITLE
sqlite3 installation on Debian 8 64-bit.

### ISSUE THREAD

**Issue by Owidiusz** [mapbox/node-sqlite3#492]
Hello,
the problem occured while trying to install ghost blog platform. But it also happend while trying to install sqlite3 without version specified.

My current node version is v0.13.0-pre

Thanks for helping!

Here are logs for ghost0-6-4 (current):

artur@satellite:~/Projekty/ghost$ npm install --production
/
> sqlite3@3.0.8 install /home/artur/Projekty/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:152:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:723:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1000:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1168:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:461:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64"
gyp ERR! cwd /home/artur/Projekty/ghost/node_modules/sqlite3
gyp ERR! node -v v0.13.0-pre
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/artur/Projekty/ghost/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "node" "/home/artur/Projekty/ghost/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/artur/Projekty/ghost/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.13.0-pre
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.8 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! cwd /home/artur/Projekty/ghost
npm ERR! node -v v0.13.0-pre
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Here are logs for sqlite only:
artur@satellite:~/Projekty/ghost$ npm install sqlite3
|
> sqlite3@3.0.8 install /home/artur/Projekty/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:66:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:152:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:723:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1000:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:5)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64"
gyp ERR! cwd /home/artur/Projekty/ghost/node_modules/sqlite3
gyp ERR! node -v v0.13.0-pre
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/artur/Projekty/ghost/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1072:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "node" "/home/artur/Projekty/ghost/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/artur/Projekty/ghost/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.13.0-pre
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/artur/Projekty/ghost/node_modules/sqlite3/lib/binding/node-v0.13.0-pre-linux-x64' (1)

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.8 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! cwd /home/artur/Projekty/ghost
npm ERR! node -v v0.13.0-pre
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by rmg** [comment]
You are trying to build using a pre-release version of node and `node-gyp` doesn't know how to get the source code for it. You either need to use `--nodedir` to point to the source or try a release. node-v4.0.0 was _just_ released if new is what you want (thought sqlite3@3.0.11 which _should_ support it hasn't been released quite yet)

**Comment by ErisDS** [comment]
Ghost only supports node 0.10.x or 0.12.x - I think this issue can be closed :)

**Comment by Owidiusz** [comment]
It definitely can be closed... I just installed Ghost on another machine and forgot about the issue altogether. Thanks a lot anyway!
Or maybe... add some descriptive error messages for novices like me? Symfony is quite good at that, they often return detailed suggestions in command line.
