### ISSUE TITLE
Out of date wiki link?

### ISSUE THREAD

**Issue by stevenvergenz** [mapbox/node-sqlite3#493]
The [Binaries](https://github.com/mapbox/node-sqlite3/wiki/Binaries#available-binaries) page of your wiki lists a link to see what pre-built binaries are available, but it lists no binaries since sqlite version 2.2.4. Is this correct, and binaries are not available for v3.0.*, or is that link just out of date?

**Comment by springmeyer** [comment]
Thanks for flagging. Yes the link is out of date. The new link however does not have an html page yet, so I need to generate it.

**Comment by ErisDS** [comment]
Closing this as this task is a part of / tracked by: #268
