### ISSUE TITLE
Cannot install in folder with node_modules part in name

### ISSUE THREAD

**Issue by SirAnthony** [mapbox/node-sqlite3#496]
Probably not related to sqlite3, but npm/gyp, please forward me if so.
I found that I cannot install sqlite3 to folders containing node_modules in name, for example node_modules_tmp:
```
/tmp/node_modules_tmp$ npm install  sqlite3
/
> sqlite3@3.0.10 install /tmp/node_modules_tmp/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: not found

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.10 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "sqlite3"
npm ERR! cwd /tmp/node_modules_tmp
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```
same for .node_modules_tmp.xxx, xXxNAGIBATORnode_modules666xXx, whatever name you can come up with, which containing node_modules. It seems incorrect paths parser implemented somewhere.
There is not additional helpful information even with -ddd, but I can post that whole log if you'll desire it.
Reproducible on node 0.10.40 linux & node 0.12.02 windows with sqlite3 3.0.8 & 3.0.10

**Comment by springmeyer** [comment]
Very interesting. I agree that this is not something we likely need to care about or solve in node-sqlite3. Just don't install into a directory with that name. But thanks for creating the ticket - it might help others that make the same mistake.

**Comment by tmcw** [comment]
Closing; thanks for the report but we're comfortable with this restriction.
