### ISSUE TITLE
ERR!: can´t install node-sqlite3 on my Raspberry Pi 2

### ISSUE THREAD

**Issue by devbox** [mapbox/node-sqlite3#501]
Hey,
i´m trying to install node-sqlite3 on my Raspberry Pi 2, but always i got en Err!
Tried many thinks from google for hours, but still not working.
Here is my Err Log:

node_sqlite3.target.mk:120: recipe for target 'Release/obj.target/node_sqlite3.node' failed
make: **\* [Release/obj.target/node_sqlite3.node] Error 1
make: Leaving directory '/home/pi/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm"
gyp ERR! cwd /home/pi/node_modules/sqlite3
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Linux 4.1.6-v7+
node-pre-gyp ERR! command "node" "/home/pi/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/pi/node_modules/sqlite3/lib/binding/node-v14-linux-arm' (1)
npm verb unsafe-perm in lifecycle true
npm info sqlite3@3.0.10 Failed to exec install script
npm verb unlock done using /home/pi/.npm/_locks/sqlite3-47121c89ca36e8cc.lock for /home/pi/node_modules/sqlite3
npm verb stack Error: sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid sqlite3@3.0.10
npm verb cwd /home/pi
npm ERR! Linux 4.1.6-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--sqlite_libname=sqlcipher" "--sqlite=/usr/local" "--verbose"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/sqlite3
npm info preuninstall sqlite3@3.0.10
npm info uninstall sqlite3@3.0.10
npm verb unbuild rmStuff sqlite3@3.0.10 from /home/pi/node_modules
npm info postuninstall sqlite3@3.0.10
npm verb gentlyRm don't care about contents; nuking /home/pi/node_modules/sqlite3

any idea?

**Comment by springmeyer** [comment]
Are you perhaps trying to install as the root user? If so, try not doing that and using an unprivileged user.

**Comment by devbox** [comment]
i have tried this with both, root and unprivileged user with sudo and without.
evertime the same error. any other idea?

**Comment by springmeyer** [comment]
Can you try once more and capture the entire terminal output? Paste it to https://gist.github.com/ and share the link. It seems like the actual error is missing from above.

**Comment by devbox** [comment]
Thanks for your effort.
Here is the complete terminal output and the log file:
https://gist.github.com/devbox/f7c187eb4531ea0620fa

**Comment by ninemind** [comment]
Same thing here on my Rpi2 running Arch linux.  Any fix for this?

**Comment by springmeyer** [comment]
@devbox the error is:

```
  CXX(target) Release/obj.target/node_sqlite3/src/nodejs/Sqlite3Client.o
In file included from ../src/nodejs/Sqlite3Client.cpp:2:0:
../src/nodejs/Sqlite3Client.h:12:1: error: expected class-name before ‘{’ token
```

So, `src/nodejs/Sqlite3Client.cpp` is not part of node-sqlite3. It looks like you added this file or something like that? If you are developing node-sqlite3 by adding C++ files then I'm not sure I can help you.

**Comment by rmancuso** [comment]
I am getting the same error when trying to install on raspian jessie.   IS there any progress on this issue (501)?

**Comment by rmancuso** [comment]
I got past this error by upgrading to a more recent version of nodejs.   On pi 2:

curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y build-essential python-dev python-rpi.gpio nodejs
sudo npm cache clean

the n I reran install of sqlite3...

npm install sqlite3

**Comment by pickupman** [comment]
I was having the same issue. I installed [Node v5.7.1](http://nodejs.org/dist/v5.7.1/node-v5.7.1-linux-armv7l.tar.xz) from sources. I was on Wheezy still, and you need gcc compiler 4.8 or higher. I updated my /etc/apt/sources.list to pull the jessie sources.

Updated sources
```
sudo apt-get update
```

Then installed gcc-4.9 and g++-4.9.
```
sudo apt-get install gcc-4.9 g++-4.9
```

Then ran:
```
sudo npm install sqlite3 --unsafe-perm 
```

That finally got it installed. Then updated my /etc/apt/sources.list bac to wheezy.

**Comment by gima** [comment]
The solution to this issue, is to install the correct package:
```
npm install sqlite3
```

---

The problem here is that while *this* repository lives in GitHub under `mapbox/node-sqlite3`, the corresponding npm package is named [`sqlite3`](https://www.npmjs.com/package/sqlite3).

This bug report was created becaue some people confuse the two and try to install the incorrect npm package, named [`node-sqlite3`](https://www.npmjs.com/package/node-sqlite3).

### Suggetion to this package's maintainers:
Initiate npm's [Package Name Dispute](https://www.npmjs.com/policies/disputes) to claim the offending package name for yourselves. By using `npm show <packagename>`, it seems that your package was created on 2011, whereas the offending package was created on 2014.

These three reasons: 「<sup>1)</sup> direct name violation, <sup>2) </sup>confusion-inducing package name, and <sup>3)</sup> offending package created long after original」 ought to be reasons enough for a successful name claim.

<sup>Hopefully I didn't botch anything, am quite sleepy atm. Sorry if I did :(</sup>
