### ISSUE TITLE
stmt.finalize(callback) can't promise the sequence

### ISSUE THREAD

**Issue by march1993** [mapbox/node-sqlite3#503]
codes like:
```javascript
db.serialize();
var result = []
stmt.prepare(...);
stmt.each(parameter, function(err, row) {
    result.push(row['some_column']);
});
stmt.finalize(function () {
    console.log(JSON.stringify(result));
}
```
but result is missing some rows

it behaves right on Windows7 x64
but behaves not right on Centos 4.3 x64

**Comment by springmeyer** [comment]
@march1993 - can you provide a pull request with a unit test - then the test will run on ubuntu precise and we can see if it works?

**Comment by march1993** [comment]
let me have a try

**Comment by march1993** [comment]
see https://github.com/mapbox/node-sqlite3/pull/507

**Comment by LivorMortis** [comment]
@march1993: I came across this issue when I ran into the same problem, until I realized that finalize doesn't guarantee that the query has been executed in its callback.  Instead, you should use the _complete_ argument of **Statement#each([param, ...], [callback], [complete])**

So rewriting your example code to the following should work:
```node
db.serialize();
var result = []
stmt.prepare(...);
stmt.each(parameter, function(err, row) {
    result.push(row['some_column']);
}, function(err, numRows) {
    console.log(JSON.stringify(result));
});
stmt.finalize();
```

**Comment by tmcw** [comment]
Yep, workaround is ^, use the second argument of .each
