### ISSUE TITLE
Appveyor node x64 3.1.0 build broken

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-sqlite3#506]
The x86 build is working on appveyor for 3.1.0 but not x64:

```
downloading/installing node
node 3.1.0 X64 package not found
At C:\Program Files\AppVeyor\BuildAgent\Modules\avvm\avvm.psm1:94 char:17
+                 throw "$product $version $platform package not found"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (node 3.1.0 X64 package not fo 
   und:String) [], RuntimeException
    + FullyQualifiedErrorId : node 3.1.0 X64 package not found 
```

https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.379/job/pd67xpjqqk337q8g#L26

@FeodorFitsner - this is using `powershell Install-Product`. Is it possible you are missing this node version/arch?

**Comment by FeodorFitsner** [comment]
Will take a look. Is it 3.1.0 only?



- Feodor

**Comment by springmeyer** [comment]
@FeodorFitsner - same error also happened with 3.3.0: https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.384

**Comment by FeodorFitsner** [comment]
I've just checked both 3.1.0 and 3.3.0 and they both worked:

https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.821


https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.820




- Feodor

**Comment by springmeyer** [comment]
Thanks for helping test. So something is specific to node-sqlite3 appveyor.yml then. Really odd all other builds work except for just this one...

**Comment by FeodorFitsner** [comment]
I've noticed there is capital `X64`. Looks like that parameter is case-sensitive. I tried that and it failed: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.822

Should be lower-case `x64`.

**Comment by springmeyer** [comment]
Thank you @FeodorFitsner - you nailed it! It is fixed now https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.388
