### ISSUE TITLE
npm install sqlite3 fails with Node.js v4.0.0 installed

### ISSUE THREAD

**Issue by jorisvervuurt** [mapbox/node-sqlite3#509]
Attempting to install node-sqlite3 with Node.js v4.0.0 (on a Raspberry Pi 2B) fails with the following error:

1563 verbose stack Error: sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
1563 verbose stack Exit status 1
1563 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
1563 verbose stack     at emitTwo (events.js:87:13)
1563 verbose stack     at EventEmitter.emit (events.js:172:7)
1563 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
1563 verbose stack     at emitTwo (events.js:87:13)
1563 verbose stack     at ChildProcess.emit (events.js:172:7)
1563 verbose stack     at maybeClose (internal/child_process.js:817:16)
1563 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1564 verbose pkgid sqlite3@3.1.0
1565 verbose cwd /home/pi/node_apps/uu_provider/node_modules/uu-provider
1566 error Linux 4.1.6-v7+
1567 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
1568 error node v4.0.0
1569 error npm  v2.14.2
1570 error code ELIFECYCLE
1571 error sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
1571 error Exit status 1
1572 error Failed at the sqlite3@3.1.0 install script 'node-pre-gyp install --fallback-to-build'.
1572 error This is most likely a problem with the sqlite3 package,
1572 error not with npm itself.
1572 error Tell the author that this fails on your system:
1572 error     node-pre-gyp install --fallback-to-build
1572 error You can get their info via:
1572 error     npm owner ls sqlite3

**Comment by zprjk** [comment]
I just installed a few minutes ago in win7 + Nodejs v4.0.0 . I was having some troubles getting it right but my problem was I had to specify the visual studio version when installing a package that uses node-gyp:

"npm install sqlite3 --msvs_version=2013" - This made solve my problem. 

Not sure if this helps you tho.

**Comment by jorisvervuurt** [comment]
Okay, so I've got it working by specifically setting which GCC version to use:

    CC=gcc-4.9 CXX=g++-4.9 npm install sqlite3

The latest image of Raspbian (downloaded from raspberrypi.org) comes pre-installed with GCC 4.6.3.

In order to compile Node.js v4.0.0 on the Raspberry Pi (2B in my case), I had to install GCC 4.9.
I did not change the default GCC version though. Is this intended behavior?

**Comment by springmeyer** [comment]
:+1:

**Comment by nickB18** [comment]
@jorisvervuurt It didn't install still. I installed GCC 4.8.4. and tried installing sqlite3.

Nothing's working.

**Comment by jorisvervuurt** [comment]
@nickB18 to be honest, I haven't used node-sqlite3 in quite some time. Have you tried upgrading Raspbian to Jessie (if you're using a Pi, that is)?

**Comment by nickB18** [comment]
@jorisvervuurt I'm not using a Pi. Just wanted to install sqlite3 and make it work with nodejs

**Comment by ErisDS** [comment]
@nickB18 I recommend posting all the information asked for [here](https://github.com/mapbox/node-sqlite3/wiki/Binaries#help) for your setup. If the same solution as in this issue doesn't help you it's very likely you have a different problem.
