### ISSUE TITLE
node-sqlite3 node-pre-gyp binaries for node.js 4.0.0

### ISSUE THREAD

**Issue by lbeschastny** [mapbox/node-sqlite3#511]
Could you publish `node-sqlite3` binaries for node.js 4.0.0 with `node-pre-gyp`, please?

It would be greatly appreciated!

**Comment by donthebike** [comment]
+1 for this request; would be appreciated!

**Comment by evgenyt1** [comment]
+1

**Comment by shijunlin** [comment]
+1

**Comment by Awk34** [comment]
https://github.com/nodejs/node/issues/2798

https://github.com/julianduque/node-expat/commit/c129cb37c6f04f09190a3912f44f3976b813b973 for upgrade reference

**Comment by Awk34** [comment]
I believe the issue is that this package uses `nan@~2.0.5`, whereas at least `2.0.8` is required

**Comment by lbeschastny** [comment]
@Awk34 `node-sqlite` worked fine with node.js 4.0.0 on my ubuntu.

Though, I had an issue on windows because `node-sqlite` doesn't have precompiled binaries for 4.0.0 yet.

**Comment by Awk34** [comment]
Yeah, I'm on Windows 10 :/

**Comment by lbeschastny** [comment]
@Awk34 yeach, `node-gyp` [prerequisites] for windows are pretty tough (you need specific version of Visual Studio and a bunch of other things).

But build process itself should work fine.

  [1]: https://github.com/nodejs/node-gyp#installation

**Comment by Awk34** [comment]
I've got all the `node-gyp` prereqs. I'll try again when I get home from work.

**Comment by springmeyer** [comment]
I missed 4.x binaries for windows. But they should be available now. Can each of you try running the install again? Make sure you are installing `v3.1.0` and if the build fails please report your operating system and exact node version.

**Comment by lbeschastny** [comment]
@springmeyer tested both

```
node-pre-gyp install --target_platform=win32 --target_arch=x64
```

and

```
node-pre-gyp install --target_platform=win32 --target_arch=ia32
```

Installation succeeded without falling back to build.

**Comment by springmeyer** [comment]
thank you for the followup @lbeschastny
