### ISSUE TITLE
Uncaught TypeError: Cannot read property '_ansicursor' of undefined

### ISSUE THREAD

**Issue by raulromanp** [mapbox/node-sqlite3#512]
That error is showed on 'sqlite3' simply when I require it through 
`var sqlite3 = require('sqlite3').verbose();`

I'm on a angularjs-nodewebkit stack and using gulp,  and made all install steps. That error is showed  on both, serving app on browser and compiling final app.

**Comment by chauthai** [comment]
+1
I'm trying to use [knex.js](https://github.com/tgriesser/knex) in a web browser enviroment (a cordova app) and encountered the same error trying to connect to my sqlite db via [cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage). 
knex.js uses node-sqlite3 to connect to the local db with a websql-wrapper.

**Comment by RodrigoBalest** [comment]
+1
Got the same problem when trying to use node-sqlite3 with ember and ember-browserify.

**Comment by RodrigoBalest** [comment]
+1
I'm trying to use node-sqlite3 with ember and ember-browserify and I'm having the same issue.

**Comment by shaikhather** [comment]
Hi All,

Got the same problem when trying to use node-sqlite3 with ember and ember-browserify.

Did anybody got  resolution.

Regards,

**Comment by tmcw** [comment]
node-sqlite3 is a native module: it should not be expected to work browserify or web environments. SQLite3 is a C library.
