### ISSUE TITLE
Does db.serialize support full ACID feature?

### ISSUE THREAD

**Issue by hahamed** [mapbox/node-sqlite3#515]
Hello
Does db.serialize support full ACID feature?
ACID (Atomicity, Consistency, Isolation, Durability) is a set of properties that guarantee that database transactions are processed reliably.

Is db.serialize same as Begin Transaction;END Transaction?
thanks

**Comment by tmcw** [comment]
Hi,

No - for transactions, you can use [SQLite's transactions](https://www.sqlite.org/lang_transaction.html). .serialize() guarantees order of query execution and does not guarantee rollback or any other properties.

- Tom
