### ISSUE TITLE
node v4 support?

### ISSUE THREAD

**Issue by yinso** [mapbox/node-sqlite3#517]
Will there be support for node v4? Trying to build it on Mac and it fails "too many errors" at this time.

**Comment by springmeyer** [comment]
Yes, there is support in the v3.1.0 release. Perhaps you need to upgrade?

**Comment by yinso** [comment]
I've upgraded node and npm - are there other packages I need to as well, like Xcode itself?

**Comment by yinso** [comment]
Ah - I didn't realize I was installing the wrong version. My bad, it all works now. Thanks.
