### ISSUE TITLE
Cant install on Ubuntu 14.04

### ISSUE THREAD

**Issue by rsolci** [mapbox/node-sqlite3#529]
Hi, im trying to install sqlite3 by npm install sqlite3 and i keep getting this error

https://gist.github.com/rsolci/1237ff48f2add3615249

I tried as root but after seeing some comments i switched to a normal user, got the same error

Thanks in advance

**Comment by dziamid** [comment]
`npm install sqlite3` works, seems that this repo has been moved to `sqlite3` npm package

**Comment by rsolci** [comment]
well i issued the same `npm install sqlite3`and i got the error i pasted, anyone got a clue about what is the problem?

**Comment by zedtux** [comment]
I have the same error when installing Ghost blogging platform.

**Comment by talkingtab** [comment]
mkdir foo
cd foo
npm install sqlite3
---- this failed with 4.2.1, 5.0 and v0.12
sudo npm install sqlite3 was successful. I did not look at why.

**Comment by springmeyer** [comment]
The problem everyone here is facing can be solved by installing sqlite3@3.1.x. From the logs it looks like you all are installing `sqlite3@3.0.8` which does not support Node 4.x.

**Comment by zedtux** [comment]
Thank you @springmeyer ! I have downgraded to node 0.12.x and now Ghost is installing successfully !

**Comment by ErisDS** [comment]
As mentioned sqlite@3.0.8, and therefore Ghost do not support Node 4.0 or above. If you're running into this issue because of Ghost, please downgrade to 0.12 or 0.10. 

You can find information about Ghost moving towards support for new versions of node here: https://github.com/TryGhost/Ghost/issues/5821.
