### ISSUE TITLE
cannot build windows 10 64bit 

### ISSUE THREAD

**Issue by SkyTaurus** [mapbox/node-sqlite3#535]
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=ia32 --target=0.10.5 

2697 verbose unsafe-perm in lifecycle true
2698 info sqlite3@3.1.0 Failed to exec install script
2699 verbose unlock done using C:\Users\SkyTa\AppData\Roaming\npm-cache\_locks\sqlite3-0c1f0adb8b85e866.lock for C:\!\node_modules\sqlite3
2700 verbose stack Error: sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
2700 verbose stack Exit status 1
2700 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
2700 verbose stack     at EventEmitter.emit (events.js:110:17)
2700 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
2700 verbose stack     at ChildProcess.emit (events.js:110:17)
2700 verbose stack     at maybeClose (child_process.js:1015:16)
2700 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
2701 verbose pkgid sqlite3@3.1.0
2702 verbose cwd C:\!\dkcjs
2703 error Windows_NT 6.3.9600
2704 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=ia32" "--target=0.10.5"
2705 error node v0.12.7
2706 error npm  v2.11.3
2707 error code ELIFECYCLE
2708 error sqlite3@3.1.0 install: `node-pre-gyp install --fallback-to-build`
2708 error Exit status 1
2709 error Failed at the sqlite3@3.1.0 install script 'node-pre-gyp install --fallback-to-build'.
2709 error This is most likely a problem with the sqlite3 package,
2709 error not with npm itself.
2709 error Tell the author that this fails on your system:
2709 error     node-pre-gyp install --fallback-to-build
2709 error You can get their info via:
2709 error     npm owner ls sqlite3
2709 error There is likely additional logging output above.
2710 verbose exit [ 1, true ]
2711 verbose unbuild node_modules\sqlite3
2712 info preuninstall sqlite3@3.1.0
2713 info uninstall sqlite3@3.1.0
2714 verbose unbuild rmStuff sqlite3@3.1.0 from C:\!\node_modules
2715 info postuninstall sqlite3@3.1.0
2716 silly gentlyRm C:\!\node_modules\sqlite3 is being purged from base C:\!\dkcjs
2717 verbose gentlyRm don't care about contents; nuking C:\!\node_modules\sqlite3
2718 silly vacuum-fs purging C:\!\node_modules\sqlite3
2719 silly vacuum-fs quitting because other entries in C:\!\node_modules

**Comment by neechange** [comment]
4861 warn ENOENT ENOENT: no such file or directory, open 'C:\Users\强\package.json'
4862 warn EPACKAGEJSON C:\Users\强 No description
4863 warn EPACKAGEJSON C:\Users\强 No repository field.
4864 warn EPACKAGEJSON C:\Users\强 No README data
4865 warn EPACKAGEJSON C:\Users\强 No license field.
4866 verbose stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4866 verbose stack Exit status 1
4866 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:233:16)
4866 verbose stack     at emitTwo (events.js:87:13)
4866 verbose stack     at EventEmitter.emit (events.js:172:7)
4866 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
4866 verbose stack     at emitTwo (events.js:87:13)
4866 verbose stack     at ChildProcess.emit (events.js:172:7)
4866 verbose stack     at maybeClose (internal/child_process.js:818:16)
4866 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4867 verbose pkgid sqlite3@3.1.1
4868 verbose cwd C:\Users\强
4869 error Windows_NT 10.0.10240
4870 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3"
4871 error node v5.0.0
4872 error npm  v3.3.6
4873 error code ELIFECYCLE
4874 error sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
4874 error Exit status 1
4875 error Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
4875 error This is most likely a problem with the sqlite3 package,
4875 error not with npm itself.
4875 error Tell the author that this fails on your system:
4875 error     node-pre-gyp install --fallback-to-build
4875 error You can get their info via:
4875 error     npm owner ls sqlite3
4875 error There is likely additional logging output above.
4876 verbose exit [ 1, true ]

**Comment by josephlimb** [comment]
Same issue here but on windows 8.1

**Comment by tmcw** [comment]
Closing in favor of #497
