### ISSUE TITLE
v3.1.1 release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-sqlite3#539]
Quick release to get out node 5.x support (with binaries)

TODO:

  - [x] Write a CONTRIBUTING.md doc so that @Mithgol @ErisDS could follow it in the future to push out a release (will pull from https://github.com/mapnik/node-mapnik/blob/master/CONTRIBUTING.md)
  - [x] Bump the version and get latest deps - https://github.com/mapbox/node-sqlite3/commit/77d51d5785b047ff40f6a8225051488a0d96f7fd
  - [x] Ensure binaries built okay
  - [x] Ensure changelog is up to date
  - [x] Tag and publish

**Comment by springmeyer** [comment]
@Mithgol @lvivier - I see you've added a few things to master, can you update the changelog with the key details?

**Comment by springmeyer** [comment]
v3.1.1 is now tagged and published and supports Node 5.x (with binaries).

**Comment by lvivier** [comment]
:+1:
