### ISSUE TITLE
Bind issue with LIKE

### ISSUE THREAD

**Issue by arb** [mapbox/node-sqlite3#545]
Checked https://github.com/mapbox/node-sqlite3/issues/480 and it didn't help my problem.

Code looks like this:

```js
const sql = `select * from driver where name like '$drivername'`;`
const params = {$drivername: '%Alice%'};
db.all(sql, params, (err, rows) => {
  /*{ [Error: SQLITE_RANGE: bind or column index out of range] errno: 25, code: 'SQLITE_RANGE' }*/
});
```
Not sure what to do at this point. I've tried several variations on LIKE and parameter binding, but no luck. If I do string concatenation, the query works; obviously I would like to avoid that though.

**Comment by lvivier** [comment]
@arb I was able to get this to work on my machine by using an ordinary string for the parameter `sql`, and by not quoting the parameter $drivername:

```js
const Database = require('sqlite3').Database
const sql = 'select * from driver where name like $drivername'
const params = {$drivername: '%Alice%'}

let db = new Database(':memory:')

db.all(sql, params, console.log)
```

As an aside, if you're looking to implement free-form search you should really check out [SQLite's full-text search capabilities](https://www.sqlite.org/fts3.html). It should be much faster for all but the smallest tables (a LIKE that begins with a wildcard [will not use indexes in SQLite](https://www.sqlite.org/optoverview.html#like_opt)).

**Comment by arb** [comment]
Thank you! That solved my problem. I will look into full-text search; looks neat.

**Comment by lvivier** [comment]
:+1: :sparkles:
