### ISSUE TITLE
python 3 dependency?

### ISSUE THREAD

**Issue by jgillich** [mapbox/node-sqlite3#546]
node-sqlite3 requires the `python` [command](https://github.com/mapbox/node-sqlite3/blob/ecb4f3c87c94de881b4b8b7c2e65f636227b7b6b/deps/sqlite3.gyp#L58) to successfully build. I've recently had problems with a lightweight container that only had `python2`, `python` (which is python 3) wasn't installed. node-gyp actually defaults to `python2`, could that be a good default here, too?

**Comment by kkaefer** [comment]
Looks like we're using python only to untar the archive. It looks like we're doing this because Windows... (https://github.com/mapbox/node-sqlite3/issues/151).

**Comment by jgillich** [comment]
Hm, the Windows installer for Python 2 doesn't provide `python2`. I think the best way to detect python would be (like node-gyp)[https://github.com/nodejs/node-gyp/blob/2ac7de02c42654e4e80e346e5d560f7cc01d4553/lib/configure.js#L27], but I have no clue how to integrate that into the gyp file..
