### ISSUE TITLE
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "14.0", "4.0"。 what‘s wrong?

### ISSUE THREAD

**Issue by tosone** [mapbox/node-sqlite3#548]
MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "14.0", "4.0"。 what‘s wrong?

**Comment by ErisDS** [comment]
Please can you provide the following information: 

* terminal logs of failed install (run `npm install sqlite3 --loglevel=info`)
* node-sqlite3 version you tried to install
* node version you are running
* operating system and architecture you are running, e.g. Windows 7 64 bit.

**Comment by neechange** [comment]
我也遇到了WIN10 64位
真搞不懂为什么不发布编译好的版本

**Comment by neechange** [comment]
应该是NET FRAMEWORK版本高了，每个使用者使用一个几M的模块要安装G级的VS。这是什么理论

**Comment by tosone** [comment]
i installed the sqlite 3.1.1.  my os is win10 x64. node version is 4.2.2. npm is the new version now.
After i uninstall `Express visual studio 2016 for Web` and `Express visual studio 2016 for Web`.......
and install `Commity visual studio 2016` only,,,,it worked....why?
sometimes i open a sln file, it need to identification that file which is for web or desktop...i think it has something wrong  with `node-gyp`.

**Comment by ronnieyuyiwei** [comment]
So it is said that if I install Commity visual studio 2016 the problem will be solved?

**Comment by al310517** [comment]
actually after I install vs2015 this problem has not been saved either.

**Comment by ronnieyuyiwei** [comment]
其实把win10的framework版本改一下就好了，已经解决

**Comment by ronnieyuyiwei** [comment]
@cesar-blog 这似乎是很久以前我在win10安装mongodb数据库时遇到的问题，当时的解决办法就是把win10的framework降低一个版本（应该是3.5版本）即可。现在版本的软件已经可以完美兼容了，不会再出现这个问题了。另外上面所说的装vs2016 或者2015我当时试过，不靠谱。

**Comment by F-loat** [comment]
![image](https://user-images.githubusercontent.com/16759376/33665409-ce39ebbc-dad1-11e7-8f17-17e840d49ff7.png)
Just add this.

**Comment by navono** [comment]
first:
> yarn global add --production windows-build-tools

then:
> npm config set msvs_version 2015 --global

**Comment by forconz** [comment]
如果npm install --msvs_version 2015解决不了问题，试试

通过配置淘宝的镜像源解决，首先配置淘宝的镜像源
npm config set registry https://registry.npm.taobao.org

* 然后在 ~/.npmrc 加入下面内容

sass_binary_site=https://npm.taobao.org/mirrors/node-sass/

注：.npmrc 文件位于：

    win：C:\Users\[你的账户名称]\.npmrc
    linux：直接使用 vi ~/.npmrc

项目根目录下执行命令：npm install

**Comment by lonexw** [comment]
在控制面板/程序和功能/启用或关闭 Windows 功能中启用了 .NET Framework 3.5
