### ISSUE TITLE
Possible mem leak on db.each?

### ISSUE THREAD

**Issue by kuanb** [mapbox/node-sqlite3#552]
I am attempting to run the below listed function in Node on a VM with 3.5GB of memory. The query I am running returns ~2.25 million rows. It fails due to what appears to be a memory leak - if someone has encountered this or has suggestions on how to handle the increasing memory problem on this call, I'd appreciate it (or, if it is indeed a leak - I'd like to bring it to your attention).

```
var sqlite3 = require('sqlite3').verbose();

db.each(query, function (error, data) {
    if (error) {
        console.log('Failed.');
    } else {
        console.log('Current perf: ', process.memoryUsage());
    }
    error = null; data = null;
}, function (error, responseLength) {
    console.log('done with all');
});
```

Each row looks like this:

```
2015-11-13T01:17:32Z|510|40.632087|-73.946855|315.47|2|20151112|9910715-SCPD5-SC_D5-Weekday-10-SDon|0|307840|73.51|5.53
```

The goal is to handle each row one at a time and write them to a CSV, line by line, via a stream. The thought was that, by doing this, I would avoid having to hold the entire query response in memory - but this goal seems to be thwarted given the current situation.

**Comment by Photonic404** [comment]
I am having the same issue. Narrowed down my memory leak to db.each calls. Even if I do nothing in them at all, my memory keeps increasing any time I use this db.each and nothing ever gets garbage collected.

**Comment by kuanb** [comment]
Right. Same observation over here.

Sent from Yahoo Mail on Android

**Comment by springmeyer** [comment]
See #614
