### ISSUE TITLE
Ghost blog sqlite3 error

### ISSUE THREAD

**Issue by mdmullendore** [mapbox/node-sqlite3#553]
I have just download ghost blogging platform. After running 
npm start --production 
I get the following error with sqlite3 

 ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mason/Desktop/ghost/npm-debug.log

> sqlite3@3.0.8 install /Users/mason/Desktop/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

Any advice, running on mac, node-v 0.10.0

**Comment by talkingtab** [comment]
if you are running node v0.10.0 (last line of output) then you will need 
to upgrade to node v5.0.0 or equivalent

**Comment by ErisDS** [comment]
Hi @mdmullendore, this is not a problem with node-sqlite. Ghost doesn't support the newer versions of node yet, you need 0.10 or 0.12. We're currently working on adding support for the 4.2 LTS branch. You can follow along here: https://github.com/TryGhost/Ghost/issues/5821

**Comment by zaiddabaeen** [comment]
You need to use sqlite3@3.1.0

See here: http://blog.z-proj.com/running-ghost-with-node-v5/
