### ISSUE TITLE
npm install on Windows 32bit for Node v5 fails

### ISSUE THREAD

**Issue by 10mitri** [mapbox/node-sqlite3#554]
npm install on Windows 32bit for Node v5 fails with :

npm ERR! node v5.0.0
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.

[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/34761/npm-debug.log.txt)

**Comment by abdihaikal** [comment]
Have you installed the Microsoft Visual Studio?

**Comment by 10mitri** [comment]
No Visual Studio installed.
I didn't need it with the previous versions.

**Comment by 10mitri** [comment]
Problem solved by adding the path of node in the PATH environment variable.
Now works on W7 32b / Node (portable) 5.1.0 / npm 3.4.0.

**Comment by Mithgol** [comment]
I guess I should close this issue then.
