### ISSUE TITLE
node-pre-gyp fails during install on Linux on Z

### ISSUE THREAD

**Issue by b-admike** [mapbox/node-sqlite3#555]
Hi,

I am trying to install sqlite or sqlite@3.1.1 on a Linux on Z machine (RHEL7) using node v0.12.7 and npm 2.11.3, but I hit error with node-pre-gyp --fallback-to-build script:

npm ERR! Linux 3.10.0-229.14.1.el7.s390x
npm ERR! argv "/home/biniam/I64_12/bin/node" "/home/biniam/I64_12/bin/npm" "install" "sqlite3@3.1.1"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/biniam/npm-debug.log

gcc/g++ version:
gcc (GCC) 4.8.3
g++ (GCC) 4.8.3

[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/35646/npm-debug.log.txt)

**Comment by mobidev111** [comment]
Got the same:

```
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--unsafe-perm" "--no-bin-links"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
```

**Comment by sorokine** [comment]
I have had a similar problem on Debian on arm7 architecture with node 5.1.1 installed through nvm.  I was able to fix it by explicitly installing node-pre-gyp globally:
```
npm install -g node-pre-gyp
```

**Comment by nickB18** [comment]
@sorokine Hey, I tried installing node-pre-gyp globally. It's showing error.

/usr/local/bin/node-pre-gyp -> /usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires inherits@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/inherits,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires once@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/once,
npm WARN unmet dependency which is version 1.3.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'~2.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.4
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/couch-login requires request@'~2.9.202' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/request,
npm WARN unmet dependency which is version 2.64.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf/node_modules/config-chain requires ini@'~1.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.4
node-pre-gyp@0.6.17 /usr/local/lib/node_modules/node-pre-gyp

**Comment by ErisDS** [comment]
When trying to get help with an install issue, please post the information listed [here](https://github.com/mapbox/node-sqlite3/wiki/Binaries#help) as this makes it much easier to debug what's happening.

**Comment by springmeyer** [comment]
Besides deleting package-lock.json the other workaround here is to upgrade to node-sqlite3@4.0.2, which should avoid this problem since it no longer uses `bundledDependencies` which trigger problems in recent npm versions > npm@5.6.x. refs https://github.com/mapbox/node-pre-gyp/pull/403
