### ISSUE TITLE
Binary Submission 

### ISSUE THREAD

**Issue by aaroncalderon** [mapbox/node-sqlite3#559]
Hi,

I was able to compile sqlite3 v3.1.1 node-v46-win32-ia32
https://github.com/aaroncalderon/sqlite3-binary/blob/master/build/stage/v3.1.1/node_sqlite3-v3.1.1-node-v46-win32-ia32.tar.gz

**Comment by neechange** [comment]
WIN X64

**Comment by aaroncalderon** [comment]
If you are asking for WIN x64 version, I do not have one. I do not have an x64 machine to test it on. 

Sorry. :(

**Comment by aaroncalderon** [comment]
I will be clossing this issue since it has been pretty much abandoned.

If you all need help with this just re open it.
