### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by classicmike** [mapbox/node-sqlite3#563]
Hi guys, 

I'm currently trying to install node-sqlite3 on my mac, however, I am encountering issues, which I don't know if it has got to do with the current package or node-pre-gyp.

I noticed there were a couple of install issues that have been logged in this repo recently, so I'm not sure if my current issue is similar to those ones or not. 

I'm currently running on a mac with Yosimite 10.10.5 installed and node version v4.2.2 as well as npm 2.14.7

I ran the command **npm install sqlite3 --loglevel=info** and I get the following log which can be seen in this gist link https://gist.github.com/classicmike/358a0077889487b6f2c0.

If that can be looked at and possibly fixed asap that would be greatly appreciated.

Thanks.

**Comment by ErisDS** [comment]
Hey @classicmike, thanks for taking the time to provide all the details! It seems you're trying to install quite an old version of sqlite3 (2.2.4) on a very new version of node (4.2.2) and these two things are incompatible.

Support for node 4.2 was added in sqlite 3.1.0 I believe, or thereabouts. 

I'm guessing the old version is a dependency of some other package which hasn't been updated in a while, in which case you'll need to downgrade your node version or use nvm/nave to manage multiple versions.

**Comment by ErisDS** [comment]
@classicmike did this help you get sqlite3 installed?

**Comment by classicmike** [comment]
@ErisDS yes that did help with my installation issues. Thanks for your help. I will close this issue now.
