### ISSUE TITLE
npm install sqlite3 fails with Node 4.2.2

### ISSUE THREAD

**Issue by smartmouse** [mapbox/node-sqlite3#565]
nodebot@plnx131:~/testPM40> node -v
v4.2.2
nodebot@plnx131:~/testPM40> npm -v
2.14.7

Errors is in:
https://gist.github.com/smartmouse/a7d12199c2175603cb7f

nodebot@plnx131:~/testPM40> node -e "console.log(process.config)"
{ target_defaults:
   { cflags: [],
     default_configuration: 'Release',
     defines: [],
     include_dirs: [],
     libraries: [] },
  variables:
   { asan: 0,
     gas_version: '2.24',
     host_arch: 'ppc64',
     icu_data_file: 'icudt56l.dat',
     icu_data_in: '../../deps/icu/source/data/in/icudt56l.dat',
     icu_endianness: 'l',
     icu_gyp_path: 'tools/icu/icu-generic.gyp',
     icu_locales: 'en,root',
     icu_path: './deps/icu',
     icu_small: true,
     icu_ver_major: '56',
     node_byteorder: 'little',
     node_install_npm: true,
     node_prefix: '/',
     node_release_urlbase: '',
     node_shared_http_parser: false,
     node_shared_libuv: false,
     node_shared_openssl: false,
     node_shared_zlib: false,
     node_tag: '-IBMBuild-4.2.2.0-201511110856',
     node_use_dtrace: false,
     node_use_etw: false,
     node_use_lttng: false,
     node_use_openssl: true,
     node_use_perfctr: false,
     node_use_static_libstdcpp: false,
     openssl_fips: '',
     openssl_no_asm: 0,
     python: '/usr/bin/python',
     target_arch: 'ppc64',
     uv_parent_path: '/deps/uv/',
     uv_use_dtrace: false,
     v8_enable_gdbjit: 0,
     v8_enable_i18n_support: 1,
     v8_no_strict_aliasing: 1,
     v8_optimized_debug: 0,
     v8_parent_path: 'deps/v8',
     v8_random_seed: 0,
     v8_use_snapshot: 1,
     want_separate_host_toolset: 0 } }
nodebot@plnx131:~/testPM40>

**Comment by springmeyer** [comment]
Looks like you are trying to install on PPC arch. This is not an arch that we support or is well tested. I recommend using x86_64. If you truly have to use PPC, then the error you are hitting is:

```
tarfile.CompressionError: gzip module is not available
```

basically your python installation looks like it is missing gzip support. This is causing the build to fail.

**Comment by smartmouse** [comment]
Thanks for your prompt reply. will try to get gzip support and see if it works

**Comment by smartmouse** [comment]
I checked our environment, we already got gzip , gunzip installed,. any user should be able to pick it up
wonder why gzip is not picked up in this case?  
The same also works on another ppcLE machine ( which is ubuntu 14), no differences in our set up/installation

**Comment by smartmouse** [comment]
This is not a sqlite3 issue but an issue with the python we set up on the machine, we are able to install sqlte3 on one of the other ppc LE machine..
Just that this machine - the python are unable to find the gzip and the zlib, so machine configuration issues.
