### ISSUE TITLE
asynchronized or not, the document should clarify it.

### ISSUE THREAD

**Issue by fish520** [mapbox/node-sqlite3#585]
I'm really confused that all API are asynchronized ? But after I dig into the `simple-chaining.js` example, I see the `Statment#prepare` API is synchronized at least, but all of them has a node-style callbacks. so the following code 
```javascript
    var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
    stmt.run("lorem content");
    stmt.finalize();
```

may be identical to the following:

```javascript
    var stmt = db.prepare("INSERT INTO lorem VALUES (?)", function(){
        console.log("second");
        stmt.run("lorem content");
        stmt.finalize();
    });
    console.log("first");
```

the output is as expected, printing 'first' followed by 'second', but I'm thinking the "key logical" inside to be synchronized ( the same as `Statement#finallize` and `Statement#bind` ? ), it behaves like a asynchronized one just because the callback is excuted in the next event loop, is that the truth ?

**Comment by wangq8** [comment]
check my code, the async code is in the done callback, the codes should be like this:
```javascript
stmt.prepare('INSERT INTO t1 VALUES (?)', function() {
  stmt.run('value1');
  stmt.finalize(done);
});

db.serialize(function(){
  // one by one
  db.wait(done);
});
```

**Comment by tmcw** [comment]
The documentation does explain this in detail:

* https://github.com/mapbox/node-sqlite3/wiki/Control-Flow
* https://github.com/mapbox/node-sqlite3/wiki/API
