### ISSUE TITLE
error:Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.

### ISSUE THREAD

**Issue by jmolboy** [mapbox/node-sqlite3#593]
error when i install [cnpm](https://github.com/cnpm/cnpmjs.org)

```
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jmol/cnpmjs.org/npm-debug.log
make: *** [install] Error 1
```

pls help.

npm log 
[npm-debug.log.zip](https://github.com/mapbox/node-sqlite3/files/100276/npm-debug.log.zip)

**Comment by timonti** [comment]
I'm facing the same error.

**Comment by ErisDS** [comment]
If you're having install issues, please provide all of the information described here: https://github.com/mapbox/node-sqlite3/blob/master/CONTRIBUTING.md#install-help

Without the proper error log and details of your system it's not possible for anyone to see what might be wrong.

**Comment by tmcw** [comment]
Closing; need a full error log to debug.
