### ISSUE TITLE
No error thrown when connecting to a non-sqlite3 file

### ISSUE THREAD

**Issue by falnos24865** [mapbox/node-sqlite3#595]
For example:

<pre>
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database('/path/to/image.png', null, function(err) {
  // err is null
});
</pre>

Is there any validation is done when trying to connect to a sqlite file that it is in deed a database file, or will sqlite3 simply overwrite whatever is there?

**Comment by olsonpm** [comment]
My temporary, and likely not comprehensive workaround [is the following](http://unix.stackexchange.com/a/48831)

```js
const childProcess = require('child_process')
  , path = require('path');

const isSqliteFileSync = fPath => {
  let res;
  try {
    const sqliteFormatStr = childProcess.execSync('head -c 16 ' + path.resolve(fPath)).toLowerCase();
    res = (sqliteFormatStr === 'sqlite format 3');
  }
  catch (e) { res = false; }
  return res;
};
```

**Comment by tmcw** [comment]
This is default SQLite behavior, as you can confirm by attaching the default CLI tool to a non-SQLite file.
