### ISSUE TITLE
Unable to install on Raspberry PI

### ISSUE THREAD

**Issue by SaphuA** [mapbox/node-sqlite3#601]
Trying to install sqlite3 using npm on the Raspberry pi, but can't figure out why it keeps failing. Not much of an linux expert so that's most likely part of the issue.

These steps all work fine:

1. Install Debian Jessie Light (https://www.raspberrypi.org/downloads/raspbian/)
2. Installed node 5.6 (http://blog.wia.io/installing-node-js-v4-0-0-on-a-raspberry-pi/)
3. Fixed npm permissions (https://docs.npmjs.com/getting-started/fixing-npm-permissions)
4. `chmod 777` all directories that I suspect are giving issues
5. `npm install node-gyp -g`

And then come steps from the `readme.md`

1. `export LDFLAGS="-L/usr/local/lib"`
2. `export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"`
3. `export CXXFLAGS="$CPPFLAGS"`
4. `npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose`

It fails at the last step. I'm fairly certain this is a rights issue, but what I don't understand is what needs access to what. I've attached the npm log and this is what's displayed on screen:

```
> sqlite3@3.1.1 install /media/usb0/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
npm verb lifecycle sqlite3@3.1.1~install: unsafe-perm in lifecycle true
npm verb lifecycle sqlite3@3.1.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/media/usb0/node_modules/sqlite3/node_modules/.bin:/media/usb0/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
npm verb lifecycle sqlite3@3.1.1~install: CWD: /media/usb0/node_modules/sqlite3
npm info lifecycle sqlite3@3.1.1~install: Failed to exec install script
npm verb unlock done using /home/pi/.npm/_locks/staging-a3a607d475bab14c.lock for /media/usb0/node_modules/.staging
npm WARN sousvide@ No description
npm WARN sousvide@ No repository field.
npm WARN sousvide@ No license field.
npm verb stack Error: sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 126
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at EventEmitter.emit (events.js:185:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:827:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid sqlite3@3.1.1
npm verb cwd /media/usb0
npm ERR! Linux 4.1.17+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--build-from-source" "--sqlite_libname=sqlcipher" "--sqlite=/usr/local" "--verbose"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
```

Does anyone have any clue?

[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/131182/npm-debug.log.txt)

**Comment by SaphuA** [comment]
I just tried again to install in /home/pi and that works perfectly. I was trying to install on USB before. So it must be an rights issue, I just can't do figure out what.

**Comment by alexellis** [comment]
Go ahead and close, that looks like a FS permissions issue due to the USB stick.

**Comment by tmcw** [comment]
Closing; permissions.
