### ISSUE TITLE
SQLite3 error during execution

### ISSUE THREAD

**Issue by Satish102** [mapbox/node-sqlite3#602]
I have created Angular JS application to be compiled with nw.js (webkit), but I am getting following error when I run the application. Appreciate any quick help ASAP.

'C:\Users\msi1150\AppData\Local\Temp\nw4456_6774\node_modules\sqlite3\lib\binding\node-webkit-v0.8.3-win32-ia32\node_sqlite3.node'

I am trying on Windows 8

Thanks in advance,

Satish L C

**Comment by kroggen** [comment]
You have to inform the complete error message if you want some help. You posted only the path to the binary file.

**Comment by tmcw** [comment]
Closing; please open a new issue if you can provide enough details to debug.
