### ISSUE TITLE
API Clarification

### ISSUE THREAD

**Issue by JoshuaWise** [mapbox/node-sqlite3#603]
I have a few questions about the API.

- What's the difference between `run()` and `exec()`? It seems like they do the same thing.
- What does it mean to "finalize" a statement?

**Comment by Gigabyte-Giant** [comment]
Unless I'm terribly mistaken, I do believe [`sqlite3.Database.run`](https://github.com/mapbox/node-sqlite3/wiki/API#statementrunparam--callback) only executes a single SQL statement, while [`sqlite3.Database.exec`](https://github.com/mapbox/node-sqlite3/wiki/API#databaseexecsql-callback) executes all SQL statements within the supplied string, up until the first instance of `\0`.

Finalizing a [prepared] statement, is essentially saying that you're done with it, and that you want to free up the memory that was used for it.

- Brynden

**Comment by tmcw** [comment]
Yep, what Brynden writes is the case, and is covered thoroughly by the documentation. The purpose of [finalize is also documented and explained](https://github.com/mapbox/node-sqlite3/wiki/API#statementfinalizecallback).
