### ISSUE TITLE
Write queries are not sequential

### ISSUE THREAD

**Issue by JoshuaWise** [mapbox/node-sqlite3#605]
SQLite3 serializes writes to the the database. This means if I tell it to write 5 times, those 5 writes will happen one at a time, in order.

However, when I run the test below, occasionally the INSERTs are not sequential (sometimes they are all perfect, but running the test several times reveals the occasional bug).

This could be caused by a bug in the SQLite3 engine, but it is more likely caused by some asynchronicity introduced by the node-sqlite3 library. Could this be the case? And if so, is it fixable?
```js
var fs = require('fs');
var sql = require('sqlite3');
var db = new sql.Database('test.db');
var count = 10000;
var inserted = 0;


// Delete database from previous test.
try {
  fs.unlinkSync('test.db');
} catch (e) {/* ignore errors */}


console.log('testing...');


db.on('open', function () {
  db.run("CREATE TABLE tests (id INTEGER);", function (err) {
    if (err) {throw err;}
    
    // Insert rows into table, one at a time.
    for (var i = 0; i < count; i++) {
      db.run("INSERT INTO tests VALUES (?)", [i], onInserted);
    }
  });
});

function onInserted(err) {
  if (err) {throw err;}
  
  if (++inserted === count) {
    // When all rows have been inserted,
    // check to see if their sequence is correct.
    checkSequence();
  }
}

function checkSequence() {
  db.all("SELECT id FROM tests", function (err, results) {
    if (err) {throw err;}
    var ids = pluck(results, 'id');
    
    for (var i = 0; i < count; i++) {
      if (ids[i] !== i) {
        console.log('failed!');
        printErrorDetails(ids, i);
        process.exit(1);
      }
    }
    
    console.log('success!');
    process.exit();
  });
}

function printErrorDetails(ids, index) {
  for (var i = index - 2; i <= index + 2; i++) {
    var id = ids[i];
    var isWrong = id !== i;
    if (id != null) {
      console.log('=> ' + id + (isWrong ? ' (expected to be ' + i + ')' : ''));
    }
  }
}

function pluck(array, property) {
  function getProperty(obj) {
    return obj == null ? undefined : obj[property];
  }
  return array.map(getProperty);
}
```

**Comment by ErisDS** [comment]
> However, when I run the test below, occasionally the INSERTs are not sequential (sometimes they are all perfect, but running the test several times reveals the occasional bug).

Could you quantify occasional? IMO it'd make a more compelling case to investigate if, for example this issue had the stats on the no. of failures from this test run 1000 times.

**Comment by JoshuaWise** [comment]
On my Ubuntu production server, it fails every time I run the test.

On my Macbook Pro development computer, it fails every 2 or 3 times I run the test.

**Comment by JoshuaWise** [comment]
Okay, after doing 1000 tests on my Macbook Pro, a total of 797 rows were out of order. Each test inserts 10,000 rows, so it was 797 rows out of 10,000,000 total rows. That may seem like a small number, but I think it's significant for large databases.

Also, although I didn't run 1000 tests on my Ubuntu server, that machine was experiencing a much higher rate of failure (~5x) when I did single tests on it.

**Comment by talkingtab** [comment]
try

db.on('open', function () {
   db.run("CREATE TABLE tests (id INTEGER);", function (err) {
     if (err) {throw err;}

     // Insert rows into table, one at a time.
     db.serialize(function() {
         for (var i = 0; i < count; i++) {
           db.run("INSERT INTO tests VALUES (?)", [i], onInserted);
         }
     });
   });
});
which proclaimed success on my ubuntu system after getting errors with 
your original code

My take (and I could be wrong) is that although sqlite the program may 
handle sequences correctly, because node is not synchronous the calls 
can get out of sequence when going from your code to sqlite, for example:

-db.run starts with value 1
- returns, but not complete
db.run starts with value 2
- returns but not complete
db.run(2) completes
db.run(1) completes.

db.serialize ensures this does not happen

Same thing will happen on a table insert then a lookup for the same 
entry (only worse) - the lookup will fail because it hits the table 
before the insert has completed.

**Comment by JoshuaWise** [comment]
I think you're right, @talkingtab . That's too bad that we have to rely on `db.serialize()`, but I suppose it is necessary
