### ISSUE TITLE
node-sqlite3 run callback not working?

### ISSUE THREAD

**Issue by MassimoCappellano** [mapbox/node-sqlite3#606]
Hi,

I have this problem with nodejs 4.3 and sqlite3: 3.1.1.

The problem is that I want to separate when update has effect on one row from when update has no effect on none row (without doing select first).

In my example I have a row with an id = 1. I would like to know that when I do an update with an id = 1111, no row has been affected.

I have used the callback on database.run but it seems not valorizing value of **this.changes** when update is executed on a row in the database.

    var sql = 'update recipes set stars = stars + 1 where id = ?';

	db.run(sql,
		[
		1 // id = 1 execute update - if id = 11111 do nothing
		], (err) => {
			if(err)
				throw err;
            
            console.log("VALUE CHANGES: " + this.changes + " - " + util.inspect(this, { showHidden: false, depth: null }));
            
			if(this.changes == 1)
				console.log("WORK DONE");
			else
				console.log("NOTHING DONE");

		});

this.changes is undefined even when update is executed correctly (the same when I use an id, for example 1111111, not in the db).

**There is a bug or I don't have understood how use callback?**

Result on console is:
VALUE CHANGES: undefined - { db: Database { open: true, filename: './dindin.sqlite', mode: 65542 } }

the same if id = 1 and execute update on one row or id= 1111111 and execute update on none row.

Here on http://stackoverflow.com/questions/10022984/nodejs-node-sqlite3-run-callback-not-working 
Massimo

**Comment by talkingtab** [comment]
It is the callback thing. "this" in a callback will be the context of 
where the call back was called from *not* your present context.

The best way to understand this is to google javascript along with 
"closures" and "this" and "object.bind". Lots of stuff out there to 
learn about. ES6 aka ES2015 has a fat arrow operator and is worth 
understanding as well.

**Comment by MassimoCappellano** [comment]
Thanks Terry for yours hint,

the problem was that I've used fat arrow for callback declaration. From documentation I've discovered that in arrow function (fat arrow ), _this_ has _lexical scope_ and so _this_ result undefined  and not valued as in documentation said. Using otherwise anonimous function, _this_ is bounded in dynamic scope and so **this.changes** is valued.

Now, with code as below, is ok:

```
var sql = 'update recipes set stars = stars + 1 where id = ?';

db.run(sql,
    [
    1 // id = 1 execute update - if id = 11111 do nothing
    ], function(err) {
        if(err)
            throw err;

        console.log("VALUE CHANGES: " + this.changes + " - " + util.inspect(this, { showHidden: false, depth: null }));

        if(this.changes == 1)
            console.log("WORK DONE");
        else
            console.log("NOTHING DONE");

    });
```

Thanks
