### ISSUE TITLE
CREATE TABLE OF NOT EXIST

### ISSUE THREAD

**Issue by zettam** [mapbox/node-sqlite3#607]
I've been trying to create a table if it's not there,
`db.run("CREATE TABLE IF NOT EXIST mytable (path text)", ...)`
seems to fail.
Looks like sqlite needs to be 3.3
what version is the package? if it's 3.3+ then why do you think this is failing for me ?

**Comment by kroggen** [comment]
1. You did not showed what is the error message
2. Your command is incorrect. Check the documentation:
https://www.sqlite.org/lang_createtable.html

**Comment by zettam** [comment]
I've checked the documentation, I don't see anything wrong about it?
Maybe you can guide me

**Comment by zettam** [comment]
Ah you were right. Typo. Fixed.
Feel free to close the thread.
