### ISSUE TITLE
Windows 10 NW.js Build failed for 0.12.3

### ISSUE THREAD

**Issue by digitronic-games** [mapbox/node-sqlite3#613]
I'm trying to build sqlite3 for nw.js 0.12.3, I keep running into this error. I've never build node modules before so I have no Idea whats going on here, if someone could help or point me in the right direction it would be much appreciated.

This is that the console output:

	> sqlite3@3.1.1 install .\node_modules\sqlite3
	> node-pre-gyp install --fallback-to-build

	.\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
	(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
	Traceback (most recent call last):
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\gyp_main.py", line 18, in <module>
		sys.exit(gyp.script_main())
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\__init__.py", line 534, in script_main
		return main(sys.argv[1:])
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\__init__.py", line 527, in main
		return gyp_main(args)
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\__init__.py", line 503, in gyp_main
		options.circular_check)
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
		generator.CalculateVariables(default_variables, params)
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\generator\msvs.py", line 1798, in CalculateVariables
		generator_flags.get('msvs_version', 'auto'))
	  File "~\AppData\Roaming\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py", line 400, in SelectVisualStudioVersion
		versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
	KeyError: '2015'
	gyp ERR! configure error
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (~\AppData\Roaming\npm\node_modules\nw-gyp\lib\configure.js:361:16)
	gyp ERR! stack     at emitTwo (events.js:100:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Windows_NT 10.0.10586
	gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Users\\Digipixel_IO\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Node\\projects\\tea\\sqlite3-nwjs\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.12.3-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\Node\\projects\\tea\\sqlite3-nwjs\\node_modules\\sqlite3\\lib\\binding\\node-webkit-v0.12.3-win32-x64" "--python=C:/Python27/python.exe" "--msvs_version=2015"
	gyp ERR! cwd .\node_modules\sqlite3
	gyp ERR! node -v v5.7.1
	gyp ERR! nw-gyp -v v0.13.0
	gyp ERR! not ok
	node-pre-gyp ERR! build error
	node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=.\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=.\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64 --python=C:/Python27/python.exe --msvs_version=2015' (1)
	node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (.\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
	node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
	node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
	node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
	node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	node-pre-gyp ERR! System Windows_NT 10.0.10586
	node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Node\\projects\\tea\\sqlite3-nwjs\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd .\node_modules\sqlite3
	node-pre-gyp ERR! node -v v5.7.1
	node-pre-gyp ERR! node-pre-gyp -v v0.6.14
	node-pre-gyp ERR! not ok
	Failed to execute 'nw-gyp.cmd configure --fallback-to-build --module=.\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=.\node_modules\sqlite3\lib\binding\node-webkit-v0.12.3-win32-x64 --python=C:/Python27/python.exe --msvs_version=2015' (1)
	npm WARN enoent ENOENT: no such file or directory, open '.\package.json'
	npm WARN sqlite3-nwjs No description
	npm WARN sqlite3-nwjs No repository field.
	npm WARN sqlite3-nwjs No README data
	npm WARN sqlite3-nwjs No license field.
	npm ERR! Windows_NT 10.0.10586
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--build-from-source" "--runtime=node-webkit" "--target_arch=x64" "--target=0.12.3"
	npm ERR! node v5.7.1
	npm ERR! npm  v3.6.0
	npm ERR! code ELIFECYCLE

	npm ERR! sqlite3@3.1.1 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the sqlite3@3.1.1 install script 'node-pre-gyp install --fallback-to-build'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the sqlite3 package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-pre-gyp install --fallback-to-build
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs sqlite3
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls sqlite3
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR! .\sqlite3-nwjs\npm-debug.log

[npm-debug.log ](https://dl.dropboxusercontent.com/u/37497632/npm/npm-debug.log)

This is the command I'm running:

	npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.12.3

and I've set the variables:

	npm config set python C:/Python27/python.exe --global
	npm config set msvs_version 2015 --global

and I have the _GYP_MSVS_VERSION=2015_ set in my PC environment variables and the path added for python.

and here's some more data on the env:

	node -v v5.7.1
	npm -v 3.6.0
	
	npm ls -global
	+-- node-gyp@3.3.1
	| +-- fstream@1.0.8
	| | `-- inherits@2.0.1
	| +-- glob@4.5.3
	| | +-- inflight@1.0.4
	| | | `-- wrappy@1.0.1
	| | +-- minimatch@2.0.10
	| | | `-- brace-expansion@1.1.3
	| | |   +-- balanced-match@0.3.0
	| | |   `-- concat-map@0.0.1
	| | `-- once@1.3.3
	| +-- graceful-fs@4.1.3
	| +-- minimatch@1.0.0
	| | +-- lru-cache@2.7.3
	| | `-- sigmund@1.0.1
	| +-- mkdirp@0.5.1
	| | `-- minimist@0.0.8
	| +-- nopt@3.0.6
	| | `-- abbrev@1.0.7
	| +-- npmlog@2.0.2
	| | +-- ansi@0.3.1
	| | +-- are-we-there-yet@1.0.6
	| | | +-- delegates@1.0.0
	| | | `-- readable-stream@2.0.5
	| | |   +-- core-util-is@1.0.2
	| | |   +-- isarray@0.0.1
	| | |   +-- process-nextick-args@1.0.6
	| | |   +-- string_decoder@0.10.31
	| | |   `-- util-deprecate@1.0.2
	| | `-- gauge@1.2.7
	| |   +-- has-unicode@2.0.0
	| |   +-- lodash.pad@4.1.0
	| |   | +-- lodash.repeat@4.0.0
	| |   | `-- lodash.tostring@4.1.2
	| |   +-- lodash.padend@4.2.0
	| |   `-- lodash.padstart@4.2.0
	| +-- osenv@0.1.3
	| | +-- os-homedir@1.0.1
	| | `-- os-tmpdir@1.0.1
	| +-- path-array@1.0.1
	| | `-- array-index@1.0.0
	| |   +-- debug@2.2.0
	| |   | `-- ms@0.7.1
	| |   `-- es6-symbol@3.0.2
	| |     +-- d@0.1.1
	| |     `-- es5-ext@0.10.11
	| |       `-- es6-iterator@2.0.0
	| +-- request@2.69.0
	| | +-- aws-sign2@0.6.0
	| | +-- aws4@1.3.2
	| | | `-- lru-cache@4.0.0
	| | |   +-- pseudomap@1.0.2
	| | |   `-- yallist@2.0.0
	| | +-- bl@1.0.3
	| | +-- caseless@0.11.0
	| | +-- combined-stream@1.0.5
	| | | `-- delayed-stream@1.0.0
	| | +-- extend@3.0.0
	| | +-- forever-agent@0.6.1
	| | +-- form-data@1.0.0-rc3
	| | | `-- async@1.5.2
	| | +-- har-validator@2.0.6
	| | | +-- chalk@1.1.1
	| | | | +-- ansi-styles@2.2.0
	| | | | | `-- color-convert@1.0.0
	| | | | +-- escape-string-regexp@1.0.5
	| | | | +-- has-ansi@2.0.0
	| | | | | `-- ansi-regex@2.0.0
	| | | | +-- strip-ansi@3.0.1
	| | | | `-- supports-color@2.0.0
	| | | +-- commander@2.9.0
	| | | | `-- graceful-readlink@1.0.1
	| | | +-- is-my-json-valid@2.13.1
	| | | | +-- generate-function@2.0.0
	| | | | +-- generate-object-property@1.2.0
	| | | | | `-- is-property@1.0.2
	| | | | +-- jsonpointer@2.0.0
	| | | | `-- xtend@4.0.1
	| | | `-- pinkie-promise@2.0.0
	| | |   `-- pinkie@2.0.4
	| | +-- hawk@3.1.3
	| | | +-- boom@2.10.1
	| | | +-- cryptiles@2.0.5
	| | | +-- hoek@2.16.3
	| | | `-- sntp@1.0.9
	| | +-- http-signature@1.1.1
	| | | +-- assert-plus@0.2.0
	| | | +-- jsprim@1.2.2
	| | | | +-- extsprintf@1.0.2
	| | | | +-- json-schema@0.2.2
	| | | | `-- verror@1.3.6
	| | | `-- sshpk@1.7.4
	| | |   +-- asn1@0.2.3
	| | |   +-- dashdash@1.13.0
	| | |   | `-- assert-plus@1.0.0
	| | |   +-- ecc-jsbn@0.1.1
	| | |   +-- jodid25519@1.0.2
	| | |   +-- jsbn@0.1.0
	| | |   `-- tweetnacl@0.14.1
	| | +-- is-typedarray@1.0.0
	| | +-- isstream@0.1.2
	| | +-- json-stringify-safe@5.0.1
	| | +-- mime-types@2.1.10
	| | | `-- mime-db@1.22.0
	| | +-- node-uuid@1.4.7
	| | +-- oauth-sign@0.8.1
	| | +-- qs@6.0.2
	| | +-- stringstream@0.0.5
	| | +-- tough-cookie@2.2.1
	| | `-- tunnel-agent@0.4.2
	| +-- rimraf@2.5.2
	| | `-- glob@7.0.3
	| |   +-- minimatch@3.0.0
	| |   `-- path-is-absolute@1.0.0
	| +-- semver@5.1.0
	| +-- tar@2.2.1
	| | `-- block-stream@0.0.8
	| `-- which@1.2.4
	|   +-- is-absolute@0.1.7
	|   | `-- is-relative@0.1.3
	|   `-- isexe@1.1.2
	`-- nw-gyp@0.13.0
	  +-- fstream@0.1.31
	  | +-- graceful-fs@3.0.8
	  | `-- inherits@2.0.1
	  +-- glob@3.2.11
	  | `-- minimatch@0.3.0
	  +-- graceful-fs@2.0.3
	  +-- minimatch@0.4.0
	  | +-- lru-cache@2.7.3
	  | `-- sigmund@1.0.1
	  +-- mkdirp@0.5.1
	  | `-- minimist@0.0.8
	  +-- nopt@2.2.1
	  | `-- abbrev@1.0.7
	  +-- npmlog@0.1.1
	  | `-- ansi@0.3.1
	  +-- osenv@0.1.3
	  | +-- os-homedir@1.0.1
	  | `-- os-tmpdir@1.0.1
	  +-- request@2.69.0
	  | +-- aws-sign2@0.6.0
	  | +-- aws4@1.3.2
	  | | `-- lru-cache@4.0.0
	  | |   +-- pseudomap@1.0.2
	  | |   `-- yallist@2.0.0
	  | +-- bl@1.0.3
	  | | `-- readable-stream@2.0.5
	  | |   +-- core-util-is@1.0.2
	  | |   +-- isarray@0.0.1
	  | |   +-- process-nextick-args@1.0.6
	  | |   +-- string_decoder@0.10.31
	  | |   `-- util-deprecate@1.0.2
	  | +-- caseless@0.11.0
	  | +-- combined-stream@1.0.5
	  | | `-- delayed-stream@1.0.0
	  | +-- extend@3.0.0
	  | +-- forever-agent@0.6.1
	  | +-- form-data@1.0.0-rc3
	  | | `-- async@1.5.2
	  | +-- har-validator@2.0.6
	  | | +-- chalk@1.1.1
	  | | | +-- ansi-styles@2.2.0
	  | | | | `-- color-convert@1.0.0
	  | | | +-- escape-string-regexp@1.0.5
	  | | | +-- has-ansi@2.0.0
	  | | | | `-- ansi-regex@2.0.0
	  | | | +-- strip-ansi@3.0.1
	  | | | `-- supports-color@2.0.0
	  | | +-- commander@2.9.0
	  | | | `-- graceful-readlink@1.0.1
	  | | +-- is-my-json-valid@2.13.1
	  | | | +-- generate-function@2.0.0
	  | | | +-- generate-object-property@1.2.0
	  | | | | `-- is-property@1.0.2
	  | | | +-- jsonpointer@2.0.0
	  | | | `-- xtend@4.0.1
	  | | `-- pinkie-promise@2.0.0
	  | |   `-- pinkie@2.0.4
	  | +-- hawk@3.1.3
	  | | +-- boom@2.10.1
	  | | +-- cryptiles@2.0.5
	  | | +-- hoek@2.16.3
	  | | `-- sntp@1.0.9
	  | +-- http-signature@1.1.1
	  | | +-- assert-plus@0.2.0
	  | | +-- jsprim@1.2.2
	  | | | +-- extsprintf@1.0.2
	  | | | +-- json-schema@0.2.2
	  | | | `-- verror@1.3.6
	  | | `-- sshpk@1.7.4
	  | |   +-- asn1@0.2.3
	  | |   +-- dashdash@1.13.0
	  | |   | `-- assert-plus@1.0.0
	  | |   +-- ecc-jsbn@0.1.1
	  | |   +-- jodid25519@1.0.2
	  | |   +-- jsbn@0.1.0
	  | |   `-- tweetnacl@0.14.1
	  | +-- is-typedarray@1.0.0
	  | +-- isstream@0.1.2
	  | +-- json-stringify-safe@5.0.1
	  | +-- mime-types@2.1.10
	  | | `-- mime-db@1.22.0
	  | +-- node-uuid@1.4.7
	  | +-- oauth-sign@0.8.1
	  | +-- qs@6.0.2
	  | +-- stringstream@0.0.5
	  | +-- tough-cookie@2.2.1
	  | `-- tunnel-agent@0.4.2
	  +-- rimraf@2.5.2
	  | `-- glob@7.0.3
	  |   +-- inflight@1.0.4
	  |   | `-- wrappy@1.0.1
	  |   +-- minimatch@3.0.0
	  |   | `-- brace-expansion@1.1.3
	  |   |   +-- balanced-match@0.3.0
	  |   |   `-- concat-map@0.0.1
	  |   +-- once@1.3.3
	  |   `-- path-is-absolute@1.0.0
	  +-- semver@2.2.1
	  +-- tar@0.1.20
	  | `-- block-stream@0.0.8
	  `-- which@1.2.4
		+-- is-absolute@0.1.7
		| `-- is-relative@0.1.3
		`-- isexe@1.1.2

**Comment by Pomax** [comment]
To be fair - 0.12.3 is now in maintenance-only mode, with the current LTS is 4.x (4.4 at the time of this comment), with the current stable 5.x (5.9 at the time of this comment), so still building for 0.12 is inadvisable.

**Comment by tmcw** [comment]
nwjs is not yet supported, main ticket is #497
