### ISSUE TITLE
General questions about sqlite3, install, concurrency, deployment

### ISSUE THREAD

**Issue by audiolion** [mapbox/node-sqlite3#616]
Hello, these are not issues but just things that I don't quite understand from reading documentation.

- sqlite3 dependency on visual studio 2010
  - with this requirement you need admin rights on your machine to install node-sqlite3 because there is no way to install visual studio without admin privileges as far as I know, correct?
  - visual studio 2010 doesn't seem to be offered on microsoft's website anymore, I followed the links in the Wiki for building on windows and the oldest version I can find is 2012, is this a problem/does documentation just need to be updated?
- installing sqlite3 and deploying
  - can I build sqlite3 as win32 or x64 and transfer the compiled files to another machine to run it
  - if not, how does deployment work, if you wanted to bundle in an electron app let's say and distribute
- concurrency
  - node-sqlite3 reads a database from a file into memory and executes queries on it to my understanding, if this is true, calling db.close would write the contents back to the disk at that time
  - how does concurrency work in this model? if you have many people each pulling the entire db into memory, making modifications, even if the updates are mutually exclusive, when each writes to the database will it copy over updates made to other mutually exclusive areas because those updates weren't present when the database was read into memory?

Any help is greatly appreciated! My goal is to build an electron app that uses a sqlite3 database on a server, it would then need to support concurrent access, sqlite3 support concurrency pretty well as an embedded db but I am not sure how node-sqlite3 implements it.

**Comment by springmeyer** [comment]
Visual studio is only needed for source compiles. I've updated https://github.com/mapbox/node-sqlite3/wiki/Building-on-Windows to make that more clear.

> can I build sqlite3 as win32 or x64 and transfer the compiled files to another machine to run it

https://github.com/mapbox/node-pre-gyp is designed to help solve this problem. Make sure you understand that tool in detail before continuing.

>  if you wanted to bundle in an electron app let's say and distribute

Electron should work, but we do not yet provide binaries for electron. So again, you'll want to learn node-pre-gyp to ensure that the binaries you build are versioned correctly.

> concurrency

See https://www.sqlite.org/lockingv3.html for details.

But in general concurrent writes are not a good idea with sqlite. Sqlite is great when you have serial writing and concurrent reads. You will likely hit SQLITE_BUSY errors if you try concurrent writes (see https://github.com/mapbox/node-sqlite3/issues/471). If you truly need concurrent writes then I would seriously consider a different database solution.

> sqlite3 support concurrency pretty well as an embedded db but I am not sure how node-sqlite3 implements it.

node-sqlite3 does nothing special. It just allows you to talk to sqlite3 via node.js. Sounds like you already understand concurrency with sqlite3 proper so you should expect things to behave similarly via node.js.

**Comment by audiolion** [comment]
thanks @springmeyer for the help in answering my questions. I am going to move to a client/server dbms because that fits the problem domain much better.

As to the building on windows, thanks for updating the doc to make that more clear. I must have had something wrong with my node-pre-gyp install then because, like most others I was getting the `node-pre-gyp install --fallback-to-build error`
I thought it was because it relied on the visual studio c++ compiler but it must have been something else. Thanks again

**Comment by springmeyer** [comment]
> I thought it was because it relied on the visual studio c++ compiler but it must have been something else.

Probably the compiler was not set up right. You usually need to run in the VS command prompt. Or python was not found. Could have been any number of things. This is why we provide binaries for most common node versions.
