### ISSUE TITLE
ENOENT: no such file or directory, chmod

### ISSUE THREAD

**Issue by eharrow** [mapbox/node-sqlite3#620]
Not sure where the issue is but I am unable to install sqlite3 in an ubuntu vagrant vm.  Any ideas what I have missed?

vagrant@vagrant-ubuntu-trusty-64:/vagrant/pushnotify-server$ `npm cache clean`
vagrant@vagrant-ubuntu-trusty-64:/vagrant/pushnotify-server$ `rm -rf node_modules/`
vagrant@vagrant-ubuntu-trusty-64:/vagrant/pushnotify-server$ `npm install sqlite3 --loglevel=info`
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.6.0
npm info attempt registry request try #1 at 11:21:49 AM
npm http request GET https://registry.npmjs.org/sqlite3
[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/193324/npm-debug.log.txt)

npm http 200 https://registry.npmjs.org/sqlite3
npm info addNameTag [ 'sqlite3', 'latest' ]
npm info retry fetch attempt 1 at 11:21:49 AM
npm info attempt registry request try #1 at 11:21:49 AM
npm http fetch GET https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.2.tgz
npm http fetch 200 https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.2.tgz
npm info attempt registry request try #1 at 11:21:54 AM
npm http request GET https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/nan
npm info retry fetch attempt 1 at 11:21:54 AM
npm info attempt registry request try #1 at 11:21:54 AM
npm http fetch GET https://registry.npmjs.org/nan/-/nan-2.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/nan/-/nan-2.2.0.tgz
npm info lifecycle nan@2.2.0~preinstall: nan@2.2.0
npm info lifecycle minimist@0.0.8~preinstall: minimist@0.0.8
npm info lifecycle mkdirp@0.5.1~preinstall: mkdirp@0.5.1
npm info lifecycle abbrev@1.0.7~preinstall: abbrev@1.0.7
npm info lifecycle nopt@3.0.6~preinstall: nopt@3.0.6
npm info lifecycle ansi@0.3.1~preinstall: ansi@0.3.1
npm info lifecycle delegates@1.0.0~preinstall: delegates@1.0.0
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle process-nextick-args@1.0.6~preinstall: process-nextick-args@1.0.6
npm info lifecycle string_decoder@0.10.31~preinstall: string_decoder@0.10.31
npm info lifecycle util-deprecate@1.0.2~preinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.0.6~preinstall: readable-stream@2.0.6
npm info lifecycle are-we-there-yet@1.1.2~preinstall: are-we-there-yet@1.1.2
npm info lifecycle has-unicode@2.0.0~preinstall: has-unicode@2.0.0
npm info lifecycle lodash.tostring@4.1.2~preinstall: lodash.tostring@4.1.2
npm info lifecycle lodash.repeat@4.0.0~preinstall: lodash.repeat@4.0.0
npm info lifecycle lodash.pad@4.1.0~preinstall: lodash.pad@4.1.0
npm info lifecycle lodash.tostring@4.1.2~preinstall: lodash.tostring@4.1.2
npm info lifecycle lodash.repeat@4.0.0~preinstall: lodash.repeat@4.0.0
npm info lifecycle lodash.padend@4.2.0~preinstall: lodash.padend@4.2.0
npm info lifecycle lodash.tostring@4.1.2~preinstall: lodash.tostring@4.1.2
npm info lifecycle lodash.repeat@4.0.0~preinstall: lodash.repeat@4.0.0
npm info lifecycle lodash.padstart@4.2.0~preinstall: lodash.padstart@4.2.0
npm info lifecycle gauge@1.2.7~preinstall: gauge@1.2.7
npm info lifecycle npmlog@2.0.3~preinstall: npmlog@2.0.3
npm info lifecycle deep-extend@0.4.1~preinstall: deep-extend@0.4.1
npm info lifecycle ini@1.3.4~preinstall: ini@1.3.4
npm info lifecycle minimist@1.2.0~preinstall: minimist@1.2.0
npm info lifecycle strip-json-comments@1.0.4~preinstall: strip-json-comments@1.0.4
npm info lifecycle rc@1.1.6~preinstall: rc@1.1.6
npm info lifecycle aws-sign2@0.6.0~preinstall: aws-sign2@0.6.0
npm info lifecycle pseudomap@1.0.2~preinstall: pseudomap@1.0.2
npm info lifecycle yallist@2.0.0~preinstall: yallist@2.0.0
npm info lifecycle lru-cache@4.0.0~preinstall: lru-cache@4.0.0
npm info lifecycle aws4@1.3.2~preinstall: aws4@1.3.2
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle process-nextick-args@1.0.6~preinstall: process-nextick-args@1.0.6
npm info lifecycle string_decoder@0.10.31~preinstall: string_decoder@0.10.31
npm info lifecycle util-deprecate@1.0.2~preinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.0.6~preinstall: readable-stream@2.0.6
npm info lifecycle bl@1.0.3~preinstall: bl@1.0.3
npm info lifecycle caseless@0.11.0~preinstall: caseless@0.11.0
npm info lifecycle delayed-stream@1.0.0~preinstall: delayed-stream@1.0.0
npm info lifecycle combined-stream@1.0.5~preinstall: combined-stream@1.0.5
npm info lifecycle extend@3.0.0~preinstall: extend@3.0.0
npm info lifecycle forever-agent@0.6.1~preinstall: forever-agent@0.6.1
npm info lifecycle async@1.5.2~preinstall: async@1.5.2
npm info lifecycle color-convert@1.0.0~preinstall: color-convert@1.0.0
npm info lifecycle ansi-styles@2.2.0~preinstall: ansi-styles@2.2.0
npm info lifecycle escape-string-regexp@1.0.5~preinstall: escape-string-regexp@1.0.5
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info lifecycle has-ansi@2.0.0~preinstall: has-ansi@2.0.0
npm info lifecycle ansi-regex@2.0.0~preinstall: ansi-regex@2.0.0
npm info lifecycle strip-ansi@3.0.1~preinstall: strip-ansi@3.0.1
npm info lifecycle supports-color@2.0.0~preinstall: supports-color@2.0.0
npm info lifecycle chalk@1.1.1~preinstall: chalk@1.1.1
npm info lifecycle graceful-readlink@1.0.1~preinstall: graceful-readlink@1.0.1
npm info lifecycle commander@2.9.0~preinstall: commander@2.9.0
npm info lifecycle generate-function@2.0.0~preinstall: generate-function@2.0.0
npm info lifecycle is-property@1.0.2~preinstall: is-property@1.0.2
npm info lifecycle generate-object-property@1.2.0~preinstall: generate-object-property@1.2.0
npm info lifecycle jsonpointer@2.0.0~preinstall: jsonpointer@2.0.0
npm info lifecycle xtend@4.0.1~preinstall: xtend@4.0.1
npm info lifecycle is-my-json-valid@2.13.1~preinstall: is-my-json-valid@2.13.1
npm info lifecycle pinkie@2.0.4~preinstall: pinkie@2.0.4
npm info lifecycle pinkie-promise@2.0.0~preinstall: pinkie-promise@2.0.0
npm info lifecycle har-validator@2.0.6~preinstall: har-validator@2.0.6
npm info lifecycle hoek@2.16.3~preinstall: hoek@2.16.3
npm info lifecycle boom@2.10.1~preinstall: boom@2.10.1
npm info lifecycle cryptiles@2.0.5~preinstall: cryptiles@2.0.5
npm info lifecycle sntp@1.0.9~preinstall: sntp@1.0.9
npm info lifecycle hawk@3.1.3~preinstall: hawk@3.1.3
npm info lifecycle assert-plus@0.2.0~preinstall: assert-plus@0.2.0
npm info lifecycle extsprintf@1.0.2~preinstall: extsprintf@1.0.2
npm info lifecycle json-schema@0.2.2~preinstall: json-schema@0.2.2
npm info lifecycle verror@1.3.6~preinstall: verror@1.3.6
npm info lifecycle jsprim@1.2.2~preinstall: jsprim@1.2.2
npm info lifecycle asn1@0.2.3~preinstall: asn1@0.2.3
npm info lifecycle assert-plus@1.0.0~preinstall: assert-plus@1.0.0
npm info lifecycle dashdash@1.13.0~preinstall: dashdash@1.13.0
npm info lifecycle jsbn@0.1.0~preinstall: jsbn@0.1.0
npm info lifecycle jodid25519@1.0.2~preinstall: jodid25519@1.0.2
npm info lifecycle ecc-jsbn@0.1.1~preinstall: ecc-jsbn@0.1.1
npm info lifecycle tweetnacl@0.14.1~preinstall: tweetnacl@0.14.1
npm info lifecycle sshpk@1.7.4~preinstall: sshpk@1.7.4
npm info lifecycle http-signature@1.1.1~preinstall: http-signature@1.1.1
npm info lifecycle is-typedarray@1.0.0~preinstall: is-typedarray@1.0.0
npm info lifecycle isstream@0.1.2~preinstall: isstream@0.1.2
npm info lifecycle json-stringify-safe@5.0.1~preinstall: json-stringify-safe@5.0.1
npm info lifecycle mime-db@1.22.0~preinstall: mime-db@1.22.0
npm info lifecycle mime-types@2.1.10~preinstall: mime-types@2.1.10
npm info lifecycle form-data@1.0.0-rc4~preinstall: form-data@1.0.0-rc4
npm info lifecycle node-uuid@1.4.7~preinstall: node-uuid@1.4.7
npm info lifecycle oauth-sign@0.8.1~preinstall: oauth-sign@0.8.1
npm info lifecycle qs@6.0.2~preinstall: qs@6.0.2
npm info lifecycle stringstream@0.0.5~preinstall: stringstream@0.0.5
npm info lifecycle tough-cookie@2.2.2~preinstall: tough-cookie@2.2.2
npm info lifecycle tunnel-agent@0.4.2~preinstall: tunnel-agent@0.4.2
npm info lifecycle request@2.69.0~preinstall: request@2.69.0
npm info lifecycle wrappy@1.0.1~preinstall: wrappy@1.0.1
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle balanced-match@0.3.0~preinstall: balanced-match@0.3.0
npm info lifecycle concat-map@0.0.1~preinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.3~preinstall: brace-expansion@1.1.3
npm info lifecycle minimatch@3.0.0~preinstall: minimatch@3.0.0
npm info lifecycle wrappy@1.0.1~preinstall: wrappy@1.0.1
npm info lifecycle once@1.3.3~preinstall: once@1.3.3
npm info lifecycle inflight@1.0.4~preinstall: inflight@1.0.4
npm info lifecycle path-is-absolute@1.0.0~preinstall: path-is-absolute@1.0.0
npm info lifecycle glob@7.0.3~preinstall: glob@7.0.3
npm info lifecycle rimraf@2.5.2~preinstall: rimraf@2.5.2
npm info lifecycle semver@5.1.0~preinstall: semver@5.1.0
npm info lifecycle ms@0.7.1~preinstall: ms@0.7.1
npm info lifecycle debug@2.2.0~preinstall: debug@2.2.0
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle balanced-match@0.3.0~preinstall: balanced-match@0.3.0
npm info lifecycle concat-map@0.0.1~preinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.3~preinstall: brace-expansion@1.1.3
npm info lifecycle minimatch@3.0.0~preinstall: minimatch@3.0.0
npm info lifecycle graceful-fs@4.1.3~preinstall: graceful-fs@4.1.3
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle fstream@1.0.8~preinstall: fstream@1.0.8
npm info lifecycle fstream-ignore@1.0.3~preinstall: fstream-ignore@1.0.3
npm info lifecycle wrappy@1.0.1~preinstall: wrappy@1.0.1
npm info lifecycle once@1.3.3~preinstall: once@1.3.3
npm info lifecycle core-util-is@1.0.2~preinstall: core-util-is@1.0.2
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
npm info lifecycle process-nextick-args@1.0.6~preinstall: process-nextick-args@1.0.6
npm info lifecycle string_decoder@0.10.31~preinstall: string_decoder@0.10.31
npm info lifecycle util-deprecate@1.0.2~preinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.0.6~preinstall: readable-stream@2.0.6
npm info lifecycle uid-number@0.0.6~preinstall: uid-number@0.0.6
npm info lifecycle graceful-fs@4.1.3~preinstall: graceful-fs@4.1.3
npm info lifecycle inherits@2.0.1~preinstall: inherits@2.0.1
npm info lifecycle fstream@1.0.8~preinstall: fstream@1.0.8
npm info lifecycle block-stream@0.0.8~preinstall: block-stream@0.0.8
npm info lifecycle tar@2.2.1~preinstall: tar@2.2.1
npm info lifecycle tar-pack@3.1.3~preinstall: tar-pack@3.1.3
npm info lifecycle node-pre-gyp@0.6.24~preinstall: node-pre-gyp@0.6.24
npm info lifecycle sqlite3@3.1.2~preinstall: sqlite3@3.1.2
npm info linkStuff nan@2.2.0
npm info linkStuff minimist@0.0.8
npm info linkStuff mkdirp@0.5.1
npm WARN pushnotify-server@1.0.0-SNAPSHOT No repository field.
npm WARN pushnotify-server@1.0.0-SNAPSHOT license should be a valid SPDX license expression
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3" "--loglevel=info"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path /vagrant/pushnotify-server/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/pushnotify-server/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/pushnotify-server/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/pushnotify-server/npm-debug.log

**Comment by eharrow** [comment]
I have found a work around http://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod using `--no-bin-links` which works but I don't know if there is an underlying defect or it is just one of those things.

**Comment by wbecker** [comment]
Same problem here, I just tried running `npm install --no-bin-links` but the issue still persists. Are you sure thats all you tried to fix it, or did you do something else as well?

**Comment by wbecker** [comment]
I got this working using `npm install --no-bin-links` but had to run `npm install -g node-pre-gyp` first.

**Comment by eharrow** [comment]
To be honest I may have done that as well at some point as over the course of a day I must have run npm install about 30 times.

As a follow up I did try a `npm install --no-bin-links` on a clean directory and it failed with a recursion issue in npm due to the --no-bin-links.  Of course being on a host with node already installed node-pre-gyp would have already been there if installed globally.  a `rm -rf node_modules` and then `npm rebuild` seemed to remove it.

**Comment by springmeyer** [comment]
Besides deleting package-lock.json the other workaround here is to upgrade to node-sqlite3@4.0.2, which should avoid this problem since it no longer uses bundledDependencies which trigger problems in recent npm versions > npm@5.6.x.

**Comment by mrgenesis** [comment]
> I got this working using `npm install --no-bin-links` but had to run `npm install -g node-pre-gyp` first.

This working for me. Thank you.
