### ISSUE TITLE
Build from source - Node-Webkit  0.14.2 Fails

### ISSUE THREAD

**Issue by craiglintott** [mapbox/node-sqlite3#636]
Am new to Node and Node -Webkit and am trying to build for the latest stable nwjs, but i get deprecation errors at the start as well has many more. The build fails with the attached log detail.

I am convinced my system configuration is now correct as it build just fine if the target is 0.12.3.

Any help would be greatly appreciated, as i have been trying to solve this for 3 days now without any luck

[npm-debug.zip](https://github.com/mapbox/node-sqlite3/files/241809/npm-debug.zip)

**Comment by tmcw** [comment]
nwjs is not yet supported, main ticket is #497
