### ISSUE TITLE
Node.js 6.x support

### ISSUE THREAD

**Issue by yisk** [mapbox/node-sqlite3#638]
Node.js v6.0.0, sqlite3 v3.1.3, Windows 10 x64.
I have an error "Cannot find module ...\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node".
There are only "node-v47-win32-x64" folder in ...\sqlite3\lib\binding .

**Comment by 10mitri** [comment]
Same problem as yisk with Windows10 x86.

**Comment by tswaters** [comment]
Because of the new V8 version, if you update to 6.0.0 you need to `npm rebuild` or delete node_modules and try again.

>Note that because this new version of Node.js is shipping with a new version of V8, you will need to recompile any native addons you have already installed or you will receive a runtime error when trying to load them. Use npm rebuild or simply remove your node_modules directory and npm install from scratch.

https://nodejs.org/en/blog/release/v6.0.0/

**Comment by yisk** [comment]
Well, I finally did it. That rebuilding was really tricky (Python2.7, Windows SDK-8.1, VS C++ tools).
Now I have a lot of deprecation warnings, but there is related issue already.

**Comment by olamedia** [comment]
What about `Cannot find module 'node_modules\sqlite3\lib\binding\node-webkit-v0.14.3-win32-x64\node_sqlite3.node'` while I have `node-v48-win32-x64`?

**Comment by frankhale** [comment]
Try rebuilding with nan 2.3.2 and the deprecation warnings should go away.

related issue: https://github.com/mapbox/node-sqlite3/issues/634

**Comment by yisk** [comment]
Yep, it helps.

**Comment by jaumard** [comment]
Any news on this ? Release date ? Because I can make it work locally but all CI tests are failing because of this error. 

```
Failed to execute '/home/travis/.nvm/versions/node/v6.1.0/bin/node /home/travis/.nvm/versions/node/v6.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/travis/build/trailsjs/trailpack-sequelize/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/travis/build/trailsjs/trailpack-sequelize/node_modules/sqlite3/lib/binding/node-v48-linux-x64' (1)
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.1.0/bin/node" "/home/travis/.nvm/versions/node/v6.1.0/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.1.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/trailsjs/trailpack-sequelize/npm-debug.log
The command "eval npm install " failed 3 times.
```
Full Travis build here https://travis-ci.org/trailsjs/trailpack-sequelize/jobs/129071450

**Comment by springmeyer** [comment]
node-sqlite3@3.1.4 has been released, which is the first one to support node v6.
