### ISSUE TITLE
remove stack trace

### ISSUE THREAD

**Issue by OlehZymnytskiy** [mapbox/node-sqlite3#639]
After installing sqlite3 package from npm my terminal is full of this stack trace. Why I see it? How to remove it?

==== JS stack trace =========================================

Security context: 0x1e993ebc9fa9 #0#
    1: .node [module.js:568] [pc=0x1e3962aa3c84] (this=0x14ceca9bad31 #1#,module=0x2f85be11f541 #2#,filename=0x2f85be11f509 )
    2: load [module.js:456] [pc=0x1e3962a38e72] (this=0x2f85be11f541 #2#,filename=0x2f85be11f509 )
    3: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1e3962a3899d] (this=0x1e993eb04189 ,module=0x2f85be11f541 #2#,filename=0x2f85be11f509 )
    4: _load [module.js:407] [pc=0x1e3962a345e2] (this=0x14ceca9badb1 #3#,request=0x2f85be1186c1 ,parent=0x14ceca9bd321 #4#,isMain=0x1e993eb04299 )
    5: require [module.js:466] [pc=0x1e3962a42573] (this=0x14ceca9bd321 #4#,path=0x2f85be1186c1 )
    6: require(aka require) [internal/module.js:20] [pc=0x1e3962a422a6] (this=0x1e993eb04189 ,path=0x2f85be1186c1 )
    7: /* anonymous */ [/home/oleh/node/node_modules/sqlite3/lib/sqlite3.js:4] [pc=0x1e3962a4795e] (this=0x14ceca9bd5b9 #5#,exports=0x14ceca9bd5b9 #5#,require=0x14ceca9bd3b1 #6#,module=0x14ceca9bd321 #4#,__filename=0x14ceca9bd569 ,__dirname=0x14ceca9bd541 )
    8: _compile [module.js:541] [pc=0x1e3962a41944] (this=0x14ceca9bd321 #4#,content=0x14ceca9bec19 #7#,filename=0x14ceca9bd569 )
    9: .js [module.js:550] [pc=0x1e3962a3a46b] (this=0x14ceca9bad31 #1#,module=0x14ceca9bd321 #4#,filename=0x14ceca9bd569 )
   10: load [module.js:456] [pc=0x1e3962a38e72] (this=0x14ceca9bd321 #4#,filename=0x14ceca9bd569 )
   11: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1e3962a3899d] (this=0x1e993eb04189 ,module=0x14ceca9bd321 #4#,filename=0x14ceca9bd569 )
   12: _load [module.js:407] [pc=0x1e3962a345e2] (this=0x14ceca9badb1 #3#,request=0x14ceca956b29 ,parent=0x14ceca9c0201 #8#,isMain=0x1e993eb04299 )
   13: require [module.js:466] [pc=0x1e3962a42573] (this=0x14ceca9c0201 #8#,path=0x14ceca956b29 )
   14: require(aka require) [internal/module.js:20] [pc=0x1e3962a422a6] (this=0x1e993eb04189 ,path=0x14ceca956b29 )
   15: /* anonymous */ [/home/oleh/node/sqlite3.js:1] [pc=0x1e3962a41c2b] (this=0x14ceca9c03b9 #9#,exports=0x14ceca9c03b9 #9#,require=0x14ceca9c0291 #10#,module=0x14ceca9c0201 #8#,__filename=0x14ceca9c0381 ,__dirname=0x14ceca9c0359 )
   16: _compile [module.js:541] [pc=0x1e3962a41944] (this=0x14ceca9c0201 #8#,content=0x14ceca9c0621 ,filename=0x14ceca9c0381 )
   17: .js [module.js:550] [pc=0x1e3962a3a46b] (this=0x14ceca9bad31 #1#,module=0x14ceca9c0201 #8#,filename=0x14ceca9c0381 )
   18: load [module.js:456] [pc=0x1e3962a38e72] (this=0x14ceca9c0201 #8#,filename=0x14ceca9c0381 )
   19: tryModuleLoad(aka tryModuleLoad) [module.js:415] [pc=0x1e3962a3899d] (this=0x1e993eb04189 ,module=0x14ceca9c0201 #8#,filename=0x14ceca9c0381 )
   20: _load [module.js:407] [pc=0x1e3962a345e2] (this=0x14ceca9badb1 #3#,request=0x14ceca9c0811 ,parent=0x1e993eb04101 ,isMain=0x1e993eb04231 )
   21: runMain [module.js:575] [pc=0x1e3962a340aa] (this=0x14ceca9badb1 #3#)
   22: startup(aka startup) [node.js:159] [pc=0x1e396294085e] (this=0x1e993eb04189 )
   23: /* anonymous */(aka /* anonymous */) [node.js:444] [pc=0x1e396293e4f2] (this=0x1e993eb04101 ,process=0x1e993ebe4d89 #11#)

==== C stack trace ===============================

 1: v8::Template::Set(v8::Local, v8::Local, v8::PropertyAttribute)
 2: node_sqlite3::Statement::Init(v8::Local)
 3: 0x7f81237df4b6
 4: node::DLOpen(v8::FunctionCallbackInfo const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo const&))
 6: 0x98b90b
 7: 0x98beb1
 8: 0x1e396290961b

**Comment by yisk** [comment]
This is deprecation warnings I guess. Same as here https://github.com/mapbox/node-sqlite3/issues/634.

**Comment by OlehZymnytskiy** [comment]
Thanks.
