### ISSUE TITLE
install fails for node 6.1.0

### ISSUE THREAD

**Issue by gerry-eagle** [mapbox/node-sqlite3#648]
Fails when I tried to install on node 6.1.0 / npm 3.8.9 on Windows 10. Get the following output...

      D:\Research\Motorola\Test\Test>npm -v
    3.8.9

    D:\Research\Motorola\Test\Test>npm install sqlite3 --save

    > sqlite3@3.1.3 install D:\Research\Motorola\Test\Test\node_modules\sqlite3
    > node-pre-gyp install --fallback-to-build

    D:\Research\Motorola\Test\Test\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Users\gzs.EAGLE\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

    D:\Research\Motorola\Test\Test\node_modules\sqlite3>if not defined npm_config_node_gyp (node "C:\Users\gzs.EAGLE\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64 )  else (node "" configure --fallback-to-build --module=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64 )
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at failNoPython (C:\Users\gzs.EAGLE\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
    gyp ERR! stack     at C:\Users\gzs.EAGLE\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
    gyp ERR! System Windows_NT 10.0.10240
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gzs.EAGLE\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Research\\Motorola\\Test\\Test\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\Research\\Motorola\\Test\\Test\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64"
    gyp ERR! cwd D:\Research\Motorola\Test\Test\node_modules\sqlite3
    gyp ERR! node -v v6.1.0
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Research\Motorola\Test\Test\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
    node-pre-gyp ERR! System Windows_NT 10.0.10240
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Research\\Motorola\\Test\\Test\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\Research\Motorola\Test\Test\node_modules\sqlite3
    node-pre-gyp ERR! node -v v6.1.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.25
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\Research\Motorola\Test\Test\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
    npm WARN test@0.0.0 No repository field.
    npm WARN test@0.0.0 No license field.
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gzs.EAGLE\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "sqlite3" "--save"
    npm ERR! node v6.1.0
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE

    npm ERR! sqlite3@3.1.3 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sqlite3@3.1.3 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the sqlite3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs sqlite3
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls sqlite3
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\Research\Motorola\Test\Test\npm-debug.log

**Comment by jaumard** [comment]
Same on travis build https://travis-ci.org/trailsjs/trailpack-sequelize/jobs/129863647

**Comment by Mklueh** [comment]
Same here on Windows 8.1 and Ubuntu Server

**Comment by springmeyer** [comment]
node-sqlite3@3.1.4 has been released, which is the first one to support node v6.

**Comment by gerry-eagle** [comment]
Thank Dane, installs fine now :+1:
