### ISSUE TITLE
CAST returns a strange response

### ISSUE THREAD

**Issue by IrosTheBeggar** [mapbox/node-sqlite3#650]
I'm working with a databases that stores some text as a BLOB.  I tried this string to get the data:
`  "SELECT title, CAST( path as TEXT) FROM items LIMIT 1;"
`

I get the following object back:
```
[{
    title: 'First File',
    'CAST( path as TEXT)': '/Users/admin/file1.txt',
}]
```

How can I get it to return a key that it not a SQL command?

**Comment by kroggen** [comment]
use `"SELECT title, CAST(path as TEXT) as filepath FROM items LIMIT 1;"`
