### ISSUE TITLE
Problem when promisify `run`

### ISSUE THREAD

**Issue by zweifisch** [mapbox/node-sqlite3#658]
Currently the callback argument for `run` only accept one parameter, namely `err`, and `lastID` and `changes` can be get from `this` inside the callback. When promisify using tools like bluebird, things like `lastID` are lost. It would be nice to have those passed to the callback as the second argument, and this is also a nodejs convention I believe.

**Comment by pabigot** [comment]
@rnewman Thanks.  For others coming in late the link in the above comment is dead and the capability is now available as [promise-sqlite](https://www.npmjs.com/package/promise-sqlite).

**Comment by tmcw** [comment]
We'd happily review a PR that implements lastID in the results object, but for now, you can use a library like [pify](https://github.com/sindresorhus/pify) that accepts a `multiArgs` option to successfully pass multiple arguments into a Promise object.

**Comment by fasiha** [comment]
@tmcw can I get some additional information on using `pify` with sqlite3? When I adapt the README's example as such:
```js
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');
var pify = require('pify');

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
  for (var i = 0; i < 10; i++) { stmt.run("Ipsum " + i); }
  stmt.finalize();

  db.get("SELECT * FROM lorem", function(err, row) { console.log('err', err, 'row', row); });

  pify(db.get, {multiArgs: true})("SELECT * FROM lorem")
      .then(x => console.log('promise', x))
      .catch(e => console.log('promise error', e));
});

db.close();
```
the callback works but promisified `get` fails, with this error: `promise error TypeError: Database object expected`. This actually happens even if I omit the `multiArgs` option.

Has something changed in the last couple of years in sqlite3 that prevents `pify` from working, or am I doing something wrong?

**Comment by fasiha** [comment]
Sorry for bugging you all. I realized it was a `this`/`bind` issue. Both
- `(pify(db).get.bind(db))("select * from lorem").then // ...` and
- `pify(db.get.bind(db))("select * from lorem").then // ...`

work as expected.
