### ISSUE TITLE
Feature request: provide pre-compiled binaries (official builds) in npm packages

### ISSUE THREAD

**Issue by Mithgol** [mapbox/node-sqlite3#67]
Currently `npm install sqlite3` requires building node-sqlite3 from the source with node-gyp (on Windows the prerequisites are Python and MSVC, the latter is huge).

To get rid of this requirement (and thus to attract more end users and less building-related issues reported), please accomplish the following:
1. Require (and use) [node-bindings](https://github.com/TooTallNate/node-bindings/).
2. Compile binary part of node-sqlite3 for the supported platforms (win32/ia32, darwin/x64, linux/ia32, linux/x64... sunos/ia32?), put the resulting binaries inside your npm package and let node-bindings pick one on user's side.
3. Put `binding.gyp` in `.npmignore`, otherwise npm will still attempt to build from the source. (Do not forget to add some contents of `.gitignore` to `.npmignore` when you create the latter, but only some: npm should not ignore the binaries.)
4. _(optional)_ Put binaries in `.gitignore` to prevent them from being hosted on GitHub. (This step is necessary only if you hate mixing sources with binaries. This step may also be completed already if you build in `build/`, which is currently in `.gitignore`.)

After that `npm install sqlite3` would involve only downloading and unpacking, and thus would _just work._

**Comment by michael-ts** [comment]
I am experiencing a problem with the link to [pre-compiled binaries]( http://node-sqlite3.s3.amazonaws.com/index.html) provided here and from the documentation.  The page just says "loading..." but it never does.  If I bring up Chrome developer tools there are two errors:

- Mixed Content: The page at 'https://node-sqlite3.s3.amazonaws.com/index.html?path=Release/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
- index.html?path=Release/:16 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ index.html?path=Release/:16

Is there a new updated URL to obtain the binaries?

Also, are there pre-compiled binaries with sqlcipher support?  I'm trying to get this working in Windows 10 and the pre-requisites are ridiculous.  I'm sure a lot of people would appreciate not having to go through this.
