### ISSUE TITLE
Failed to install v3.0.3+ on ARMv6 (like Raspi A)

### ISSUE THREAD

**Issue by TomFreudenberg** [mapbox/node-sqlite3#671]
Hi, I am maintaining the [meteor.js universal fork for running meteor on ARM](https://github.com/4commerce-technologies-AG/meteor). Therefor node-sqlite3 is used long time. Although the newest releases are working on ARMv7 and ARMv8 (Aarch64) the npm could not be installed on ARMv6 anymore.

Currently used (must be) is nodejs v0.10.45 and npm 2.15.1. 
OS is latest raspbian which is Debian jessie armh

When installing `sqlite3@3.0.2` all is fine but if installing `sqlite3@3.0.3` or later it breaks - see attached output.

I am using `sqlite3@3.1.3` without any issues on armv7 (Ubuntu 14.04) and armv8 (Ubuntu xenial).

ERROR LOG:

<pre>
PATH=$PATH:/tmp/node/bin npm install sqlite3@3.0.6
-
> sqlite3@3.0.6 install /tmp/node/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.45"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/sqlite3/.node-gyp"
make: Entering directory '/tmp/node/node_modules/sqlite3/build'
make: *** No rule to make target '../.node-gyp/0.10.45/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/tmp/node/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/node/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.4.13+
gyp ERR! command "/tmp/node/bin/node" "/tmp/node/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm"
gyp ERR! cwd /tmp/node/node_modules/sqlite3
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/tmp/node/bin/node /tmp/node/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/node/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.4.13+
node-pre-gyp ERR! command "node" "/tmp/node/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/node/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.45
node-pre-gyp ERR! node-pre-gyp -v v0.6.5
node-pre-gyp ERR! not ok
Failed to execute '/tmp/node/bin/node /tmp/node/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node/node_modules/sqlite3/lib/binding/node-v11-linux-arm' (1)
npm ERR! Linux 4.4.13+
npm ERR! argv "/tmp/node/bin/node" "/tmp/node/bin/npm" "install" "sqlite3@3.0.6"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node/npm-debug.log
</pre>

**Comment by TomFreudenberg** [comment]
When I clone the repo and run:

```
git clone https://github.com/mapbox/node-sqlite3.git

cd node-sqlite3

git checkout v3.1.3

npm install nan node-pre-gyp
```

and then start the build via:

```
./node_modules/node-pre-gyp/bin/node-pre-gyp rebuild
```

everything gets built

**Comment by xbolshe** [comment]
It looks like a file access problem:

> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.45"

**Comment by TomFreudenberg** [comment]
No, its not that problem. Will use temporary path even that root normally has full access to everywhere

<pre>
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/node/node_modules/sqlite3/.node-gyp"
</pre>

**Comment by xbolshe** [comment]
But a temporary path does not allow to find '../.node-gyp/0.10.45/include/node/common.gypi'
Have you tried to check rights for "/root/.node-gyp/0.10.45" ?

> make: Entering directory '/tmp/node/node_modules/sqlite3/build'
> make: *** No rule to make target '../.node-gyp/0.10.45/include/node/common.gypi', needed by 'Makefile

**Comment by TomFreudenberg** [comment]
Problem is located at `package.json` when switching from release v3.0.2 to release v3.0.3 this line:

```
"node-pre-gyp": "~0.5.27"
```

to

```
"node-pre-gyp": "~0.6.0"
```

Even if I change the `node-pre-gyp` dependency at latest release v3.1.4 back to `~0.5.27` everything works fine.

So it is an error due node-pre-gyp package :-(

**Comment by TomFreudenberg** [comment]
Well, after testing the different `node-pre-gyp` packages, the issue occurs when using

```
"node-pre-gyp": "0.6.4" (or newer)
```

if changing back to

```
"node-pre-gyp": "0.6.3" (or previous)
```
