### ISSUE TITLE
Support variadic SET parameters in UPDATE statements

### ISSUE THREAD

**Issue by raphaeltraviss** [mapbox/node-sqlite3#672]
There should be a way to handle multiple statements in the SET section of a query string, without knowing them beforehand.

For example, if a user only supplied "param1" and nothing else, we would want to SET param1 = value1.  If a user supplied "param1" and "param2", we would want SET param1 = value1, param2 = value2.

```javascript
var updateFields = [];
if (typeof body.param1 != 'undefined') {
    updateFields.push("param1 = '" + body.param1 + "'");
}
if (typeof body.param2!= 'undefined') {
    updateFields.push("param2 = '" + body.param2 + "'");
}

const updateString = updateFields.join(", ");

// SQL injection possible here.
db.get("UPDATE mytable SET " + updateString + " WHERE id = ?", [my_id], function(err, row) {
    // do stuff
});
```

**Comment by kroggen** [comment]
Hi Tesla!

You can use something like this:

```javascript
var fields = [], values = [];

if (typeof body.param1 != 'undefined') {
    fields.push('param1 = ?')
    values.push(body.param1)
}
if (typeof body.param2 != 'undefined') {
    fields.push('param2 = ?')
    values.push(body.param2)
}

if (fields.length == 0) return;

values.push(my_id)

db.run("UPDATE mytable SET " + fields.join(',') + " WHERE id = ?", values, function(err) {
    // do stuff
});
```
Or you can use the [sqlite3-wrapper](https://github.com/vladimirfedorov/sqlite3-wrapper). Check also my [fork](https://github.com/kroggen/sqlite3-wrapper/commits/master) that has the update arguments in different order, among other changes.

**Comment by raphaeltraviss** [comment]
Ah, clever!  That should work just fine, thanks!

Don't tell Thomas Edison that I was here!
