### ISSUE TITLE
`SELECT ROWID` doesn't return rowid

### ISSUE THREAD

**Issue by jameslaneconkling** [mapbox/node-sqlite3#676]
```javascript
db.all(`SELECT ROWID, otherField FROM table`)
```

returns: (ROWID is missing)
```json
[
  { "otherField": "value"},
  ...
]
```

**Workaround**:

```javascript
db.all(`SELECT ROWID as rowid, otherField FROM table`)
```

returns: (ROWID is not missing)
```json
[
  { "rowid": 1, "otherField": "value"},
  ...
]
```

**Comment by kroggen** [comment]
Show the command used to create the table.

In the sqlite3 shell run: `.schema tablename`

Note that newer versions of SQLite support tables without RowIDs.

An also that if a table is created with a field with type `INTEGER PRIMARY KEY` then it becomes the primary key. eg.:

`CREATE TABLE test (id INTEGER PRIMARY KEY, name TEXT)`

That does not have a field named "rowid".

**Comment by jameslaneconkling** [comment]
Ah, hadn't realized `ROWID` was just an alias of `INTEGER PRIMARY KEY`.  Thus why it doesn't work w/ subqueries.

Even still, I would have expected it to return from the query if it was included in the `SELECT` statement, even if it was just aliasing `id`.

Thanks for the help.
