### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by dmitrymakhnin** [mapbox/node-sqlite3#679]
fails on `npm install(with package.json)` and `npm install sqlite`.
1. err.txt contains &> dump
2. npm-debug.log.txt is npm-debug.log generated by the installation process, .txt was appended because git drag input rejects .log file extension.

[err.txt](https://github.com/mapbox/node-sqlite3/files/375176/err.txt)
[npm-debug.log.txt](https://github.com/mapbox/node-sqlite3/files/375177/npm-debug.log.txt)

**Comment by Ranzear** [comment]
Try installing with --unsafe-perm

For me it was an issue with non-root access to some non-app path even if not installing with -g

**Comment by kreig303** [comment]
Thanks for this, I had a hanging install which this fixed!
