### ISSUE TITLE
npm install sqlite3 fails on Ubuntu 12.04 using Node v4.2.0

### ISSUE THREAD

**Issue by karloespiritu** [mapbox/node-sqlite3#683]
I'm trying to install Ghost v0.9 on Ubuntu 12.04 using Node v4.2.0 and I'm always getting the following error during `npm install of sqlite3` (v3.1.4): 

```bash
$ npm install sqlite3

> sqlite3@3.1.4 install /var/www/ghost/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v46-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@4.2.0 (node-v46 ABI) (falling back to source compile with node-gyp)
make: Entering directory `/var/www/ghost/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3090100/sqlite3.c
```
When I tried  to manually access -- [https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v46-linux-ia32.tar.gz](https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v46-linux-ia32.tar.gz), it returns 'Access Denied'.

**Comment by asianboiFRC** [comment]
I am having the same problem.

**Comment by xditx32** [comment]
me, too. no way out resolved?

**Comment by ayxos** [comment]
me too

**Comment by ErisDS** [comment]
There are no longer any pre-built binaries supplied for this package for 32bit linux.

The available solutions are to either switch to 64bit linux, or follow the [install guide](https://github.com/mapbox/node-sqlite3#installing) for how to setup your environment and compile your own binary.
