### ISSUE TITLE
Documentation Mismatch

### ISSUE THREAD

**Issue by wachauski** [mapbox/node-sqlite3#684]
Hello. Thanks for all the amazing work here!
I have a recommendation for making the web site better.  On the web page https://github.com/mapbox/node-sqlite3/wiki/Binaries, it states instructions for installing by using "npm install sqlite3 --build-from-source=sqlite3".  Yet on the the other web page: https://github.com/mapbox/node-sqlite3/wiki/Building-On-Windows, you have different instructions: "npm install sqlite --build-from-source".  I followed both and found the former to be the more useful or at least more correct for installing on Windows 7, 64-bit, but only after losing several hours trying to get the instructions on the latter web page.  Please make your instructions consistent.  

Again, thanks for providing this package!

**Comment by tmcw** [comment]
Thanks, fixed
