### ISSUE TITLE
Installation for node v4.4.7 fails

### ISSUE THREAD

**Issue by compengi** [mapbox/node-sqlite3#694]
Installation fails to install sqlite 3.1.4. Compilation fails as well.

Log:
https://gist.github.com/compengi/d5f3f233f00b715ab894829654f88efa

**Comment by springmeyer** [comment]
Looks like you are on a 32 bit machine. We don't provide binaries for 32 bit anymore (looks like our support for that may have broken) so the build is falling back to a source compile. The source compile is failing because you need a more recent compiler installed, like clang >= 3.5 or g++ >= 4.8.

**Comment by compengi** [comment]
Thank you! Installing g++ 4.8 resolved this issue. For documentation purposes reguarding how to install g++ 4.8 on ubuntu, please refer to this link: http://askubuntu.com/questions/271388/how-to-install-gcc-4-8
