### ISSUE TITLE
can not find database *.db

### ISSUE THREAD

**Issue by cybibo** [mapbox/node-sqlite3#695]
sqlite = require("sqlite3")
// Initialize sqlite and create our db if it doesnt exist
var sqlite3 = require("sqlite3").verbose();
var db = new sqlite3.Database(__dirname+'/db/bb-login.db');

but can not find bb-login.db;

node:
sqlite3:"version": "3.1.4",
node:version:4.2.1
express:3.21.2

**Comment by kroggen** [comment]
You must write to the database so the file is created
