### ISSUE TITLE
Automatic parsing values from tables

### ISSUE THREAD

**Issue by kroggen** [mapbox/node-sqlite3#700]
Hi everyone!

I have some suggestions:

SUGGESTION 1: Include part of the [sqlite3-wrapper](https://github.com/vladimirfedorov/sqlite3-wrapper) code in the node-sqlite3 project, at least the functions to `update` and `insert` records.

Note that these functions accept javascript objects:

```javascript
var user = {name: 'John', email: 'john@gmail.com', other: [{...}, {...}], obj: {...}}

db.insert('users', user, function(error, id) {
    // error: sqlite3 error
    // id: id of the created row
})

db.update('users', user, {id: user.id}, function(error, changes) {
    // error: sqlite3 error
    // changes: number of rows updated (if any)
})
```

[My fork](https://github.com/vladimirfedorov/sqlite3-wrapper/network) works slightly different from the @vladimirfedorov's original version. Mainly the arguments order in the `db.update` function.

We can't change the original version due to backward compatibility.

SUGGESTION 2: To automatically convert values from a record when saving or retrieving from the database.

In the above example it shows the conversion when saving a record.

In this case the lib will convert javascript objects and arrays to a JSON string and save it in the table.

The same must be done to boolean values (true and false).

Note that my fork of sqlite3-wrapper is already making the conversion when saving but it lacks the conversion when loading a record.

In this last case the data in the table must be converted back (parsed) from string to a valid javascript value.

How to know when to parse and when to keep the original value?

Using these rules:

1. If the column is declared as `JSON` then it tries to parse. Otherwise it returns the stored string.
2. If the parsing fails, it returns the original string.
3. If the column is declared as `BOOL` AND the content is of type `INTEGER` then it tries to convert to true or false.

So the tables must be created like this:

```
CREATE TABLE users (
id INTEGER PRIMARY KEY,
name TEXT,
other JSON,    <-- automatically parsed
active BOOL    <-- automatically parsed
)
```

I have already implemented the code to make the conversion in the load process, inside the node-sqlite3 library. It is working with node 0.10, but I guess it needs to be converted do NAN. And as I am not a C++ developer I need the help of someone.

You can check the code in [this fork](https://github.com/kroggen/node-sqlite3/commits/master).

Note that it is calling `JSON.parse()` from C++ via v8. I guess the v8 has no more such parser at C++ level so it needs to do that.

Note also that the parser is currently in a separate file (named [v8_json.cc](https://github.com/kroggen/node-sqlite3/blob/master/src/v8_json.cc)) but it can be merged with statement.cc if it's better.

What do you think about it?

**Comment by kroggen** [comment]
Another option would be to use the Whitney Young [method](https://github.com/mapbox/node-sqlite3/pull/451): retrieve the column declared type from C++ to the javascript level and then make the parsing there.

@wbyoung what do you think?

**Comment by orangebook** [comment]
I also have same proble me 
no such column

**Comment by orangebook** [comment]
that have error,but how to call back.there is no tips

**Comment by orangebook** [comment]
I think that nice,there is so much db driver.such as mongoose ,ORM that is nice

**Comment by wbyoung** [comment]
@kroggen I think that's really a question for the maintainers of the project.

**Comment by tmcw** [comment]
Thanks for the suggestion! Users are free to use [sqlite3-wrapper](https://github.com/vladimirfedorov/sqlite3-wrapper) in their projects, but this library aims to be a low-level binding to sqlite, rather than an ORM or higher-level abstraction for types.
