### ISSUE TITLE
how to get the value of Database#all(sql, [param, ...], [callback])

### ISSUE THREAD

**Issue by imzzy** [mapbox/node-sqlite3#704]
hi ,i am newer to use node-sqlite3. when use the  fucntion all()  select all the data .i just can get the value in the [callback], however, i want get the value of exec sql in another function, but how can i to do? thanks.

this is my code.
`function queryGetAll(){

  db.all("select * from tempdata",function(err,row){
    console,log(row);
  });

}`

and  i want use  row of the function queryGetAll() i get it to another function , i wish i can return the value of row of queryGetAll().   who can help me ? thanks. :)

**Comment by tmcw** [comment]
Hi @imzzy,

Sure, you cannot return data that is passed through an async callback through the normal 'return' statement in Node.js. Refer to [callbackhell](http://callbackhell.com/) for more information: specifically, you'd have `queryGetAll` also take a callback, and call that callback with the data.

- Tom
