### ISSUE TITLE
Shared Cache policy

### ISSUE THREAD

**Issue by ncortines** [mapbox/node-sqlite3#710]
Hi,

would you please comment on this topic?

https://www.sqlite.org/c3ref/enable_shared_cache.html

What is the current policy?

Thanks

**Comment by tmcw** [comment]
Thanks for the question. `node-sqlite3` doesn't call this method and thus should have the default shared cache setting of 'off'. We're happy to review and accept a PR that makes this option configurable if it's important to you.
