### ISSUE TITLE
Dynamically building parametrized statement

### ISSUE THREAD

**Issue by dzbanek** [mapbox/node-sqlite3#721]
Why this one isn't working?
```
var select = 'SELECT ... FROM ... where ...';
var pars = [];

db.serialize(function () {
                db.each("SELECT id FROM FilteredCountries", function (error, row) {
                    select = select + " and ... = ?";
                    pars.push('CA');
                });

                db.each(select, pars, function (err, row) {
                    result.push({
                        ...
                    });
                }, function () {                    
                    res.end(JSON.stringify(result));
                });

            });
```
I mean second db.each got called with just basic 'select from where' statement. If I move 

```
 select = select + " and ... = ?";
                    pars.push('CA');
```

before serialize it will work just fine, but I want to build my statement using data from database.

What am I doing wrong?

**Comment by kroggen** [comment]
Try this instead:
```javascript
db.serialize(function () {
    db.each("SELECT id FROM FilteredCountries", function (error, row) {
        select = select + " and ... = ?";
        pars.push('CA');
        db.each(select, pars, function (err, row) {
            result.push({
                ...
            });
        }, function () {                    
            res.end(JSON.stringify(result));
        });
    });
});
```

**Comment by dzbanek** [comment]
That doesn't seem right. Correct me, if I'm wrong, but I believe it will try to run multiple statements, one for each row from FilteredCountries. 
I'm trying to get those rows first and then run single statement with where conditions populated from them.

**Comment by kroggen** [comment]
Oh, sorry! I did not notice that. You are right.

The first SELECT should use `db.all` instead.

The callback will receive an array of rows that can be used to build the new query string.
```javascript
rows.forEach(function(row) {
    select += ...
    pars.push(...);
});
```

**Comment by dzbanek** [comment]
It doesn't matter if I use db.all in first select and iterate through rows or db. each as I did in my example. The second select will still use original strings:

```
var select = 'SELECT ... FROM ... where ...';
var pars = [];
```

I'm still noob in node, but I think second select statement is built and added to queries flow before first one ends and that's why it's not updated when select and pars are changed.

I hope it's clear now what I'm asking about.

**Comment by dzbanek** [comment]
I forgot to say that using callback from first select to run second one doesn't make any difference.

But I'm leaving this problem behind, I'll move storing my filters to client side. Tbh I have no idea why I wanted to do it on server side.

**Comment by kroggen** [comment]
No. The second db.each must be AFTER the iteration on the results, like this:

```javascript
db.serialize(function () {
    db.all("SELECT id FROM FilteredCountries", function (error, rows) {
        rows.forEach(function(row) {
            select += ...
            pars.push(...);
        });
        db.each(select, pars, function (err, row) {
            result.push({
                ...
            });
        }, function () {                    
            res.end(JSON.stringify(result));
        });
    });
});
```

or this loop instead of forEach:

```javascript
      for(var i=0; i < rows.length; i++) {
            select += ... rows[i] ...
      }
```
