### ISSUE TITLE
Upgrade to SQLite to latest release.

### ISSUE THREAD

**Issue by rnewman** [mapbox/node-sqlite3#722]
`node-sqlite3` ships with sqlite 3.9.1, which was released almost exactly a year ago.

At the very least, this should be the 3.9.3 branch release, which includes two fixes and a backported performance improvement.

Ideally it should be 3.14.2, which includes performance improvements and a year of other work.

**Comment by springmeyer** [comment]
Yes, can upgrade when we make a new release. In the meantime you can easily source compile node-sqlite3 against your own version of libsqlite3 like https://github.com/mapbox/node-sqlite3#source-install

**Comment by wmertens** [comment]
@springmeyer is there anything I can do to help with doing the next release? Issue wrangling, PR reviews, …?

**Comment by rnewman** [comment]
I suggest taking #724 instead.

**Comment by springmeyer** [comment]
Thanks, agree, done in #724
