### ISSUE TITLE
Support for Node 7?

### ISSUE THREAD

**Issue by mikeptweet** [mapbox/node-sqlite3#728]

**Comment by mikeptweet** [comment]
When can we expect this?

**Comment by bkimminich** [comment]
For me `sqlite3` installs **just fine** wth 7.0.0 for:
- Docker image based on `node:7`
- CI-builds run on AppVeyor (Windows)

It **fails** on the other hand for:
- Travis-CI builds
- Local `npm install` on Windows 10

(see https://github.com/bkimminich/juice-shop/issues/228)

**Comment by djhi** [comment]
Same here, working fine locally but failing on travis

**Comment by tmcw** [comment]
Can someone link a failed Travis build to give us context for what the specific build error is?

**Comment by bkimminich** [comment]
Sure thing:
* Travis (failing): https://travis-ci.org/bkimminich/juice-shop/jobs/170966743
* AppVeyor (passing): https://ci.appveyor.com/project/bkimminich/juice-shop/build/705/job/fvt1q2epcywd289x

**Comment by tmcw** [comment]
The relevant line from that Travis test is:

> This version of node/NAN/v8 requires a C++11 compiler

Maybe try [installing a newer gcc](https://jsteemann.github.io/blog/2014/10/17/using-travis-ci-for-a-c-plus-plus-11-project/) and seeing if the errors change?

**Comment by bkimminich** [comment]
Seems to be the same/a similar underlying issue I have on my local Windows machine:

```
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm▒glichen, m▒ssen Sie den Schalter "/m" hinzuf▒gen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f▒gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Data\Github\juice-shop\node_modules\sqlite3\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bjoern.kimminich\AppData\Roaming\nvm\v7.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\bjoern.kimminich\\AppData\\Roaming\\nvm\\v7.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Data\\Github\\juice-shop\\node_modules\\sqlite3\\lib\\binding\\node-v51-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Data\\Github\\juice-shop\\node_modules\\sqlite3\\lib\\binding\\node-v51-win32-x64"
gyp ERR! cwd C:\Data\Github\juice-shop\node_modules\sqlite3
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Data\Github\juice-shop\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Data\Github\juice-shop\node_modules\sqlite3\lib\binding\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Data\Github\juice-shop\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601

```
(It seems AppVeyor have a better Windows setup than me... :grin:)

**Comment by xhallix** [comment]
Yep same here, only works with node-pre-gyp because binary is missing
```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
```

**Comment by bkimminich** [comment]
I'm just checking https://github.com/nodejs/node-gyp#installation to see what's missing on my end...

**Comment by springmeyer** [comment]
I'm working on publishing binaries for v7 for osx and linux and windows. They will be ready in about ~30 min.

**Comment by xhallix** [comment]
wow thanks a lot ! thats great

**Comment by xhallix** [comment]
I was trying to do that and provide it as a PR but failing miserably because somehow i cannot get rid of `gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp`

**Comment by bkimminich** [comment]
@springmeyer This is the kind of support you would want (but never get) from enterprise grade products... :smiling_imp: Big thanks!

**Comment by bkimminich** [comment]
@tmcw On Travis it works for me now after installing gcc. Thanks! (https://travis-ci.org/bkimminich/juice-shop/builds/171144010)

**Comment by xhallix** [comment]
@bkimminich maybe take a look here for your windows machine. this fixed it for me some times ago 
http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012

**Comment by springmeyer** [comment]
v3.1.8 is now released with binaries for node v7

**Comment by 10mitri** [comment]
Hello,
Sorry but I have the same problem with Windows 7.
Installation of 3.1.8 is OK. But when I run node I get :

Error: Cannot find module 'D:\node.js\node_modules\sqlite3\lib\binding\node-v51-win32-ia32\node_sqlite3.node'

Effectivley there is no ..\node-v**51**-win32-ia32 directory, but ..\node-v**48**-win32-ia32
