### ISSUE TITLE
error sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by nithumahi** [mapbox/node-sqlite3#733]
I am getting following error while installing sqlite in machine 

41213 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
41214 error node v5.10.1
41215 error npm  v3.8.6
41216 error code ELIFECYCLE
41217 error sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
41217 error Exit status 1
41218 error Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
41218 error Make sure you have the latest version of node.js and npm installed.
41218 error If you do, this is most likely a problem with the sqlite3 package,
41218 error not with npm itself.
41218 error Tell the author that this fails on your system:
41218 error     node-pre-gyp install --fallback-to-build
41218 error You can get information on how to open an issue for this project with:
41218 error     npm bugs sqlite3
41218 error Or if that isn't available, you can get their info via:
41218 error     npm owner ls sqlite3
41218 error There is likely additional logging output above.
41219 verbose exit [ 1, true ]

**Comment by springmeyer** [comment]
That is not enough of an error log to help you debug the failure. You will need to post more of the output of your terminal. However I'll say that usually `ELIFECYCLE` means you are running as root, which is not supported by `npm` unless you pass the `--unsafe-perm` flag.

**Comment by ottomen** [comment]
I have the same issue. 
"node-pre-gyp install --fallback-to-build"
