### ISSUE TITLE
Question about returned json

### ISSUE THREAD

**Issue by gbrault** [mapbox/node-sqlite3#736]
Thanks for the job first!

I have a question, you opted for a format of responses which is an array of objects, each being properties named after db fields.

Let me show an example

given a Table Test like this

id   value
1       bon
2       grand
3       petit

Applying <SELECT * FROM  Test> will provide a result like this
[{"id":1,"value":"bon"},{"id":2,"value":"grand"},{"id":3,"value":"petit"}]

I would rather like to have a result formatted this way:
{"columns":["id","value"], "values":[[1,"bon"],[2,"grand"],[3,"petit"]]}

Where do I have to look to make an option to format results according to sqlite3 as today and the option I just show (which is the sql.js way)?

The idea is to make the output of sqlite3 compatible with the one of sql.js...

Thanks for your help

**Comment by tmcw** [comment]
Hi Gilbert,

Sure! To produce the sort of results you're looking for, you could start with something like:

```js
var columns = Object.keys(results[0]);
var values = results.map(function (result) {
  return columns.map(function (key) {
    return result[key];
  });
});

var formattedResults = {
  columns: columns,
  values: values
};
```

Hope that helps!
