### ISSUE TITLE
ENOENT: no such file or directory, chmod nodebb

### ISSUE THREAD

**Issue by francedema** [mapbox/node-sqlite3#740]
I follow this guide to install nodebb:

https://nodebb.readthedocs.io/en/latest/installing/os/centos.html

When I do "npm install" I obtain this error:

npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /vagrant/nodebb/node_modules/nyc/node_modules/yargs/node_modules/window-size/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/nodebb/node_modules/nyc/node_modules/yargs/node_modules/window-size/cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/vagrant/nodebb/node_modules/nyc/node_modules/yargs/node_modules/window-size/cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

I installed node 7.2.0

Anyone can help  me?

**Comment by tmcw** [comment]
Thanks for the bug report!

This error doesn't mention sqlite3 anywhere: it looks like you've got an issue with window-size or vagrant.
