### ISSUE TITLE
node-uuid is deprecated

### ISSUE THREAD

**Issue by R3ido101** [mapbox/node-sqlite3#741]
Hi just to let you know if you are using node-uuid that is it deprecated please can you swap it to uuid 

Thanks

R3ido101

**Comment by tmcw** [comment]
Thanks for the report!

This package no longer depends on node-uuid, directly or indirectly.

```
~/src/node-sqlite3〉npm ls node-uuid
sqlite3@3.1.8 /Users/tmcw/src/node-sqlite3
└── (empty)

npm ERR! code 1
```
