### ISSUE TITLE
Hex string interpreted as exponential and converted to Inf.

### ISSUE THREAD

**Issue by juliangoacher** [mapbox/node-sqlite3#743]
If I run the following code:
```
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database('test.sqlite');
db.serialize( () => {
    db.run('CREATE TABLE test (value STRING)', []);
    var stmt = db.prepare('INSERT INTO test (value) VALUES (?)');
    var value = '3970e14784';
    stmt.run([ value ]);
    stmt.finalize();
});
db.close();
```
Then the value 'Inf' is inserted into the table, instead of the string '3970e14784'. The string is just a hex encoded value, but something seems to be interpreting it as a number in exponential format which yields an infinite value when converted... the same thing happens if the hex string is embedded directly into the statement SQL (i.e. "INSERT INTO test (value) VALUES ('3970e14784')").

I assume this is a bug? Or any suggestions for a work around?

**Comment by springmeyer** [comment]
Use `TEXT` type for the field. See https://www.sqlite.org/datatype3.html#type_affinity

**Comment by juliangoacher** [comment]
Thanks - should have picked up on that.
