### ISSUE TITLE
No Windows ia32 build of sqlite 3.1.8

### ISSUE THREAD

**Issue by davidfraser** [mapbox/node-sqlite3#748]
Trying to install a node module (appium) that requires sqlite 3.1.8 fails on Windows because there appears to be no prebuilt binary.

- https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.7/node-v46-win32-ia32.tar.gz resolves successfully
- https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-win32-ia32.tar.gz returns an Access Denied error:

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>469B668A2FBB7B8B</RequestId>
<HostId>
E1hHEUrfjgkdpGHI5f1PeFrpq1TYleAwPumnv+ITmZlSpKFyZd5VIsbKu3wdlowpdIlJ61yQEDU=
</HostId>
</Error>`

This is difficult to avoid when a whole tree of modules depend on the latest sqlite version.

**Comment by frankhale** [comment]
I was just bitten by this as well. Even though I am using x64 Node I had to download the ia32 module and place it in node_modules/sqlite3/lib/binding for it to work:

https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v51-win32-ia32.tar.gz

**Comment by Apollon77** [comment]
This issues broke my Appveyor builds from a project ... Will the files be provided soon?

**Comment by yliu05** [comment]
https://github.com/aaroncalderon/sqlite3-bin.git

**Comment by yliu05** [comment]
I also met the above problem:
[https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-win32-ia32.tar.gz ](https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-win32-ia32.tar.gz )  Access Denied.
Finally I find  [node-v46-win32-ia32 for node_sqlite3-v3.1.1](https://github.com/aaroncalderon/sqlite3-binary) to replace the above one, although I‘m using sqlite3.1.8 for [ghost](https://github.com/TryGhost/Ghost).
