### ISSUE TITLE
Publish build files within GitHub Releases

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/node-sqlite3#751]
Would it possible to have all the available (darwin, linux, win32) `sqlite3.node` builds located in this GitHub repo under the releases.

The reason why I'm asking is I never know the download URL of a specific build based on `arch` & `platform`.

A good example of this is from Electron, they have all the different builds under each release.

https://github.com/electron/electron/releases

Would this possible?

This issue should be considered low priority, it's just a nice to have.

Thanks,

**Comment by springmeyer** [comment]
> The reason why I'm asking is I never know the download URL of a specific build based on arch & platform.

The `node-pre-gyp reveal` command is designed for when you need to get the download urls manually:

```bash
~/projects/node-sqlite3[master]$ ./node_modules/.bin/node-pre-gyp reveal --silent | grep hosted_tarball
  "hosted_tarball": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-darwin-x64.tar.gz"
~/projects/node-sqlite3[master]$ ./node_modules/.bin/node-pre-gyp reveal --silent --target_arch=ia32 | grep hosted_tarball
  "hosted_tarball": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-darwin-ia32.tar.gz"
~/projects/node-sqlite3[master]$ ./node_modules/.bin/node-pre-gyp reveal --silent --target_platform=win32 | grep hosted_tarball
  "hosted_tarball": "https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-win32-x64.tar.gz"
```

This even works for alternative runtimes like node-webkit and electron: `./node_modules/.bin/node-pre-gyp reveal  --target_platform=win32 --runtime=electron --target=1.4.12`

**Comment by DenisCarriere** [comment]
Perfect! This helps a lot... having a lot of issues with an offline Windows environment.

Also in your wiki you have all the downloads available (which helps):

http://node-sqlite3.s3.amazonaws.com/index.html?path=Release/

My end goal is to have a functional Electron app using `sqlite3` on an offline Windows.

@springmeyer Thanks for the helpful comments!
