### ISSUE TITLE
native errors crash node js

### ISSUE THREAD

**Issue by lcop200685** [mapbox/node-sqlite3#759]
The error is the no control of native errors, when a native error is create, whatever error native crash the node js program, ignoring the try catch putting in node js code 

`error: SQLITE_CONSTRAINT: UNIQUE constraint failed:
    at Error (native)
`

this is a error, I know that a constraint error must generate a rollback but no close the program

I'm agree with your help

**Comment by springmeyer** [comment]
Can you provide a simple JS program that demonstrates the problem?

**Comment by lcop200685** [comment]
Sorry the error is because I'm using sqlite-transacctions https://www.npmjs.com/package/sqlite3-transactions sqlite3 capture exceptions ok

**Comment by lcop200685** [comment]
Sqlite3 provide a api to use sqlite transactional?
