### ISSUE TITLE
no mention of db.serialize in the API docs

### ISSUE THREAD

**Issue by ORESoftware** [mapbox/node-sqlite3#772]
https://github.com/mapbox/node-sqlite3/wiki/API

in the frontpage README, the primary example uses:

`db.serialize()`

 but I don't see this method in the API docs, where can I read about what that call is for?

**Comment by ORESoftware** [comment]
ok I found it, it was hidden, thanks!

**Comment by axelpale** [comment]
And where it was documented? I too have hard time finding it..

**Comment by axelpale** [comment]
Found it, here: https://github.com/mapbox/node-sqlite3/wiki/Control-Flow

Why we want to put API docs outside of API docs...
