### ISSUE TITLE
AWS secret access key stored in a public repository

### ISSUE THREAD

**Issue by senotrusov** [mapbox/node-sqlite3#787]
There is a AWS bucket "mapbox-node-binary.s3.amazonaws.com" with binaries for most Node versions and platforms. Every user of node-sqlite3 automatically downloads and installs binaries which resides on that host.

If I understand correctly, in that publicly available repository there is a file with an access key ID and secret access key: https://github.com/mapbox/node-sqlite3/blob/master/appveyor.yml#L5

I'm not familiar with your build process, but may that key pair give a write access to mapbox-node-binary.s3.amazonaws.com?

If it is indeed the case then anyone could publish any possible binary. That may lead to utterly unexpected consequences.

Sorry if I get it wrong.

**Comment by springmeyer** [comment]
@senotrusov thanks for your concern. We take security seriously so I appreciate you checking on this. The key pair does give write access to https://mapbox-node-binary.s3.amazonaws.com/sqlite3. However the values in the `appveyor.yml` are encrypted so they are not viable to use for writes unless decrypted, which only the appveyor systems can do, to enable windows publishing for commits we push.

**Comment by senotrusov** [comment]
@springmeyer No worries then. I'm really sorry for disturbing you, thanks a lot :)
