### ISSUE TITLE
testing json1 extension

### ISSUE THREAD

**Issue by kirankumar-ravuri** [mapbox/node-sqlite3#798]
I am trying simple example for json1 extension for which i am getting "**undefined**" for returned data.
All other queries except json1 extension are working fine. I am using  3.1.8 for sqlite( installed using npm install) and v4.6.0 for node and ubuntu 14.04.
Does it need any env variables to be set ??  Please let me know what is that I am missing.

```javascript
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
	db.run('SELECT json(?)', JSON.stringify({ok:true}), function(err, data){
		if(err)
			return console.log(err);
		console.log(data);
		db.close();
	});
});
```

**Comment by C3realGuy** [comment]
use .get instead of .run.

```
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
	db.get('SELECT json(?)', JSON.stringify({ok:true}), function(err, data){
		if(err)
			return console.log(err);
		console.log(data);
		db.close();
	});
});
```

**Comment by wmertens** [comment]
this issue should be closed

**Comment by kirankumar-ravuri** [comment]
Sorry for delay. I completely forgot about this. I am closing this issue.
