### ISSUE TITLE
cannot install sqlite3 on windows 10

### ISSUE THREAD

**Issue by angryhorse0905** [mapbox/node-sqlite3#808]
I have tried to build sqlite3 node package from source code.
but it does not work.

**Comment by kroggen** [comment]
You forgot to include the complete error message and the sequence of commands to reproduce the error

**Comment by shoutrain** [comment]
Looks I met the same error, please refer to the issue [https://github.com/mapbox/node-sqlite3/issues/814](url)

**Comment by shoutrain** [comment]
just updated my issue (tried on CentOS 7.2, save result): https://github.com/mapbox/node-sqlite3/issues/814  @kroggen

**Comment by springmeyer** [comment]
Going to close. Please re-open and provide the full error message from the terminal.

**Comment by shoutrain** [comment]
Actually I DID pasted all terminal output in the issue, please read it again #814. ------------------------------------------------------------------发件人：Dane Springmeyer <notifications@github.com>发送时间：2017年5月3日(星期三) 09:53收件人：mapbox/node-sqlite3 <node-sqlite3@noreply.github.com>抄　送：Rafael Gu <shoutrain_goo@aliyun.com>; Comment <comment@noreply.github.com>主　题：Re: [mapbox/node-sqlite3] cannot install sqlite3 on windows 10 (#808)
Going to close. Please re-open and provide the full error message from the terminal.—
