### ISSUE TITLE
Upgrading to 3.1.7 kills performance of this query

### ISSUE THREAD

**Issue by groovy9** [mapbox/node-sqlite3#812]
I have an app that runs the following long query via db.all():

`
select runs.id as id, runs.customer as customer, customers.name as custname, runs.[date] as [date], runs.shortdesc as shortdesc, round(runs.fee * (1.0 + runs.fuelpct / 100.0), 2) as total, runs.fee as fee, runs.fuelpct as fuelpct, group_concat(employees.firstname || "  " || substr(employees.lastname,1,1)) as drivername, group_concat(payroll.pay) as driverpay, runs.distance as distance, runs.scan as scan, group_concat(vehicles.id) as vehicle, group_concat(vehicles.unit) as unit from runs join customers on runs.customer = customers.id join payroll on runs.id = payroll.id join employees on payroll.driver = employees.id join vehicles on payroll.vehicle = vehicles.id  where  [date] >= ?  and  [date] <= ?  group by runs.id  order by [date] desc  limit ?  offset ?
`

The runs and payroll tables have around 80k rows, employees and vehicles under 200.

With node-sqlite3 versions 3.1.4, 3.1.5 and 3.1.6, this consistently finishes in under 50 ms in my test case.

Upgrading to 3.1.7 or 3.1.8 with no other changes, that query jumps to a consistent 450ms.

The changelog indicates 3.1.7 includes an sqlite lib upgrade and enabling FTS, but I'm not using any FTS tables.

Any ideas what's going on here?

**Comment by springmeyer** [comment]
Thanks for the report. I don't know what would cause this, but the sqlite upgrade does feel like a likely culprit. I don't see any obvious regressions reported fixed post 3.15.x at https://www.sqlite.org/news.html. But to narrow this down you could:

 - Build node-sqlite3 from source yourself (https://github.com/mapbox/node-sqlite3#source-install)
 - Replicate the slowdown with the latest master
 - Try upgrading or downgrading the sqlite3 version
 - Run your benchmark again

You'll need to do this yourself, unless you can provide a small and easy to run testcase the demonstrates the problem.

**Comment by groovy9** [comment]
It turned out to be an index issue.  For unrelated reasons, I did some query performance analysis, created some indexes, got it running as fast as I could, and then decided to try upgrading node-sqlite3 again to see if it changed anything, and the performance penalty is now gone.  

I suspect the older version of sqlite was doing something with automatic indexes that the new one doesn't, so since I hadn't optimized my indexes for the problem query, it bit me.
