### ISSUE TITLE
Failed db.get doesn't fail well

### ISSUE THREAD

**Issue by robcalcroft** [mapbox/node-sqlite3#818]
When running a `db.get` on some records the call will fail and throw an error exiting the app as it can't get the first record of an array of records. This seems like a poor way to fail as it doesn't correctly populate the `error` callback argument

**Comment by kroggen** [comment]
Show the code to reproduce the bug.

Have you tested it on more than 1 platform?

Have you tested it with different dbs? With different content?

Are there more apps accessing the same db file at the same time?

**Comment by robcalcroft** [comment]
Hmm I can't seem to reproduce, closing until I can consistently reproduce. Thanks
