### ISSUE TITLE
node 8

### ISSUE THREAD

**Issue by slajax** [mapbox/node-sqlite3#825]
Looks like the remote binaries are missing for node 8 and when pre-gyp falls back to build, [it implodes](https://travis-ci.org/feathersjs/feathers-knex/jobs/237679638). Anyone have any idea how to get these built or fix the v8 gyp source build?

**Comment by springmeyer** [comment]
I'm working on publishing binaries for node v8 now. Once https://travis-ci.org/mapbox/node-sqlite3/builds/237718791 is green they should be available for the current release and you can try your build again.

**Comment by slajax** [comment]
@springmeyer Rad, thanks for the quick response. I'll verify it on my build and report back.

**Comment by springmeyer** [comment]
Thanks. Although I made a mistake. The correct link to watch is https://travis-ci.org/mapbox/node-sqlite3/builds/237719330. Travis is slow right now - might be a while until that goes green.

**Comment by slajax** [comment]
All good, I caught that already ;) Watching it intently. I'll ping you when it's ready if you want to move onto more productive things!

**Comment by slajax** [comment]
@springmeyer looks good! Thanks for the quick help brotha!

**Comment by springmeyer** [comment]
Going to re-open this. WIndows is still missing node v8 binaries. Need to watch for appveyor to enable them https://github.com/appveyor/ci/issues/1581

**Comment by springmeyer** [comment]
done: https://ci.appveyor.com/project/Mapbox/node-sqlite3

**Comment by springmeyer** [comment]
Note: users of node v8 may hit `TypeError: Cannot read property 'version' of null`. Follow npm/npm#16926 for a fix.
