### ISSUE TITLE
Setup sqlite3 for electron pouchdb(adapter websql)

### ISSUE THREAD

**Issue by JeevanJain** [mapbox/node-sqlite3#833]
>C:\Users\Jeevan\.node-gyp\iojs-1.6.10\x64\iojs.lib : fatal error LNK1127: library is corrupt [F:\wirecamp\dh_offline\node_modules\sqlite3\build\node_sqlite3.vcxproj]
>gyp ERR! build error
>gyp ERR! stack Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe failed with exit code: 1
>gyp ERR! stack     at ChildProcess.onExit (C:\Users\Jeevan\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build
.js:258:23)
>gyp ERR! stack     at emitTwo (events.js:106:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
>gyp ERR! System Windows_NT 10.0.10586
>gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jeevan\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.6.10" "--arch=x64" "--target_platform=win32" "--dist-url=http://electron.
atom.io/" "--module_name=node_sqlite3" "--module_path=../lib/binding/electron-v1.6-win32-x64"
>gyp ERR! cwd F:\wirecamp\dh_offline\node_modules\sqlite3
>gyp ERR! node -v v6.10.2
>gyp ERR! node-gyp -v v3.6.2
>gyp ERR! not ok

**Comment by azurinko** [comment]
You need to rebuild the library as it says library is corrupt, I don't know if it means compiling library or what...

How can I replicate your error?
What command have you used?

Try to install it as 
`--build-from-source`

Then use `electron-rebuild` for it
