### ISSUE TITLE
Build from source failing

### ISSUE THREAD

**Issue by markmitton** [mapbox/node-sqlite3#862]
Hi,

I am trying to build node-sqlite3 module from source after multiple failed attempts to install using npm on the box. 

Platform details are:
Linux 4.4.68 (Yocto project release)
armv7l

I download the master source and then try to make, with the following output, can anyone point me in the right direction?

root@figcomp2:~/node_modules/node-sqlite3 [0] # make verbose
./node_modules/.bin/node-pre-gyp rebuild --loglevel=verbose
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/mnt/sdcard/node_modules/node-sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'rebuild',
node-pre-gyp verb cli   '--loglevel=verbose' ]
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@6.10.3 | linux | arm
node-pre-gyp verb command rebuild []
node-pre-gyp verb command clean []
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.3 | linux | arm
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.10.3 | linux | arm
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 6.10.3
gyp verb command install [ '6.10.3' ]
gyp verb install input version string "6.10.3"
gyp verb install installing version: 6.10.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 6.10.3
gyp verb build dir attempting to create "build" dir: /mnt/sdcard/node_modules/node-sqlite3/build
gyp verb build dir "build" dir needed to be created? /mnt/sdcard/node_modules/node-sqlite3/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /mnt/sdcard/node_modules/node-sqlite3/build/config.gypi
gyp verb config.gypi checking for gypi file: /mnt/sdcard/node_modules/node-sqlite3/config.gypi
gyp verb common.gypi checking for gypi file: /mnt/sdcard/node_modules/node-sqlite3/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/sdcard/node_modules/node-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/sdcard/.node-gyp/6.10.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/mnt/sdcard/.node-gyp/6.10.3',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/mnt/sdcard/.node-gyp/6.10.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/sdcard/node_modules/node-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm' ]
gyp info using node-gyp@3.6.2
gyp info using node@6.10.3 | linux | arm
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /mnt/sdcard/.node-gyp/6.10.3
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/mnt/sdcard/node_modules/node-sqlite3/build'
  LD_LIBRARY_PATH=/mnt/sdcard/node_modules/node-sqlite3/build/Release/lib.host:/mnt/sdcard/node_modules/node-sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /mnt/sdcard/node_modules/node-sqlite3/build/Release/obj/gen/sqlite-autoconf-3150000; python ./extract.py ./sqlite-autoconf-3150000.tar.gz "/mnt/sdcard/node_modules/node-sqlite3/build/Release/obj/gen"
Traceback (most recent call last):
  File "./extract.py", line 2, in <module>
    import tarfile
ImportError: No module named tarfile
make[1]: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c] Error 1
make[1]: Leaving directory '/mnt/sdcard/node_modules/node-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.68_figcomp2-01701-gfa8486c
gyp ERR! command "/usr/bin/node" "/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/bin/node-gyp.js" "build" "--loglevel=verbose" "--module=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm"
gyp ERR! cwd /mnt/sdcard/node_modules/node-sqlite3
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/sdcard/node_modules/node-sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.68_figcomp2-01701-gfa8486c
node-pre-gyp ERR! command "/usr/bin/node" "/mnt/sdcard/node_modules/node-sqlite3/node_modules/.bin/node-pre-gyp" "rebuild" "--loglevel=verbose"
node-pre-gyp ERR! cwd /mnt/sdcard/node_modules/node-sqlite3
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /mnt/sdcard/node_modules/node-sqlite3/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/mnt/sdcard/node_modules/node-sqlite3/lib/binding/node-v48-linux-arm' (1)
make: *** [Makefile:15: verbose] Error 1

**Comment by kkaefer** [comment]
The relevant error is:

```
import tarfile
ImportError: No module named tarfile
```

looks like your python installation doesn't have this functionality.

**Comment by markmitton** [comment]
Thanks @kkaefer. Unfortunately python on the target embedded system could not be altered. I ended up cross compiling for the target from my host machine successfully.
