### ISSUE TITLE
SQLCipher disappears when electron-rebuild is called

### ISSUE THREAD

**Issue by jimcloudman** [mapbox/node-sqlite3#872]
I'll preface this by saying that my problem may not be with `node-sqlite3`, but with `electron-rebuild` or `node-pre-gyp` - but for now, this seems to me like the proper place to make a request.

I want to use SQLite in an Electron app with the SQLCipher extension. I've had no problems using SQLite with Electron or SQLCipher with SQLite, but I'm unable to combine the three.

Following [the directions](https://github.com/mapbox/node-sqlite3/blob/master/README.md), I installed SQLite3 from source with the extension attached, like so:

`npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --save--dev`

(Note that this is on MacOS, and that I had installed sqlcipher with Homebrew as well, and had it added to the path. Not sure if that's actually necessary, but I did it anyway.)

Then to make sure that database access worked, I ran a [test script](https://gist.github.com/jimcloudman/84c05df6a3bcbd61cc0b5c9d5edd0ccd) with it. It created an encrypted database - attempting to open it with a tool like DB Browser for SQLite resulted in a password prompt. There's some concurrency issues (the unencrypted test starts before the encrypted test finishes), but it works well enough to confirm SQLCipher's presence. The console output looked like this:

    Encrypted DB access test
    Encrypted DB without password test
    Unable to access without password
    Encrypted access: SUCCESS

However, this doesn't work with Electron. If I try to run my Electron app with just that - without using `electron-rebuild` - I get the following error when I try to run the same code in the app as in my test script:

`Cannot find module '/Users/jim/SourceCode/[APP NAME]/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node`

That makes sense. The module is there, but its binding is for `node-v57-darwin-x64`. Not built for Electron. That's what `electron-rebuild` is for, so I ran the following:

`./node_modules/.bin/electron-rebuild -w sqlite3 -p`

The Electron app was now able to work with sqlite, but could not handle the encrypted database I just created from node:

`SQLITE_NOTADB: file is encrypted or is not a database`

I switched the filename so that it would create a new database. After getting around the concurrency issue, the app's test script showed that I was able to access the new database without a password. From what I could tell, SQLCipher was stripped out of the build - or SQLite3 was reinstalled entirely without the build-from-source & other flags. I'm not sure exactly how `electron-rebuild` works.

I saw in the Readme that there was `node-pre-gyp` integration for node-webkit, that I thought might be a hack around this problem. [The readme for that](https://github.com/mapbox/node-pre-gyp/blob/master/README.md) claims to have support for setting the `--runtime` flag to `electron`, so I gave that a try:

`npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --save-dev`

I got a response back saying that I had to set a `--target` flag when using `--runtime=electron`, so I set it to my Electron version of 1.7.6:

`npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=`brew --prefix` --runtime=electron --target=1.7.6 --save-dev`

I got a bunch of errors back which [didn't really make any sense](https://gist.github.com/jimcloudman/cc8d7219a48d2f1b70a13cebf52e5a2b) - references to io.js which I would've thought would have been long gone by now. The [npm error log is available here](https://gist.github.com/jimcloudman/54ccbdf0fb4ff26c80d3f5e71dabe3ce) for anyone who can decipher that.

With that, I'm out of ideas - I don't see how to compile this for Electron with encryption included. Any advice or guidance would be very appreciated!

**Comment by springmeyer** [comment]
> npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=brew --prefix--runtime=electron --target=1.7.6 --save-dev

That looks very close. You also need `--dist-url=https://atom.io/download/electron` to tell the build where to find the headers for electron. Without that is it looking for the nodejs headers for the given target.

**Comment by jimcloudman** [comment]
Wow, it's working now. I was not expecting it to be that easy!

Thank you for your help!

**Comment by springmeyer** [comment]
@jimcloudman great, can you ask you to create a PR with docs on how you got this working?

**Comment by jimcloudman** [comment]
I've added a PR with a new note added to the readme. If the wiki would be a better spot for it, let me know and I can add something there.

**Comment by bobnguyen** [comment]
Does it work for Windows 10 - sqlcipher + electron?

**Comment by muccix** [comment]
What if I have to distribute the electron app: does the target machine need to have sqlchiper installed?
