### ISSUE TITLE
 version glibc_2.14' not found@sqlite 3.1.11

### ISSUE THREAD

**Issue by neewbee** [mapbox/node-sqlite3#878]
OS@CentOS6 
node@8.4.0 
`npm install sqlite 3.1.10` is fine. but not 3.1.11

**Comment by evanhuang8** [comment]
Same here. Why bump the glibc version on a minor version bump (3.1.x)?

**Comment by springmeyer** [comment]
Can you provide the exact error you are seeing in your terminal? Please capture all the terminal output from your install and paste here. This error should not be happening and I can't, currently, see how it would happen. Please provide more info and confirm your versions.

**Comment by springmeyer** [comment]
I found the problem and fixed in https://github.com/mapbox/node-sqlite3/commit/7bfbcc46a09be145d6503cab6ca5c87516ca325a. This regression will be solved once I release `sqlite3@3.1.12`

**Comment by springmeyer** [comment]
sqlite3@3.1.12 is released. Please try again and re-open a new issue if the problem persists.

**Comment by neewbee** [comment]
awesome！
