### ISSUE TITLE
Attempting to run test with electron/angularjs results in many strange errors

### ISSUE THREAD

**Issue by danielcovill** [mapbox/node-sqlite3#882]
App can be seen here: https://github.com/danielcovill/budget-app

I can run the app without any trouble using npm run electron (after proper builds). Unfortunately, running npm run test causes failures with the following errors: 

`dan$ npm run test

> budget-app@0.0.0 test /Users/dan/projects/budget-app
> ng test

 10% building modules 1/1 modules 0 active19 09 2017 21:03:47.330:WARN [karma]: No captured browser, open http://localhost:9876/
19 09 2017 21:03:47.340:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
19 09 2017 21:03:47.341:INFO [launcher]: Launching browser Chrome with unlimited concurrency
19 09 2017 21:03:47.345:INFO [launcher]: Starting browser Chrome

WARNING in ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'npm' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util'
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js 39:27-49
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/node-gyp/lib/Find-VS2017.cs
Module parse failed: /Users/dan/projects/budget-app/node_modules/node-gyp/lib/Find-VS2017.cs Unexpected token (7:6)
You may need an appropriate loader to handle this file type.
| // Usage:
| // powershell -ExecutionPolicy Unrestricted -Version "2.0" -Command "&{Add-Type -Path Find-VS2017.cs; [VisualStudioConfiguration.Main]::Query()}"
| using System;
| using System.Text;
| using System.Runtime.InteropServices;
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

WARNING in ./~/sqlite3/lib/sqlite3.js
4:14-35 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sqlite3/~/node-pre-gyp/lib/pre-binding.js
19:22-48 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sqlite3/~/node-pre-gyp/lib/util/versioning.js
15:20-67 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sqlite3/~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sqlite3/~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sqlite3/~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/har-validator/~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

ERROR in ./~/sqlite3/~/node-pre-gyp/lib/info.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib'
 @ ./~/sqlite3/~/node-pre-gyp/lib/info.js 14:14-32
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/node-pre-gyp/lib/publish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib'
 @ ./~/sqlite3/~/node-pre-gyp/lib/publish.js 17:14-32
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/node-pre-gyp/lib/unpublish.js
Module not found: Error: Can't resolve 'aws-sdk' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib'
 @ ./~/sqlite3/~/node-pre-gyp/lib/unpublish.js 15:14-32
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/node-pre-gyp/lib/testbinary.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib'
 @ ./~/sqlite3/~/node-pre-gyp/lib/testbinary.js 10:9-33
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util'
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js 9:9-33
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/rc/index.js
Module parse failed: /Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/rc/index.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #! /usr/bin/env node
| var cc   = require('./lib/utils')
| var join = require('path').join
 @ ./~/sqlite3/~/node-pre-gyp/lib/info.js 11:13-26
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/osenv/osenv.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/osenv'
 @ ./~/sqlite3/~/osenv/osenv.js 3:11-35
 @ ./~/sqlite3/~/nopt/lib/nopt.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve '../package' in '/Users/dan/projects/budget-app/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 67:16-37
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/node-gyp/lib/node-gyp.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/node-gyp.js 16:20-44
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/node-gyp/lib/build.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/build.js 14:11-35
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/node-gyp/lib/configure.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/configure.js 19:9-33
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/node-gyp/lib/find-vs2017.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/node-gyp/lib'
 @ ./~/node-gyp/lib/find-vs2017.js 2:15-39
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/sqlite3/~/uid-number/uid-number.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/sqlite3/node_modules/uid-number'
 @ ./~/sqlite3/~/uid-number/uid-number.js 9:20-44
 @ ./~/sqlite3/~/tar-pack/index.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/package.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts

ERROR in ./~/osenv/osenv.js
Module not found: Error: Can't resolve 'child_process' in '/Users/dan/projects/budget-app/node_modules/osenv'
 @ ./~/osenv/osenv.js 3:11-35
 @ ./~/node-gyp/lib/configure.js
 @ ./~/node-gyp/lib ^\.\/.*$
 @ ./~/node-gyp/lib/node-gyp.js
 @ ./~/sqlite3/~/node-pre-gyp/lib/util/compile.js
 @ ./~/sqlite3/~/node-pre-gyp/lib ^\.\/.*$
 @ ./~/sqlite3/~/node-pre-gyp/lib/node-pre-gyp.js
 @ ./~/sqlite3/lib/sqlite3.js
 @ ./src/utils/settings.service.ts
 @ ./src/utils/settings.service.spec.ts
 @ ./src \.spec\.ts$
 @ ./src/test.ts
`

Many of these errors seem related to sqlite3. Apologies if this is totally unrelated to sqlite3 but I'm not really sure where else to go with this as I've been working on it for a while and that seems to be the thing that keeps coming up. I've seen similar issues discussed:
https://github.com/webpack/webpack/issues/4603
https://github.com/chentsulin/electron-react-boilerplate/issues/1155
but nobody seems to have quite this situation.

Am I missing something obvious?

**Comment by danielcovill** [comment]
Disregard. I see that mocha is required for unit testing and I was using Jasmine.

**Comment by Mydly** [comment]
I also encountered a similar problem
