### ISSUE TITLE
Can't download Binary from S3

### ISSUE THREAD

**Issue by MishUshakov** [mapbox/node-sqlite3#884]
https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v48-linux-arm.tar.gz

Permission denied 403, any solutions?

**Comment by springmeyer** [comment]
We do not provide pre-compiled binaries for arm arch. We tried to do this for a while (#298) but it was unsustainable since we do not have a way to automatically create them. So your build will fall back to a source compile whenn the `403` happens (which is really a 404)
