### ISSUE TITLE
HeidiSql or similar

### ISSUE THREAD

**Issue by mnemanja** [mapbox/node-sqlite3#893]
Hi there,
is there a way to visualize database tables like with HeidiSql?

**Comment by okaufmann** [comment]
Simething like ? http://sqlitebrowser.org/

**Comment by mnemanja** [comment]
I'm using node-sqlite3 with electron-forge. Should be ok.

I'll give it a try :) thanks

**Comment by wz2cool** [comment]
I have same problem. I can't find any tool to see tables or data.

**Comment by mnemanja** [comment]
This works. Thanks @okaufmann
