### ISSUE TITLE
Failed to locate CL.exe with electron.

### ISSUE THREAD

**Issue by mnemanja** [mapbox/node-sqlite3#897]
Hello there,

I'm trying to add sqlite3 to electron-forge. Clean install, works before adding sqlite3.
So, after the initial install I've added sqlite3 to the project, and after starting the project, the error gets shown asking for CL.exe:
`TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\www\rm-r\node_modules\sqlite3\build\deps\sqlite3.vcxproj]`

I've tried installing sqlite3 by using the following:
`npm install --save sqlite3 --build-from-source --runtime=electron --target=1.7.9 --dist-url=https://atom.io/download/electron`
but this shows the same error, and the install fails.

I've installed visual studio, and selected c++ etc. but I cannot find CL.exe anywhere.

I also have `node-gyp` and `node-pre-gyp` installed.

How can I solve this problem?

**Comment by wmertens** [comment]
a quick google search shows that this is a visual c++ configuration issue, not a sqlite3 issue. Vote to close.

**Comment by BokangThoola** [comment]
mnemanja what is the solution, why did you close?

**Comment by mnemanja** [comment]
Sorry @BokangThoola. I've ended up not using electron-forge. I've used electron + create-react-app combination done by some tutorial I've found and haven't had the same problem with the sqlite3.

**Comment by BokangThoola** [comment]
ok, thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
