### ISSUE TITLE
%1 is not a valid win32 application

### ISSUE THREAD

**Issue by sanjeevprasad** [mapbox/node-sqlite3#910]
I am building an electron app for windows and linux both. but unable to get it working on windows
![screenshot from 2017-11-18 12-01-37](https://user-images.githubusercontent.com/22276981/32977731-2dcf16ec-cc59-11e7-8c95-f55483d29063.png)
I am getting error on windows 7 ultimate 32 bit. running in virtual box..
and my dev environment is on linux 64 bit
currently using electron-builder to build for windows.
here is my package.json file
```
`{
	"name": "dportal",
	"version": "1.0.0",
	"description": "Distributor Portal",
	"main": "html/js/main.js",
	"private": true,
	"scripts": {
		"start": "electron ./app",
		"pack": "electron-builder --dir",
		"packw": "electron-builder -w --ia32 --dir",
		"postinstall": "electron-builder install-app-deps;electron-builder install-app-deps --platform=win32 --arch=ia32;"
	},
	"author": "author",
	"license": "MIT",
	"dependencies": {},
	"devDependencies": {
		"asar": "^0.14.0",
		"material-design-icons": "^3.0.1",
		"electron": "^1.7.9",
		"electron-builder": "^19.45.5"
	},
	"build": {
		"appId": "com.oapis.dportal",
		"asar": false
	}
}`
```
i able to run it on linux very well. no conflicts.
but on windows
what I think is that i am not able to generate correct node_sqlite3.node for win32

i even used electron-rebuild -f -w sqlite3  command to generate but that too is not working.
it took my whole yesterday trying to fix that. 
can anybody please tell me what the heck am i doing wrong.

**Comment by wave2588** [comment]
I have encountered this problem. Have you solved it?

**Comment by SanjeevPrasad** [comment]
I dedicated my whole week to it but got no solution.
- everything works fine on mac and linux.
- but on windows. it is not accepting the build.
- internet says windows build must be built on windows. but that too doesn't worked for me.
- finaly i am using sql.js ( https://github.com/kripken/sql.js/ )

and let me know if it somehow works for you.(if you continue to look for solution)

**Comment by rkistner** [comment]
This error typically means that something is trying to load a 64-bit DLL, while it is expecting a 32-bit one.

I've found the best way to debug these issues is with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon): Add a filter for the electron.exe process, and see which DLLs it is trying to load when you do `require('sqlite3')`.

**Comment by theone74** [comment]
Try to look at the contents of the * .node file - there is the usual Linux ELF. When build under Linux with wine, the electron-builder attempts to download [electron-v1.8-win32-ia32.tar.gz](https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/electron-v1.8-win32-ia32.tar.gz) and does not find it. After which he build ELF

**Comment by kewde** [comment]
Should be resolved nowadays with the prebuilt binaries.
