### ISSUE TITLE
socket hang up - ECONNRESET

### ISSUE THREAD

**Issue by Kiranbhat2005** [mapbox/node-sqlite3#913]
I am getting the below exception while inserting 80,000 records into DB. The exception is thrown after inserting 40,000 records and it occurs once in a while.
_{ [Error: socket hang up] code: 'ECONNRESET', response: undefined }_

Sqlite3 version  is 3.1.8 and the code is run on Linux.

The db connection is as follows.
  ```
var db = new sqlite3.cached.Database(dbFilename);
  db.configure('busyTimeout', 2000);
  db.run('PRAGMA journal_mode = OFF');
  db.run('PRAGMA synchronous = OFF');
```

Can you please help me to resolve the issue?

**Comment by wmertens** [comment]
I doubt this issue is related to sqlite3 because it doesn't use sockets… Where do you open connections?

I propose you close this issue to lighten the issue load of this project.

**Comment by Kiranbhat2005** [comment]
Thank you
