### ISSUE TITLE
403 fetching precompiled binary

### ISSUE THREAD

**Issue by jpillora** [mapbox/node-sqlite3#918]
```
> sqlite3@3.1.11 install /Users/jp/app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.11/node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.11 and node@9.2.1 (node-v59 ABI) (falling back to source compile with node-gyp)
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
```

And compile from source failed

**Comment by jacklau88** [comment]
i got the same problem too,how to fix it?

**Comment by DelboyDylan** [comment]
I was getting the same issue. To workaround it I've downgraded my NodeJS installation from 9, back to 8 for the time being (https://nodejs.org/dist/latest-v8.x/).

**Comment by ModernArtisan** [comment]
@springmeyer 
The same issue. Looks like **sqlite3** currently hasn't binary file for latest _node_ and _npm_ versions.
On any device
NPM version: 5.5.1
Node version: v9.2.1

Please, take attention, thanks.

**Comment by springmeyer** [comment]
I've just posted binaries for node v9 for the latest node-sqlite3@3.1.13 release. So if you install `v3.1.13` this should work now (binaries will be installed and no source compile will need to happen).

**Comment by Glebasty8** [comment]
@springmeyer Huge thanks for operative solution! Think this issue can be closed.

**Comment by ModernArtisan** [comment]
@springmeyer Huge thanks for operative solution! Think this issue can be closed.

**Comment by mrstegeman** [comment]
I'm still failing to download the binaries.

```
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v59-darwin-x64.tar.gz
```

**Comment by songzhj** [comment]
`403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.1/node-v48-darwin-x64.tar.gz`
node v6.9.2  has the same problem too

**Comment by vincent7128** [comment]
try #947 and https://github.com/mapbox/node-sqlite3#source-install

**Comment by nZeus** [comment]
Hi, I have the latest node (v9.7.1) installed on my RaspberryPi3 and still have this issue. I also tried with node v4, the same error:

```
pi@IT-Raspberry:~/pimatic-app $ sudo npm install sqlite3 --unsafe-perm

> sqlite3@3.1.13 install /home/pi/pimatic-app/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@9.5.0 (node-v59 ABI) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/pimatic-app/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
```

Can someone help me how to fix this?

**Comment by vincent7128** [comment]
@nZeus I run node-sqlite3 on the raspberry pi, it will install build from src.
The process take about 6 min on the raspberry pi 3.
```
$ uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
$ node -v
v9.7.1
$ npm -v
5.7.1
```

**Comment by nZeus** [comment]
This is what I have:

![image](https://user-images.githubusercontent.com/2727326/37059996-451eb48e-218f-11e8-916c-c89279aae5a8.png)

after an hour it's still the same >_<

**Comment by emeralis00** [comment]
Same issue. same versions as indicated above.

**Comment by rzr** [comment]
@nzeus 

I am able to build on pi3 but it's rather slow:

https://github.com/mapbox/node-sqlite3/issues/942

**Comment by jyy1082** [comment]
Is there anyone know how to fix it?

**Comment by neomh** [comment]
it works for me now 

export LDFLAGS="-L/usr/local/lib"
export CPPFLAGS="-I/usr/local/include -I/usr/local/include/sqlcipher"
export CXXFLAGS="$CPPFLAGS"
npm install sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

node -e 'require("sqlite3")'


and then as root 

npm install --only=production

**Comment by fmuntean** [comment]
Can we please get it to work without the need to compile?
Not everybody has the full development tools needed to do this.
I am currently getting the same issue on a Raspberry PI Zero.

**Comment by oppih** [comment]
node-sqlite3 does not support node v10 yet

see it here: https://github.com/mapbox/node-sqlite3/issues/977

**Comment by crazyyi** [comment]
@oppih Yes I have to revert back to node v9.5.0. Thanks for the info.

**Comment by springmeyer** [comment]
The errors reported here are all various and from different issues. Anyone hitting this please:

 - use latest node-sqlite@4.0.1
 - use latest npm@6
 - create a new issue if you are still having problems

If you are on ARM, we don't support binaries yet for easy install, so see #418

**Comment by answerquest** [comment]
> use latest node-sqlite@4.0.1
> use latest npm@6

@springmeyer Could you give exact `nvm` commands to do so?

**Comment by bbrzoska** [comment]
This keeps happening again with latest node v14.
```
node-pre-gyp WARN Tried to download(403): mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
```

**Comment by chrisgrounds** [comment]
Happens on node v15 too
