### ISSUE TITLE
How to use REGEXP operator?

### ISSUE THREAD

**Issue by ghost** [mapbox/node-sqlite3#93]
Quoting from the sqlite doc:

http://www.sqlite.org/lang_expr.html#regexp

> The REGEXP operator is a special syntax for the regexp() user function. No regexp() user function is defined by default and so >use of the REGEXP operator will normally result in an error message. If a application-defined SQL function named "regexp" is >added at run-time, that function will be called in order to implement the REGEXP operator.

Is it possible to add this custom function in node-sqlite3 to support REGEXP operator in sql queries?

**Comment by slawo** [comment]
+1 Would it be possible to add a regexp function in the default node package?

**Comment by Mithgol** [comment]
See https://github.com/mapbox/node-sqlite3/issues/140#issuecomment-25796039
