### ISSUE TITLE
No Works install GitHub

### ISSUE THREAD

**Issue by StasToken** [mapbox/node-sqlite3#931]
I try to install according to the instructions, I get an error

> sudo npm install https://github.com/mapbox/node-sqlite3/tarball/master
> 
> > sqlite3@3.1.13 install /tmp/node_modules/sqlite3
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-linux-ia32.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
> make: вход в каталог «/tmp/node_modules/sqlite3/build»
>   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
>   TOUCH Release/obj.target/deps/action_before_build.stamp
>   CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
> In file included from /usr/include/stdio.h:27:0,
>                  from Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c:11458:
> /usr/include/features.h:364:25: fatal error: sys/cdefs.h: Нет такого файла или каталога
>  #  include <sys/cdefs.h>
>                          ^
> compilation terminated.
> deps/sqlite3.target.mk:121: ошибка выполнения рецепта для цели «Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o»
> make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o] Ошибка 1
> make: выход из каталога «/tmp/node_modules/sqlite3/build»
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.8.0-59-generic
> gyp ERR! command "/home/master/node-v8.9.4-linux-x86/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32"
> gyp ERR! cwd /tmp/node_modules/sqlite3
> gyp ERR! node -v v8.9.4
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/home/master/node-v8.9.4-linux-x86/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> node-pre-gyp ERR! System Linux 4.8.0-59-generic
> node-pre-gyp ERR! command "/home/master/node-v8.9.4-linux-x86/bin/node" "/tmp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /tmp/node_modules/sqlite3
> node-pre-gyp ERR! node -v v8.9.4
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok 
> Failed to execute '/home/master/node-v8.9.4-linux-x86/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32/node_sqlite3.node --module_name=node_sqlite3 --module_path=/tmp/node_modules/sqlite3/lib/binding/node-v57-linux-ia32' (1)
> npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
> npm WARN tmp No description
> npm WARN tmp No repository field.
> npm WARN tmp No README data
> npm WARN tmp No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sqlite3@3.1.13 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/master/.npm/_logs/2018-01-07T07_49_19_381Z-debug.log
> sudo npm install https://github.com/mapbox/node-sqlite3/tarball/master  7,18s user 1,00s system 67% cpu 12,048 total
> 
   **npm install sqlite3**
Gives the same error

**Comment by springmeyer** [comment]
Looks like you are on a 32 bit linux system. We don't provide binaries for 32 bit, only 64 bit. Are you able to use a 64 bit system? If not, then the build will fall back to a source compile (like you are seeing) and for that to work you need a proper C++11 compiler and the deps needed for node-gyp: https://github.com/nodejs/node-gyp#on-unix
