### ISSUE TITLE
Support for 8.x and 9.x

### ISSUE THREAD

**Issue by Extarys** [mapbox/node-sqlite3#939]
I'm using node-webkit with node version 9.4.0. I would like to use sequelize too.
I was using better-sqlite3 which works fine but sequelize require the sqlite3 package.

Are you planning on supporting newer versions soon? The current LTS version is 8.9.4.

Thanks!

**Comment by Apollon77** [comment]
it is "in fact" working, also if it is not listed on the README :-)

**Comment by Extarys** [comment]
Really? I tried for hours without any results, I'll retry soon and post more details here if I get the same issue.

**Comment by risacher** [comment]
node-sqlite3 built for me with node 8.9.4, but not with 9.x (on Ubuntu 16.04)

**Comment by Extarys** [comment]
@risacher I made it under Linux Mint 18.2 with `npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.28.0`

**Comment by Apollon77** [comment]
Also not on nodejs 10!

**Comment by kibertoad** [comment]
@Extarys Is it still relevant? I think support for newer nodes was already fixed.
