### ISSUE TITLE
How to bind blob parameters in queries?

### ISSUE THREAD

**Issue by andreistreltsov** [mapbox/node-sqlite3#948]
I have a table with BLOB primary key (`id`):
    
    CREATE TABLE item (
        id BLOB PRIMARY KEY,
        title VARCHAR(100)
    );

In javascript models, the primary key (`id`) is represented as a HEX-encoded string:

    var item = { 
        id: "2202D1B511604790922E5A090C81E169",
        title: "foo"
    }

When I run the query below, the `id` parameter gets bound as a string. But I need it to be bound as a BLOB.

    db.run('INSERT INTO item (id, title) VALUES ($id, $title)', {
        $id: item.id,
        $title: item.title
    });

To illustrate, the above code seems to generate the following SQL:

    INSERT INTO item (id, title) VALUES ('2202D1B511604790922E5A090C81E169', 'foo');

What I need is this:

    INSERT INTO item (id, title) VALUES (X'2202D1B511604790922E5A090C81E169', 'foo');

At this point, the only way I know how to achieve this, is by string concatenation. There has to be a proper way, but I couldn't find it in the documentation or google.

**Comment by stevvvn** [comment]
`$id: Buffer.from(item.id, 'hex')`

**Comment by andreistreltsov** [comment]
It works, thank you!
