### ISSUE TITLE
Security vulnerability through outdated version of hoek

### ISSUE THREAD

**Issue by SebastianSchmidt** [mapbox/node-sqlite3#950]
node-sqlite3 is dependent on an outdated version of hoek (through the node-pre-gyp package), which has a [security vulnerability](https://hackerone.com/reports/310439).

```
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › hawk@3.1.3 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › hawk@3.1.3 › boom@2.10.1 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › hawk@3.1.3 › cryptiles@2.0.5 › boom@2.10.1 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › hawk@3.1.3 › sntp@1.0.9 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › request@2.81.0 › hawk@3.1.3 › sntp@1.0.9 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › request@2.81.0 › hawk@3.1.3 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › request@2.81.0 › hawk@3.1.3 › cryptiles@2.0.5 › boom@2.10.1 › hoek@2.16.3
sqlite3@3.1.13 › node-pre-gyp@0.6.39 › request@2.81.0 › hawk@3.1.3 › boom@2.10.1 › hoek@2.16.3
```

The [latest version of node-pre-gyp](https://github.com/mapbox/node-pre-gyp/issues/346) uses a version of hoek that fixes the vulnerability. The latest version of node-pre-gyp (0.7.0) no longer supports Node 0.10 and 0.14. However, Node 0.10 and 0.14 are no longer supported, so I think it's justifiable if node-sqlite3 also does not support these versions.

**Comment by springmeyer** [comment]
@SebastianSchmidt would you be up for creating a PR upgrading node-pre-gyp?

**Comment by SebastianSchmidt** [comment]
@springmeyer Yes, I'll take care of it.
