### ISSUE TITLE
Error on compilation OS X Sierra 10.12.6 (Xcode 9)

### ISSUE THREAD

**Issue by w0dm4n** [mapbox/node-sqlite3#951]
CXX(target) Release/obj.target/node_sqlite3/src/third_party/CodingConv/encodeutil.o
../src/third_party/CodingConv/encodeutil.cpp:179:31: error: use of undeclared identifier 'LC_ALL'
        string curLocale = setlocale(LC_ALL,NULL);
                                     ^
../src/third_party/CodingConv/encodeutil.cpp:180:12: error: use of undeclared identifier 'LC_ALL'
        setlocale(LC_ALL,"chs");
                  ^
../src/third_party/CodingConv/encodeutil.cpp:188:12: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
        setlocale(LC_ALL,curLocale.c_str());
                  ^~~~~~
                  P_ALL
/usr/include/sys/wait.h:80:2: note: 'P_ALL' declared here
        P_ALL,
        ^
../src/third_party/CodingConv/encodeutil.cpp:197:31: error: use of undeclared identifier 'LC_ALL'
        string curLocale = setlocale(LC_ALL,NULL);
                                     ^
../src/third_party/CodingConv/encodeutil.cpp:198:12: error: use of undeclared identifier 'LC_ALL'
        setlocale(LC_ALL,"chs");
                  ^
../src/third_party/CodingConv/encodeutil.cpp:206:12: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
        setlocale(LC_ALL,curLocale.c_str());
                  ^~~~~~
                  P_ALL
/usr/include/sys/wait.h:80:2: note: 'P_ALL' declared here
        P_ALL,
        ^
6 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/third_party/CodingConv/encodeutil.o] Error 1

**Comment by springmeyer** [comment]
`src/third_party/CodingConv/encodeutil.cpp` is not a file inside this repo. You must be looking for some different application?

**Comment by iskrisis** [comment]
I have exactly same thing happening to me. What is going on? @w0dm4n have you figured it out?

**Comment by kareniel** [comment]
@springmeyer is correct.

There's a package on npm named [`node-sqlite3`](https://github.com/zhs077/node-sqlite3) which is misleading because it shares this repo's name.

If you run into this issue, make sure you are using `npm install sqlite3` as opposed to `npm install node-sqlite3`.

**Comment by iskrisis** [comment]
@kareniel oh jeez you are right 🤦‍♂️
