### ISSUE TITLE
Pre-built binaries for win32 + Node 8.10.0 (ABI 57)?

### ISSUE THREAD

**Issue by ewrogers** [mapbox/node-sqlite3#960]
Trying to `npm install sqlite3` on Windows 10 with Node 8.10.0 LTS installed. It fails to load pre-built binaries and attempts to build from source.

Unfortunately, at my dayjob we do not have admin nor do we have access to a C++ compiler (MSBuild).

Is there a way to verify/cache the prebuilts somewhere locally (or within our own network)?

**Comment by igor-savin-ht** [comment]
Why can't you install C++ compiler libraries? These are free:
https://github.com/nodejs/node-gyp#on-windows

**Comment by springmeyer** [comment]
prebuild binaries are now available for node v8 and v10 in node-sqlite3@4.0.1
