### ISSUE TITLE
List pre-built binaries

### ISSUE THREAD

**Issue by iffy** [mapbox/node-sqlite3#966]
Where is the definitive list of Binaries this project publishes?  I recently upgraded my version of Electron and now sqlite is failing to build on Windows.  I'd like to figure out if I was downloading a pre-built binary before and now am not, but I can't find a list of the binaries being published.

I've read through https://github.com/mapbox/node-sqlite3/wiki/Binaries several times ... maybe I'm just not seeing it?

**Comment by iffy** [comment]
Pretty please?  Could you make https://mapbox-node-binary.s3.amazonaws.com/sqlite3/ browseable?

**Comment by JustinDFuller** [comment]
+1

**Comment by springmeyer** [comment]
The list of binaries for the latest release is:

```
$ ./node_modules/.bin/node-pre-gyp info
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.1
node-pre-gyp info using node@6.14.3 | darwin | x64
sqlite3/v4.0.1/electron-v1.3-linux-x64.tar.gz
sqlite3/v4.0.1/electron-v1.3-win32-ia32.tar.gz
sqlite3/v4.0.1/electron-v1.3-win32-x64.tar.gz
sqlite3/v4.0.1/electron-v1.6-linux-x64.tar.gz
sqlite3/v4.0.1/electron-v1.6-win32-ia32.tar.gz
sqlite3/v4.0.1/electron-v1.6-win32-x64.tar.gz
sqlite3/v4.0.1/electron-v1.7-linux-x64.tar.gz
sqlite3/v4.0.1/electron-v1.7-win32-ia32.tar.gz
sqlite3/v4.0.1/electron-v1.7-win32-x64.tar.gz
sqlite3/v4.0.1/electron-v1.8-linux-x64.tar.gz
sqlite3/v4.0.1/electron-v1.8-win32-ia32.tar.gz
sqlite3/v4.0.1/electron-v1.8-win32-x64.tar.gz
sqlite3/v4.0.1/electron-v2.0-linux-x64.tar.gz
sqlite3/v4.0.1/electron-v2.0-win32-ia32.tar.gz
sqlite3/v4.0.1/electron-v2.0-win32-x64.tar.gz
sqlite3/v4.0.1/node-v46-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v46-linux-x64.tar.gz
sqlite3/v4.0.1/node-v46-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v46-win32-x64.tar.gz
sqlite3/v4.0.1/node-v47-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v47-linux-x64.tar.gz
sqlite3/v4.0.1/node-v47-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v47-win32-x64.tar.gz
sqlite3/v4.0.1/node-v48-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v48-linux-x64.tar.gz
sqlite3/v4.0.1/node-v48-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v48-win32-x64.tar.gz
sqlite3/v4.0.1/node-v51-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v51-linux-x64.tar.gz
sqlite3/v4.0.1/node-v51-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v51-win32-x64.tar.gz
sqlite3/v4.0.1/node-v57-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v57-linux-x64.tar.gz
sqlite3/v4.0.1/node-v57-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v57-win32-x64.tar.gz
sqlite3/v4.0.1/node-v59-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v59-linux-x64.tar.gz
sqlite3/v4.0.1/node-v59-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v59-win32-x64.tar.gz
sqlite3/v4.0.1/node-v64-darwin-x64.tar.gz
sqlite3/v4.0.1/node-v64-linux-x64.tar.gz
sqlite3/v4.0.1/node-v64-win32-ia32.tar.gz
sqlite3/v4.0.1/node-v64-win32-x64.tar.gz
node-pre-gyp info ok 
```

Note: the `./node_modules/.bin/node-pre-gyp info` only works on travis (which has credentials to list the s3 bucket the binaries are in. So, to generate a public page that command could be run on travis and the result could be uploaded somewhere. If that interests anyone here as something to work on, let me know.

**Comment by springmeyer** [comment]
> Pretty please? Could you make https://mapbox-node-binary.s3.amazonaws.com/sqlite3/ browseable?

I can't make that browsable for security reasons. The list bucket action is blocked for non authenticated users and changing that is not easy.

**Comment by kputh** [comment]
How about making this list a part of each release artifact? It seems like something that can be automated. And it would answer the question which pre-build artifacts exist for future releases.

**Comment by SuperSandro2000** [comment]
This is especially useful if you want to support multiple architectures, environments and versions in something like a docker image and you need to know which combinations have pre builts and which don't.

**Comment by jmartindivmedianet** [comment]
Are there any pre-build node-sqlite3 binaries available for Android?

**Comment by vazra** [comment]
> The list of binaries for the latest release is:
> 
> ```
> $ ./node_modules/.bin/node-pre-gyp info
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.10.1
> node-pre-gyp info using node@6.14.3 | darwin | x64
> sqlite3/v4.0.1/electron-v1.3-linux-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.3-win32-ia32.tar.gz
> sqlite3/v4.0.1/electron-v1.3-win32-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.6-linux-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.6-win32-ia32.tar.gz
> sqlite3/v4.0.1/electron-v1.6-win32-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.7-linux-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.7-win32-ia32.tar.gz
> sqlite3/v4.0.1/electron-v1.7-win32-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.8-linux-x64.tar.gz
> sqlite3/v4.0.1/electron-v1.8-win32-ia32.tar.gz
> sqlite3/v4.0.1/electron-v1.8-win32-x64.tar.gz
> sqlite3/v4.0.1/electron-v2.0-linux-x64.tar.gz
> sqlite3/v4.0.1/electron-v2.0-win32-ia32.tar.gz
> sqlite3/v4.0.1/electron-v2.0-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v46-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v46-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v46-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v46-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v47-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v47-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v47-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v47-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v48-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v48-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v48-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v48-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v51-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v51-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v51-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v51-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v57-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v57-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v57-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v57-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v59-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v59-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v59-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v59-win32-x64.tar.gz
> sqlite3/v4.0.1/node-v64-darwin-x64.tar.gz
> sqlite3/v4.0.1/node-v64-linux-x64.tar.gz
> sqlite3/v4.0.1/node-v64-win32-ia32.tar.gz
> sqlite3/v4.0.1/node-v64-win32-x64.tar.gz
> node-pre-gyp info ok 
> ```
> 
> Note: the `./node_modules/.bin/node-pre-gyp info` only works on travis (which has credentials to list the s3 bucket the binaries are in). So, to generate a public page that command could be run on travis and the result could be uploaded somewhere. If that interests anyone here as something to work on, let me know.

@springmeyer is there any option to get the updated list? or is it possible to publish somewhere... like in docs ?

**Comment by Maus3rSR** [comment]
Same here... I can't know what electron version is compatible...

**Comment by Maus3rSR** [comment]
This page https://www.npmjs.com/package/sqlite3 is up to date and list the compatibilities
Could run it on Electron 8.2.5

**Comment by johnsonfash** [comment]
[sqlite3-package.tar.gz](https://github.com/user-attachments/files/17017669/sqlite3-package.tar.gz)
sqlite build binary for w32 using arm64 (macbook m1 & m2)

Built this for electron, as i couldnt compile electron with sqlite for windows exe

**Comment by cyrilfr** [comment]
There is no way to install older versions of sqlite3 now because the prebuilt S3 is blocked.

For example:

`npm i sqlite3@4`

won't work due to a 403 HTTP error (access denied).

Could you please make it available again?
