### ISSUE TITLE
Binaries: Access denied

### ISSUE THREAD

**Issue by dspangenberg** [mapbox/node-sqlite3#971]
electron-webpack couldn't download binaries  on yarn run dist:

```
Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.9.1
node-pre-gyp info using node@8.11.1 | darwin | x64
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
```

**Comment by Claytone** [comment]
Having the same issue on `yarn` and `npm`. I've tried reinstalling entirely, installing earlier versions, `--unsafe-perm`, pretty much everything from #612 

My only dependency on `sqlite3` is regular `sqlite`, which doesn't make sense to me. Is there a workaround?

**Comment by fmuntean** [comment]
I have the same issue.
Would be nice to not have to compile the package.
Some of the systems do not have compile tools installed.

**Comment by dspangenberg** [comment]
@Claytone Finally I get sqlite with electron-webpack working, but never use yarn – even to add something.

```
rm -rf node_modules
npm install
npm run dist
```

Works for me with node v8.11.1 and v9.11.1 (over nvm) and "sqlite3": "^4.0.0",

**Comment by kornelski** [comment]
I see it with yarn 1.7.0, but not with npm 6.0.1. 

    http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.9/node-v59-linux-x64.tar.gz

**Comment by springmeyer** [comment]
Anyone still having problems please try to v4.0.1 release: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401 and see the docs for electron at #1006

**Comment by zztiswb116** [comment]
> electron-webpack couldn't download binaries on yarn run dist:
> 
> ```
> Error output:
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp info using node-pre-gyp@0.9.1
> node-pre-gyp info using node@8.11.1 | darwin | x64
> node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
> node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-darwin-x64.tar.gz
> ```

fix it ？
