### ISSUE TITLE
update node-pre-gyp after vulnerability is fixed

### ISSUE THREAD

**Issue by filipesantoss** [mapbox/node-sqlite3#983]
`node-pre-gyp@0.9.0` is vulnerable to prototype pollution. This can be fixed by updating its dependencies.
https://github.com/mapbox/node-pre-gyp/issues/378

Please update as soon as `node-pre-gyp` is updated.

**Comment by Edo78** [comment]
It looks like https://github.com/mapbox/node-pre-gyp has updated.

Switching dependency to v.0.10.0 should fix this issue.

**Comment by colinkeenan** [comment]
What's preventing this fix? I thought it would be done a month ago.

**Comment by springmeyer** [comment]
This is fixed in the v4.0.1 release: https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401
