### ISSUE TITLE
I have a question about db.run function

### ISSUE THREAD

**Issue by z3214965** [mapbox/node-sqlite3#991]
I do not quite understand about “Note that it is not possible to run the statement again because it is automatically finalized after running for the first time. Any subsequent attempts to run the statement again will fail”

**Comment by colinkeenan** [comment]
In other words, if you need to run the same SQL code over and over in a loop or something, db.run is not the way to do it. Instead, prepare a statement (db.prepare...) and then run it over and over using statement.run. When done with the loop or whatever, finalize with statement.finalize.

Statement.run is the same as db.run except: "The callback behavior is identical to the Database#run method with the difference that the statement will not be finalized after it is run. This means you can run it multiple times."
